---
title: "Indicators calculation functions"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```



# Impact Indicators

## impact_2_2 
    
```{r function-impact_2_2}
#' impact_2_2
#' 
#' **Proportion of Persons of Concern residing in physically safe and secure 
#' settlements with access to basic facilities**
#' 
#' Once electricity, healthcare, drinking water and adequate shelter are
#'  calculated, check the values for each variable before, 
#'  calculating 2.2 impact indicator. 
#'  
#'  
#' ---------
#' # inter_electricity
#' 
#'  Households lighting provides a sense of safety and security within and outside 
#'  the households after sunset.
#'  
#'  If households lack access to electricity, especially for lighting and 
#'  connectivity, this affects the occupants' security and limits their 
#'  opportunities for socialization, learning and self-reliance.
#'  
#'  **Numerator**: Population with access to electricity, especially for lighting 
#'  and connectivity
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: *LIGHT01* = 1 & *LIGHT03* != 1, 96, 98
#'  
#' ---------
#' # inter_healthcare
#' 
#' Access to healthcare depends on availability of healthcare, including physical 
#' reach, acceptability and affordability for all.
#' For this indicator, the focus is on the availability of healthcare system.
#' According to [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf),
#'  primary healthcare facility should be accessible within one hour's walk from dwellings.
#'  **Numerator**: Population that can reach a primary healthcare facility within one hour from dwellings
#'  **Denominator**: Total population
#'  **Formula**: *HEA01* != 96, 98 & *HEA03* <= 60 
#'  (reachable within one hour/60 minutes)
#'  
#'  
#' ---------
#' # inter_drinkingwater
#' 
#' Access to clean drinking water is essential for a person's survival and well 
#' being and a precursor for achieving protection outcomes related to health, 
#' education and economic developed.
#' The calculation for access drinking water is linked to SGD Indicator
#'  [6.1.1](https://unstats.un.org/sdgs/metadata/files/Metadata-06-01-01.pdf).
#'  The questionnaire module and the analysis guidance is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis).
#'  
#'  **Numerator**: Population using improved sources of drinking water either in their dwelling/yard/plot or within 30 minutes round trip collection time
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: 
#'   *DWA03* < 30 (under 30 minutes), &
#'   *DWA01* != 7,9,13,96,98 &
#'   *DWA02* != 3
#'   
#'  This basic service is calculated from the main dataset
#'  There are three conditions as below  improved source, 
#'  in dwelling/yard/plot and reachable under 30 minutes 
#'  
#'  
#' ---------
#'  # inter_shelter
#' 
#' The right to access adequate housing is protected by international law.
#' The concept of "adequacy" means that housing is more than four walls and a 
#' roof as indicated in [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf).
#' Habitable housing primarily refers to the fact that the housing should provide
#'  protection from cold, damp, heat, rain, wind, and other threats to health,
#'   structural hazards, and disease vectors and it should not be overcrowded.
#'   As shelter/housing is primarily a contextual element, there may be 
#'   discrepancies from country to country on how this data is measured.
#'   
#'   Adequate shelter is measured based on having improved material for the
#'    dwelling as indicated in [DHS](https://dhsprogram.com/pubs/pdf/AS61/AS61.pdf) 
#'    publication on housing conditions which is also used by [MICS6](https://mics.unicef.org/tools).
#'    
#'    Overcrowding is also used which occurs if there are more than three people
#'     per habitable room as defined by [UN-Habitat](https://www.ncbi.nlm.nih.gov/books/NBK535289/table/ch3.tab2/).
#'     
#'     **Numerator**: Population that have access to adequate housing
#'     **Denominator**: Total population
#'     
#' **Formula**: 
#' 
#'      *DWE01* = 1,2 &
#'      *DWE02* = 3,4,5,6,7,8,9 & 
#'      *DWE03* = 8,9,10,11,12,13 & 
#'      *DWE04* = 10,11,12,13,14,15 & 
#'      crowding (*HH01*/*DWE05*) \<= 3
#' 
#' Adequate shelter is calculated from the main dataset
#' classify as habitable when improved/adequate shelter
#' 
#'  
#'  
#' ---------
#' # Compile alll
#'  Once all variables are correctly calculated, we can compute the final 
#'  variable for impact 2.2 indicator.
#'  **Numerator**: Population residing in physically safe and secure settlements with access to basic facilities
#'  **Denominator**: Total population
#'  **Formula**: *shelter*=1 & *electricity*=1 & *healthcare*=1 & *drinkingwater*=1
#'  
#'  Impact 2.2 is "1" if all services above are accessible
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                                           
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
impact_2_2 <- function(datalist ){
  
  ## Mapper 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. When anyone in your household is sick, where do they go to seek care?", 
"2. How do you reach this facility if you need to seek care?", 
"3. How long does it take to go there when you use the mode of transport that you mentioned above?", 
"4. Does this household use anything for lighting?", "5. What does this household use most of the time as energy for lighting, or as a light source?", 
"6. What source of electricity is used most of the time in this household?", 
"1. What is the main source of drinking water for this household?", 
"2. Where is this ${source} - ${source2} located?", "Unit", "Time", 
"4. In the last 30 days, has there been any time when your household did not have sufficient quantities of drinking water when needed?", 
"1.What type of dwelling does the household live in?", "2. Main material of the dwelling floor", 
"3. Main material of the roof.", "4. Main material of the exterior walls", 
"5. How many separate rooms do the members of your household occupy?", 
"8. Does your household pay any rent?", "9. Can your household generally afford to pay the rent without any major financial distress?", 
"What is the total number of persons in this household ? (including the respondent)"
)
              ,
            variable =  
c("HEA01", "HEA02", "HEA03", "LIGHT01", "LIGHT02", "LIGHT03", 
"DWA01", "DWA02", "DWA03a", "DWA03b", "DWA04", "DWE01", "DWE02", 
"DWE03", "DWE04", "DWE05", "DWE08", "DWE09", "HH01")
              ),
          modalitymap = data.frame(
            variable =  
c("HEA01", "HEA01", "HEA01", "HEA01", "HEA01", "HEA01", "HEA01", 
"HEA02", "HEA02", "HEA02", "HEA02", "HEA03", "LIGHT01", "LIGHT01", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", 
"LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA02", "DWA02", "DWA02", 
"DWA03a", "DWA03a", "DWA03b", "DWA04", "DWA04", "DWE01", "DWE01", 
"DWE01", "DWE01", "DWE01", "DWE01", "DWE01", "DWE01", "DWE01", 
"DWE01", "DWE02", "DWE02", "DWE02", "DWE02", "DWE02", "DWE02", 
"DWE02", "DWE02", "DWE02", "DWE02", "DWE03", "DWE03", "DWE03", 
"DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", 
"DWE03", "DWE03", "DWE03", "DWE03", "DWE04", "DWE04", "DWE04", 
"DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", 
"DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE05", 
"DWE08", "DWE08", "DWE09", "DWE09", "DWE09", "DWE09", "HH01")
               ,
            label =  
c("NGO facility (charity, faith-based organization)", "UNHCR Health Partner (Caritas, Save the Children)", 
"Public Clinics / Hospitals", "Private Clinics / Hospitals", 
"Pharmacy", "Other, specify", "Don't know", "By walk", "Private car", 
"Public transport (bus, boat)", "Other, specify", NA, "Yes", 
"No", "Electricity (including solar mini-grids, hybrid mini-grids and national grid)", 
"Electricity (from diesel generator)", "Solar home system", "Solar-powered lantern or flashlight", 
"Rechargeable flashlight, mobile, torch or lantern", "Battery powered flashlight, torch or lantern", 
"Biogas lamp", "LPG lamp", "Gasoline lamp", "Kerosene or paraffin lamp", 
"Oil lamp", "Candle", "Open fire", "Other, specify", "No electricity in household", 
"National grid connection from [COMPANY]", "Local mini grid", 
"Solar home system", "Solar lantern", "Electric generator", "Rechargeable battery", 
"Dry cell battery / torch", "Other, specify", "Don't know", "Piped Into Dwelling", 
"Piped Into Yard/Plot", "Piped To Neighbor", "Public Tap/Standpipe", 
"Tube Well/Borehole", "Protected Dug Well", "Unprotected Dug Well", 
"Protected Spring", "Unprotected Spring", "Rain Water Collection", 
"Tanker Truck/Water Vendor", "Cart With Small Tank/Drum", "Surface Water (River, Stream, Pond, Dam, Canal)", 
"Bottled Water", "Sachet Water", "Water Kiosk", "Other (Specify)", 
"Don't Know", "In Own Dwelling", "In Own Yard/Plot", "Elsewhere", 
"Minutes", "Hours", NA, "Yes", "No", "Apartment", "House", "Tent", 
"Caravan", "Collective Center", "Worksite/Unfinished Home/ Abandoned Building", 
"Farm Building", "School, mosque, church or other religious building", 
"Garage, shop, workshop, or other structure not meant as residential space", 
"Other (Specify)", "Earth/sand", "Dung", "Wood planks", "Palm/bamboo", 
"Parquet or polished wood", "Vinyl or asphalt strips", "Ceramic tiles", 
"Cement", "Carpet", "Other (Specify)", "No roof", "Thatch/Palm leaf", 
"Sod", "Rustic mat", "Palm/bamboo", "Wood planks", "Cardboard", 
"Metal/tin", "Wood", "Calamine/Cement fibre", "Ceramic tiles", 
"Cement", "Roofing shingles", "Other (Specify)", "No walls", 
"Cane/Palm/ Trunks", "Dirt", "Bamboo with mud", "Stone with mud", 
"Uncovered adobe", "Plywood", "Cardboard", "Reused wood", "Cement", 
"Stone with lime/ cement", "Bricks", "Cement blocks", "Covered adobe", 
"Wood planks/shingles", "Other (Specify)", NA, "Yes", "No", "Always", 
"Often", "Sometimes", "Never", NA)
               ,
            standard =  
c("1", "2", "3", "4", "5", "96", "98", "1", "2", "3", "96", NA, 
"1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "96", "1", "2", "3", "4", "5", "6", "7", "8", 
"96", "98", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "14", "15", "16", "96", "98", "1", "2", "3", 
"1", "2", NA, "1", "0", "1", "2", "3", "4", "5", "6", "7", "8", 
"9", "96", "1", "2", "3", "4", "5", "6", "7", "8", "9", "96", 
"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 
"13", "96", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "14", "15", "96", NA, "1", "0", "1", "2", "3", 
"4", NA)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 2.2")
  } else {

    ## now pull the calculation...
  
  ## Electricity ########
  datalist[["main"]]$electricity <-  dplyr::case_when(
    datalist[["main"]]$LIGHT01 == 1 & 
                       (as.integer(datalist[["main"]]$LIGHT03) != 1 | 
                        as.integer(datalist[["main"]]$LIGHT03)!= 96 |
                        as.integer(datalist[["main"]]$LIGHT03) != 98)  ~ 1, 
                     TRUE ~ 0 )
 
  datalist[["main"]]$electricity <- labelled::labelled(  
                            datalist[["main"]]$electricity,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                 label = "Access to electricity")
  ## healthcare ########
  datalist[["main"]]$healthcare <- 
           dplyr::case_when((
             as.integer(datalist[["main"]]$HEA01) != 96 | 
             as.integer(datalist[["main"]]$HEA01) != 98) & 
             as.integer(datalist[["main"]]$HEA03) <= 60 ~ 1,
                     TRUE ~ 0)

  datalist[["main"]]$healthcare <- labelled::labelled(datalist[["main"]]$healthcare,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                label = "Access to healthcare facility")

  ## Drinking Water #################
  datalist[["main"]]$time_DWA <-  dplyr::case_when(
    as.integer(datalist[["main"]]$DWA03a) == 1 ~ 1, 
    as.integer(datalist[["main"]]$DWA03a) == 2 ~ 60) 
  #convert hour into minutes
  # datalist[["main"]]$time_DWA <- as.numeric(datalist[["main"]]$time_DWA)
  datalist[["main"]]$time_tot <- datalist[["main"]]$time_DWA * 
      as.numeric(datalist[["main"]]$DWA03b)
  
  datalist[["main"]]$reachableU30 <-  dplyr::case_when( 
    datalist[["main"]]$time_tot > 30 ~  0, 
                                TRUE ~ 1) 
  # reachable under 30 minutes
  datalist[["main"]]$dwa_cond1 <-  dplyr::case_when(
    as.integer(datalist[["main"]]$DWA01) != 7 |
    as.integer(datalist[["main"]]$DWA01) != 9 |
    as.integer(datalist[["main"]]$DWA01) !=  13 | 
    as.integer(datalist[["main"]]$DWA01) !=  96 |
    as.integer(datalist[["main"]]$DWA01) !=  98 ~ 1,
                               TRUE ~ 0) 
  # improved source
  datalist[["main"]]$dwa_cond2 <- dplyr::case_when( 
    
    #UNDER30 MIN
    as.integer(datalist[["main"]]$reachableU30) == 1 & 
    as.integer(datalist[["main"]]$DWA02) == 3 ~ 1, 
    
    # NOT UNDER30 MIN
    as.integer(datalist[["main"]]$reachableU30) == 0 & 
    as.integer(datalist[["main"]]$DWA02) == 3 ~ 0, 
    
    # in the dwelling/yard/plot
    as.integer(datalist[["main"]]$DWA02) == 1 | 
    as.integer(datalist[["main"]]$DWA02) == 2 ~ 1, 
      TRUE ~ NA ) 
  
  datalist[["main"]]$drinkingwater <- dplyr::case_when(
      (as.integer(datalist[["main"]]$dwa_cond1) == 1 & 
        as.integer(datalist[["main"]]$dwa_cond2) == 1 ) ~ 1, 
      TRUE ~ 0)
  
  datalist[["main"]]$drinkingwater <- labelled::labelled(datalist[["main"]]$drinkingwater,
                              labels = c('Yes' = 1, 'No' = 0 ),
                                    label = "Access to drinking water")
  
  
  ## shelter #########
  #Only apartment and house
  datalist[["main"]]$dwe01_cat <- 
    dplyr::case_when(
      ( as.integer(datalist[["main"]]$DWE01) == 1 | 
        as.integer(datalist[["main"]]$DWE01) == 2) ~ 1, 
      TRUE ~ 0 )
  ## unimproved floor when earth,sand,clay,mud, dung or other
  datalist[["main"]]$dwe02_cat<- dplyr::case_when( 
      (as.integer(datalist[["main"]]$DWE02) == 1 | 
       as.integer(datalist[["main"]]$DWE02) == 2 | 
       as.integer(datalist[["main"]]$DWE02) == 96) ~ 0, 
      TRUE ~ 1 )
  ## unimproved roof all options except metal,wood,ceramic tiles, cement, roofing shingles/sheets
  datalist[["main"]]$dwe03_cat<- dplyr::case_when( 
      (as.integer(datalist[["main"]]$DWE03) == 8 |
       as.integer(datalist[["main"]]$DWE03) == 9 | 
       as.integer(datalist[["main"]]$DWE03) == 10 | 
       as.integer(datalist[["main"]]$DWE03) == 11 |
       as.integer(datalist[["main"]]$DWE03) == 12 | 
       as.integer(datalist[["main"]]$DWE03) == 13 ) ~ 1 , 
      TRUE ~ 0)
  
  ## improved wall: cement,stone,bricks,cement blocks, covered adobe, wood planks
  datalist[["main"]]$dwe04_cat<- dplyr::case_when( 
      (as.integer(datalist[["main"]]$DWE04) == 10| 
      as.integer(datalist[["main"]]$DWE04) == 11 | 
      as.integer(datalist[["main"]]$DWE04) == 12 | 
      as.integer(datalist[["main"]]$DWE04) == 13 | 
      as.integer(datalist[["main"]]$DWE04) == 14 | 
      as.integer(datalist[["main"]]$DWE04) == 15 ) ~ 1,
      TRUE ~ 0)
  
  ## Calculate crowding index - overcrowded when more than 3 persons
  datalist[["main"]]$crowding <- as.numeric(datalist[["main"]]$HH01) / 
       as.numeric(datalist[["main"]]$DWE05)
  
  datalist[["main"]]$dwe05_cat<- dplyr::case_when( ##if crowding <= 3, not overcrowded 
      datalist[["main"]]$crowding <= 3 ~ 1, 
      TRUE ~ 0)
  
  ####Calculate if all 5 conditions are met for adequate shelter
  ##dwe01_cat / dwe02_cat / dwe03_cat / dwe04_cat / dwe05_cat
  
  datalist[["main"]]$shelter<- dplyr::case_when(
      as.integer(datalist[["main"]]$dwe01_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe02_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe03_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe04_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe05_cat) == 0  ~  0, 
      
      as.integer(datalist[["main"]]$dwe01_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe02_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe03_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe04_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe05_cat)  == 1 ~  1)
  
  datalist[["main"]]$shelter <- labelled::labelled(  datalist[["main"]]$shelter,
                              labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Access to adequate shelter") 

  ## Compile alll ####
datalist[["main"]]$impact2_2 <- dplyr::case_when(
    as.integer(datalist[["main"]]$shelter) == 0 | 
    as.integer(datalist[["main"]]$electricity) == 0 | 
    as.integer(datalist[["main"]]$drinkingwater) == 0 | 
    as.integer(datalist[["main"]]$healthcare) == 0 ~  0,
    
    as.integer(datalist[["main"]]$shelter) == 1 & 
    as.integer(datalist[["main"]]$electricity) == 1 & 
    as.integer(datalist[["main"]]$drinkingwater) == 1 & 
    as.integer(datalist[["main"]]$healthcare) == 1 ~  1)

datalist[["main"]]$impact2_2 <- labelled::labelled(
  datalist[["main"]]$impact2_2,
                            labels =c(
                              "Yes" = 1,
                              "No" = 0
                            ),
    label = "Proportion of PoCs residing in physically safe and secure settlements with access to basic facilities") 

  }
  return(datalist)
}
```
  
```{r example-impact_2_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply calculation
datalist <-  impact_2_2(datalist)

table(datalist[["main"]]$impact2_2, useNA = "ifany")

fct_plot_indic_donut(indicator = datalist[["main"]]$impact2_2,
                     iconunicode = "f140") 


## Can get the details as well

table(datalist[["main"]]$electricity, useNA = "ifany")
fct_plot_indic_donut(indicator = datalist[["main"]]$electricity,
                     iconunicode = "f0e7") 

table(datalist[["main"]]$healthcare, useNA = "ifany")
fct_plot_indic_donut(indicator = datalist[["main"]]$healthcare,
                     iconunicode = "f479") 

 
table(datalist[["main"]]$drinkingwater, useNA = "ifany")
fct_plot_indic_donut(indicator = datalist[["main"]]$drinkingwater,
                     iconunicode = "e006") 

## Check intermediary variables
table(datalist[["main"]]$dwa_cond1, useNA = "ifany")
table(datalist[["main"]]$reachableU30, useNA = "ifany")
table(datalist[["main"]]$DWA02, useNA = "ifany")
table(datalist[["main"]]$dwa_cond2, useNA = "ifany")

# Tabulate
table(datalist[["main"]]$dwe01_cat, useNA = "ifany")
table(datalist[["main"]]$dwe02_cat, useNA = "ifany")
table(datalist[["main"]]$dwe03_cat, useNA = "ifany")
table(datalist[["main"]]$dwe04_cat, useNA = "ifany")
table(datalist[["main"]]$dwe05_cat, useNA = "ifany")
table(datalist[["main"]]$shelter, useNA = "ifany")
#plot
fct_plot_indic_donut(datalist[["main"]]$shelter,
                     iconunicode = "e54f") 

```
  
```{r tests-impact_2_2}
test_that("impact2_2 works", {
  expect_true(inherits(impact_2_2, "function")) 
})
```
  

## impact2_3
    
```{r function-impact2_3}
#' impact2_3
#' 
#' **Proportion of PoC with access to health services** 
#' 
#' This indicator measures access to primary health care services for persons 
#' of concern in need of health services.
#' 
#' Health services refers to preventive, pro-motive, curative, rehabilitative 
#' and palliative health services.
#' 
#' It is linked to SDG indicator [3.8.1](https://www.who.int/data/gho/data/themes/topics/service-coverage) 
#' on the coverage of essential health services.
#' 
#' The standard questions for this indicator are taken from UNHCR's [HAUS](https://www.unhcr.org/strategic-health-information.html) monitors trends
#'  in how refugees outside of camps access and utilize health services over time.
#'  Healthcare can be delivered through a combination of community level, mobile
#'   and fixed healthcare facilities.
#'   The number, type and location of each will vary by context.
#'   The standard questionnaire module will help us to understand these differences.
#'   
#'   | Standard Questions |
#'   |:------------------:|
#'   |  HACC01 - HACC04   |
#'   
#'   **Numerator**: Population who have received the asked for health services in the previous 30 days
#'   
#'   **Denominator**: Total population who have asked for health services in the previous 30 days
#'   
#'   **Formula**: *HACC01*=1 + / ((*HACC03*=1 & *HACC04*!=7,8,96) + *HACC01*=1)
#'   
#'   This indicator comes from the individual dataset 
#'   Calculate those who were not able to access due to reasons 
#'   unrelated to asked services (when HACC04 is 7 or 8 or 96)
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                                           
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
impact2_3 <- function(datalist ){
  
#   # Mapper , 
# mapper = list(
#            hierarchy = "ind",
#           variablemap = data.frame(
#             label = 
# c("1. During the past 30 days, has ${name_individual} consulted a health practitioner, dentist, traditional healer, or pharmacist, or visited a health center?", 
# "2. For what reason(s) did ${name_individual} seek consultation?", 
# "3. During the past 30 days, has ${name_individual} needed health services that’s/he could not have access to?", 
# "4. Why has ${name_individual} been unable to access a medical treatment in the past 30 days?"
# )
#               ,
#             variable =  
# c("HACC01", "HACC02", "HACC03", "HACC04")
#               ),
#           modalitymap = data.frame(
#             variable =  
# c("HACC01", "HACC01", "HACC02", "HACC02", "HACC02", "HACC02", 
# "HACC02", "HACC02", "HACC03", "HACC03", "HACC04", "HACC04", "HACC04", 
# "HACC04", "HACC04", "HACC04", "HACC04", "HACC04", "HACC04", "HACC04", 
# "HACC04")
#                ,
#             label =  
# c("Yes", "No", "Illness", "Injury", "General check-up (not for pregnancy)", 
# "Pre/Postnatal check-up", "Giving birth", "Other (Specify)", 
# "Yes", "No", "Lack of money", "No medical personnel available", 
# "Turned away because facility was full", "Turned away because facility was closed", 
# "Hospital/Clinic not having enough supplies or tests", "Health facility is too far", 
# "Fear of contracting a communicable disease (e.g. COVID-19)", 
# "Lockdown/Travel restrictions", "Too Far/transport issues", "Health facility is destroyed", 
# "Other (Specify)")
#                ,
#             standard =  
# c("1", "0", "1", "2", "3", "4", "5", "96", "1", "0", "1", "2", 
# "3", "4", "5", "6", "7", "8", "9", "10", "96")
#               ))
#   ## So first we check that we have what we need in the data set based on the mapper
#   check_map <- fct_check_map(datalist = datalist,
#                              mapper = mapper)
#   if ( check_map == FALSE) {
#    cat( "There are missing data requirement to calculate Indicator Impact 2.3")
#   } else {
#  
#  
#   datalist[["ind"]]$health_NOacc <- dplyr::case_when(
#     as.integer(datalist[["ind"]]$HACC03) ==  1 & 
#       (as.integer(datalist[["ind"]]$HACC04_7) ==  1 | 
#        as.integer(datalist[["ind"]]$HACC04_8) ==  1 | 
#        as.integer(datalist[["ind"]]$HACC04_96) ==  1 ) ~  0,
#     
#     as.integer(datalist[["ind"]]$HACC03) ==  1 & 
#      (as.integer(datalist[["ind"]]$HACC04_1) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_2) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_3) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_4) ==  1 |
#       as.integer(datalist[["ind"]]$HACC04_5) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_6) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_9) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_10) ==  1) ~  1, 
#     
#     TRUE ~  0)
# # table(datalist[["ind"]]$health_NOacc, useNA = "ifany")
#  
# datalist[["ind"]]$health_NOacc <- as.numeric(datalist[["ind"]]$health_NOacc)
# datalist[["ind"]]$HACC01 <- as.numeric(datalist[["ind"]]$HACC01)
# 
# 
#  ## Add up who needed services ( both who accessed and did not access)
# datalist[["ind"]]$HACC_need <- datalist[["ind"]]$HACC01 + datalist[["ind"]]$health_NOacc
# 
# datalist[["ind"]]$impact2_3 <- datalist[["ind"]]$HACC01 / datalist[["ind"]]$HACC_need 
# 
# datalist[["ind"]]$impact2_3 <- dplyr::case_when(
#     datalist[["ind"]]$impact2_3 == 1   ~ 1, 
#     datalist[["ind"]]$impact2_3 == 0.5 ~ 0,
#     datalist[["ind"]]$impact2_3 == 0   ~ 0, 
#     TRUE ~ NA_real_ )
# 
# datalist[["ind"]]$impact2_3  <- labelled::labelled( datalist[["ind"]]$impact2_3,
#    labels =c( "Yes"=1,   "No"=0 ),
#    label = "Proportion of PoC with access to health services")
#    }
#    return(datalist)
}
```
  
```{r example-impact2_3, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
# datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#                                                  package = "IndicatorCalc"))
# ## Apply calculation
# datalist <- impact2_3(datalist )
# 
# ## Visualise value
# fct_plot_indic_donut(indicator = datalist[["ind"]]$impact2_3,
#                      iconunicode = "f140") 

```
  
```{r tests-impact2_3}
test_that("impact2_3 works", {
  expect_true(inherits(impact2_3, "function")) 
})
```
  

## impact3_2a
    
```{r function-impact3_2a}
#' impact3_2a
#' 
#'  **Proportion of Persons of Concern enrolled in primary education** 
#'  
#'  This indicator measures the number of students enrolled in primary education,
#'   regardless of age, expressed as a percentage of the official school-age population 
#'   corresponding to the respective same level of education.
#'   
#'   This is also referred to as Gross enrollment rate (GER).
#'   
#'   It is linked to SGD indicator 4.1.1 on quality education.
#'   
#'   The standard questions for this indicator are taken from UNHCR's
#'    [Standardized Education Module](https://www.unhcr.org/60804b214.pdf) which 
#'    are adapted primarily from the IHSN/EPDC and MICS indicator and questionnaire frameworks.
#'    
#'    *Definitions*:
#'    
#'    1.  "Enrollment" refers individuals officially registered in a primary/secondary school education programme.
#'    
#'    2.  "Primary education" is designed to provide students with fundamental skills in reading, writing and mathematics.
#'    
#'    Duration typically varies from 4 to 7 years.
#'    The most common duration is 6 years.
#'    It corresponds to ISCED (International Standard Classification of Education) level 1.
#'    
#'    3.  "Primary school age" depends on the education system and it varies from country to country.
#'    Children typically enter in primary education between age 5 and 7 and leave at the age of 10 and 12.
#'    
#'    | Standard Questions |
#'    |:------------------:|
#'    |    EDU01-EDU04     |
#'    
#'    **Numerator**: Population enrolled in primary education (regardless of age)
#'    **Denominator**: Total primary school age population (to be adjusted by the country for enumeration)
#'    
#'    **Formula**: (*EDU01*=1 & *EDU02*=1 & *EDU03*=2) / Number of children aged from 6 to 10
#' 
#' This indicator comes from the individual dataset
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
impact3_2a <- function(datalist ){

  ## Mapper 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. Has ${child_edu_name} ever attended school?", "2. Did ${child_edu_name} attend school or pre-school at any time during current school year?", 
"3. During this/that school year , what level is (was) ${child_edu_name} attending?", 
"4. What type of school?", "6. Can you estimate how old is ${HH02}?"
)
              ,
            variable =  
c("EDU01", "EDU02", "EDU03", "EDU04", "HH07")
              ),
          modalitymap = data.frame(
            variable =  
c("EDU01", "EDU01", "EDU02", "EDU02", "EDU03", "EDU03", "EDU03", 
"EDU03", "EDU03", "EDU03", "EDU03", "EDU04", "EDU04", "EDU04", 
"EDU04", "EDU04", "EDU04", "EDU04", "HH07")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Early Childhood Education or Pre-primary", 
"Primary", "Secondary", "Secondary - Technical and Vocational Education and Training (TVET)", 
"Post-secondary - Technical and Vocational Education and Training (TVET)", 
"Tertiary", "Don’t know", "Government or public", "UN or NGO (non-governmental organization)", 
"Religious or faith-based organization", "Community", "Private", 
"Other (specify)", "Don’t know", NA)
               ,
            standard =  
c("1", "0", "1", "0", "1", "2", "3", "4", "5", "6", "98", "1", 
"2", "3", "4", "5", "96", "98", NA)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 3.2.a")
  } else {

datalist[["ind"]]$edu_primary<- dplyr::case_when(
    as.integer(datalist[["ind"]]$EDU01) == 1 & 
    as.integer(datalist[["ind"]]$EDU02) == 1 & 
    as.integer(datalist[["ind"]]$EDU03) == 2 ~ 1, 
    
    as.integer(datalist[["ind"]]$EDU01) == 0 | 
    as.integer(datalist[["ind"]]$EDU02) == 0 ~ 0, 
    
    TRUE ~ 0)

#Adjust age group for primary school  enrollment --> this to go in function var...
datalist[["ind"]]$age_primary<- dplyr::case_when(
    as.integer(datalist[["ind"]]$HH07) >= 6 &
    as.integer(datalist[["ind"]]$HH07) <= 10 ~ 1, 
    TRUE ~ NA_real_) 

datalist[["ind"]]$impact3_2a <- sum(datalist[["ind"]]$edu_primary, na.rm = TRUE) /
                                sum(datalist[["ind"]]$age_primary, na.rm = TRUE)

datalist[["ind"]]$impact3_2a  <- labelled::labelled(datalist[["ind"]]$impact3_2a,
  labels = c('Yes' = 1, 'No' = 0 ),
  label = "Proportion of persons of concern enrolled in primary education")

   }
   return(datalist)
}
```
  
```{r example-impact3_2a, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply calculation
datalist <- impact3_2a(datalist  )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$impact3_2a,
                     iconunicode = "f140")  
```
  
```{r tests-impact3_2a}
test_that("impact3_2a works", {
  expect_true(inherits(impact3_2a, "function")) 
})
```
   
 
## impact3_2b
    
```{r function-impact3_2b}
#' impact3_2b
#' 
#' **Proportion of Persons of Concern enrolled in secondary education**
#' 
#' This indicator measures the number of students enrolled in secondary education,
#'  regardless of age, expressed as a percentage of the official school-age population
#'   corresponding to the respective same level of education.
#'   
#'   This is also referred to as Gross enrollment rate (GER).
#'   It is linked to SGD indicator 4.1.1 on quality education.
#'   
#'   The standard questions for this indicator are taken from UNHCR's [Standardized Education Module](https://www.unhcr.org/60804b214.pdf) which are adapted primarily from 
#'   the IHSN/EPDC and MICS indicator and questionnaire frameworks.
#'   
#'   Definitions:
#'   
#'   1.  "Enrollment" refers individuals officially registered in a primary/secondary school education programme.
#'   
#'   2.  "Secondary education" provides learning and educational activities building on primary education and preparing for both first labour market entry as well as further study.
#'   
#'   The common duration is 6 years and is often divided between lower and upper secondary education (corresponding respectively to ISCED 2 and 3).
#'   
#'   3.  "Secondary school age" depends on the education system and differ from 
#'   country to country. 
#'   Children typically enter secondary education between age 11 and 13 and leave between age 17-19.
#'   
#'   4.  Whenever possible, operations are encouraged also to disaggregate data between lower and upper secondary
#'   
#'   | Standard Questions |
#'   |:------------------:|
#'   |    EDU01-EDU04     |
#'   
#'   **Numerator**: Population enrolled in secondary education (regardless of age)
#'   **Denominator**: Total secondary school age population (to be adjusted by the country for enumeration)
#'   
#'   **Formula**: (*EDU01*=1 & *EDU02*=1 & (*EDU03*=3,4) / Number of children aged from 11 to 18
#'   
#'   This indicator comes from the individual dataset
#'   
#'   Include if they are attending secondary or secondary -technical and vocational
#'    
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
impact3_2b <- function(datalist ){
  # mapper , 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. Has ${child_edu_name} ever attended school?", "2. Did ${child_edu_name} attend school or pre-school at any time during current school year?", 
"3. During this/that school year , what level is (was) ${child_edu_name} attending?", 
"4. What type of school?", "6. Can you estimate how old is ${HH02}?"
)
              ,
            variable =  
c("EDU01", "EDU02", "EDU03", "EDU04", "HH07")
              ),
          modalitymap = data.frame(
            variable =  
c("EDU01", "EDU01", "EDU02", "EDU02", "EDU03", "EDU03", "EDU03", 
"EDU03", "EDU03", "EDU03", "EDU03", "EDU04", "EDU04", "EDU04", 
"EDU04", "EDU04", "EDU04", "EDU04", "HH07")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Early Childhood Education or Pre-primary", 
"Primary", "Secondary", "Secondary - Technical and Vocational Education and Training (TVET)", 
"Post-secondary - Technical and Vocational Education and Training (TVET)", 
"Tertiary", "Don’t know", "Government or public", "UN or NGO (non-governmental organization)", 
"Religious or faith-based organization", "Community", "Private", 
"Other (specify)", "Don’t know", NA)
               ,
            standard =  
c("1", "0", "1", "0", "1", "2", "3", "4", "5", "6", "98", "1", 
"2", "3", "4", "5", "96", "98", NA)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 3.2.b")
  } else {
  
datalist[["ind"]]$edu_secondary<- dplyr::case_when(
    as.integer(datalist[["ind"]]$EDU01) == 1 & 
    as.integer(datalist[["ind"]]$EDU02) == 1 & 
     ( as.integer(datalist[["ind"]]$EDU03) == 3 | 
       as.integer(datalist[["ind"]]$EDU03) == 4) ~ 1, 
    
    as.integer(datalist[["ind"]]$EDU01) == 0 | 
    as.integer(datalist[["ind"]]$EDU02) == 0 ~ 0, 
    TRUE ~ 0)


#Adjust age group for secondary school enrollment 
##calculated as 11 to 18 above  --> put as function variable...

datalist[["ind"]]$age_secondary<- dplyr::case_when(
    as.integer(datalist[["ind"]]$HH07) >= 11 & 
    as.integer(datalist[["ind"]]$HH07) <= 18 ~ 1, 
    TRUE ~ NA_real_)
    
datalist[["ind"]]$impact3_2b <- sum(datalist[["ind"]]$edu_secondary, na.rm= TRUE) / 
                                sum(datalist[["ind"]]$age_secondary, na.rm = TRUE)

datalist[["ind"]]$impact3_2b  <- labelled::labelled(datalist[["ind"]]$impact3_2b,
                            labels = c('Yes' = 1, 'No' = 0 ),
  label = "Proportion of persons of concern enrolled in secondary education")

   }
   return(datalist)
}
```
  
```{r example-impact3_2b, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply calculation
datalist <- impact3_2b(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$impact3_2b,
                     iconunicode = "f140")  
 
```
  
```{r tests-impact3_2b}
test_that("impact3_2b works", {
  expect_true(inherits(impact3_2b, "function")) 
})
```
  
 
## impact3_3
    
```{r function-impact3_3}
#' impact3_3
#' 
#' **Proportion of population that feel safe walking alone in their neighbourhood**
#' 
#' This indicator measures the proportion of persons of concern who self-report 
#' feeling safe while walking alone in her/his neighborhood after dark.
#' It is linked to SDG indicator [16.1.4](https://unstats.un.org/sdgs/metadata/files/Metadata-16-01-04.pdf).
#' 
#' The standard module for this indicator is taken from SGD indicator owner UNODC.
#' This indicator only pertains to self-reported feeling of 'safety' and not 
#' 'security' since security is associated with additional external factors.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       SAF01        |
#' 
#' **Numerator**: Population who self-report feeling safe walking alone in 
#' their neighborhood after dark
#' 
#' **Denominator**: Total population
#' **Formula**: *SAF01*=1,2 / *SAF01*=1,2,3,4
#' 
#' This indicator comes from main dataset based on the respondent randomly
#'  selected for individual level
#'  
#'  if unsafe or very unsafe 0, 98 and 99 go into blank
#'  I never walk alone will also go into blank if any
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
impact3_3 <- function(datalist ){
  
  # Mapper 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
"1. How safe does ${name_selectedadult18} feel walking alone in your area/neighbourhood after dark?"
              ,
            variable =  
"SAF01"
              ),
          modalitymap = data.frame(
            variable =  
c("SAF01", "SAF01", "SAF01", "SAF01", "SAF01", "SAF01")
               ,
            label =  
c("Very safe", "Fairly safe", "Bit unsafe", "Very unsafe", "Don’t know", 
"Prefer not to respond")
               ,
            standard =  
c("1", "2", "3", "4", "98", "99")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 3.3")
  } else {
  
datalist[["main"]]$impact3_3 <- dplyr::case_when(
     as.integer(datalist[["main"]]$SAF01) == 1 | 
     as.integer(datalist[["main"]]$SAF01) == 2 ~ 1,
     as.integer(datalist[["main"]]$SAF01) == 3 | 
     as.integer(datalist[["main"]]$SAF01) == 4 ~ 0 , 
     as.integer(datalist[["main"]]$SAF01) == 98 | 
     as.integer(datalist[["main"]]$SAF01) == 99 ~ NA_real_) 

datalist[["main"]]$impact3_3  <- labelled::labelled(datalist[["main"]]$impact3_3,
   labels = c('Yes' = 1, 'No' = 0 ),
   label = "Proportion of population that feel safe walking alone in their neighbourhood") 

   }
   return(datalist)
}
```
  
```{r example-impact3_3, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply calculation
datalist <- impact3_3(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$impact3_3,
                     iconunicode = "f140")   
```
  
```{r tests-impact3_3}
test_that("impact3_3 works", {
  expect_true(inherits(impact3_3, "function")) 
})
```


# Outcome indicators

## outcome1_2 
    
```{r function-outcome1_2}
#' outcome1_2 
#' 
#' **Proportion of children under 5 years of age whose births have been registered with a civil authority**
#' 
#' This indicator measures the proportion of children under 5 years old whose births
#'  have been registered with a civil authority and civil documentation has been issued.
#'  This is directly linked to SGD indicator [16.9.1](https://unstats.un.org/sdgs/metadata/files/Metadata-16-09-01.pdf).
#'  
#'  The standard module for this indicator is taken from MICS and adjusted to UNHCR context.
#'  
#'  **Definitions**
#'  
#'  •**Birth registration** refers to the registration of new births by civil 
#'  authorities and completion of the process through the issuance of a birth certificate.
#'  This also includes documents issued by UNHCR or other relevant organizations 
#'  when **given the authority by the State and these documents are recognized by national authorities**.
#'  
#'  **Clarifications**
#'  
#'  •Birth notifications or other hospital records and records from midwives or 
#'  traditional birth attendants, **issued solely by UNHCR or its partners shall
#'   not be considered** as birth certificates although they are important sources 
#'   for establishing the total number of births.
#'   Operations are encouraged to track both the number of birth notifications and
#'    birth registrations but for the purpose of this indicator should report 
#'    the number of births registered.
#'    
#'    • The standard indicator used in DHS, MICS and RMS to report on birth 
#'    registration refers to the percentage of children under age 5 (0-59 months) 
#'    with a birth certificate, regardless of whether or not it was seen by the 
#'    interviewer, or whose birth was reported as registered with civil
#'     authorities at the time of survey.
#'     
#'     | Standard Questions |
#'     |:------------------:|
#'     |   REG03 - REG04    |
#'     
#'     **Numerator**: Number of children under 5 years old who are registered with civil authorities
#'     **Denominator**: Total number of children under 5 years old
#'     **Formula**: (*REG03=1 \| REG04=1) / Number of children under 5*
#'     
#'     This indicator comes from the individual dataset
#'      ind$REG03 - birth certificate
#'      ind$REG04 - birth has been registered
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome1_2 <- function(datalist){
  ## mapper
mapper = list(
  hierarchy = "ind",
  variablemap = data.frame(
    label =
      c("3. Does ${name_individual} have a birth certificate?", "4. Has ${name_individual}'s birth been registered with civil authorities?",
        "6. Can you estimate how old is ${HH02}?")
    ,
    variable =
      c("REG03", "REG04", "HH07")
  ),
  modalitymap = data.frame(
    variable =
      c("REG03", "REG03", "REG03", "REG04", "REG04", "REG04", "REG04",
        "HH07")
    ,
    label =
      c("Yes", "No", "Don't know", "Yes", "No", "Don't know", "Prefer not to say",
        NA)
    ,
    standard =
      c("1", "0", "98", "1", "0", "98", "99", NA)
  ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 1.2")
  } else {
  
  ##Calculate children who has a birth certificate
  datalist[["ind"]]$birthCertificate <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG03) == 0 | 
      as.integer(datalist[["ind"]]$REG03) == 98 ~ 0, 
      as.integer(datalist[["ind"]]$REG03) == 1 ~ 1)

  datalist[["ind"]]$birthCertificate  <- labelled::labelled(datalist[["ind"]]$birthCertificate,
   labels = c('Yes' = 1, 'No' = 0 ),
   label = "Children with a birth certificate")
  
  ##Calculate children who has been registered with civil authorities
  datalist[["ind"]]$birthRegistered <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG04) == 0 | 
      as.integer(datalist[["ind"]]$REG04) == 98 ~ 0, 
      as.integer(datalist[["ind"]]$REG04) == 1 ~ 1, 
      as.integer(datalist[["ind"]]$REG04) == 99 ~ NA_real_)
  
   datalist[["ind"]]$birthRegistered  <- labelled::labelled(datalist[["ind"]]$birthRegistered,
    labels = c('Yes' = 1, 'No' = 0 ),
    label = "Children with birth registered with civil authorities")
  
   ## less than 5
  datalist[["ind"]]$less_than_5 <- dplyr::case_when(
       as.numeric(datalist[["ind"]]$HH07) <  5  ~ 1, 
       TRUE ~ 0)
  datalist[["ind"]]$less_than_5  <- labelled::labelled(datalist[["ind"]]$less_than_5,
    labels = c('Yes' = 1, 'No' = 0 ),
    label = "Is a Children")
  
  ##if the birth is registered or child has a birth certificate
  datalist[["ind"]]$outcome1_2 <- dplyr::case_when(
      (datalist[["ind"]]$birthRegistered == 1 | 
       datalist[["ind"]]$birthCertificate == 1) & 
        as.integer(datalist[["ind"]]$HH07) <  5 ~ 1, 
      
      (datalist[["ind"]]$birthRegistered == 0 & 
       datalist[["ind"]]$birthCertificate == 0) & 
        as.integer(datalist[["ind"]]$HH07) < 5 ~ 0, 
      
      TRUE ~ NA_real_ )

    datalist[["ind"]]$outcome1_2  <- labelled::labelled(datalist[["ind"]]$outcome1_2,
      labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion of children under 5 years of age whose births have been registered with a civil authority")

  }
   return(datalist) 
}
```
  
```{r example-outcome1_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))

## Apply indicator function on datalist
datalist <- outcome1_2(datalist)
table(datalist[["ind"]]$outcome1_2, useNA = "ifany")
table(datalist[["ind"]]$less_than_5, useNA = "ifany")
table(datalist[["ind"]]$HH07, useNA = "ifany")
barplot(as.integer(datalist[["ind"]]$HH07))
table(datalist[["ind"]]$birthCertificate, useNA = "ifany")
table(datalist[["ind"]]$birthRegistered, useNA = "ifany")
## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome1_2,
                     iconunicode = "f140")   
fct_plot_indic_donut(indicator = datalist[["ind"]]$birthCertificate,
                     iconunicode = "f140")   
fct_plot_indic_donut(indicator = datalist[["ind"]]$birthRegistered,
                     iconunicode = "f140")   
```
  
```{r tests-outcome1_2}
test_that("outcome1_2 works", {
  expect_true(inherits(outcome1_2, "function")) 
})
```
  
## outcome1_3
    
```{r function-outcome1_3}
#' outcome1_3
#' 
#' **Proportion of Persons of Concern with legally recognized identity documents or credentials**
#' 
#' This indicator measures the proportion of persons of concern who possess legally 
#' recognized and valid identity documents or credentials.
#' 
#' Establishing one's identity and possessing legally recognized and valid identity
#'  documents or credentials ensures the legal protection of persons of concern,
#'   protection from refoulement, registration of life events to prevent statelessness,
#'    as well as access to services.
#'    
#'    **Definitions**
#'    
#'     Identity document or credential is any document or credential which may be 
#'     used as proof of identity, which may also include reference to the
#'      individuals' legal status and associated rights vis-à-vis the host 
#'      State and/or UNHCR.
#'      
#'  |          Standard Questions           |
#'  |:-------------------------------------:|
#'  | REG01 - REG02 - REG03 / REG05 - REG06 |
#'  
#'  **Numerator**: Total population with valid identity documents or credentials
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: ( *REG01=1 \| REG02=1 \| REG03=1 \| REG05=1 \| REG06=1) / Total population*
#'  
#'  This indicator comes from the individual dataset - 
#'  Calculate valid identity documents for under 5 with REG05 and REG06 variables
#'  ind$REG05a - passport
#'  ind$REG05b - civil/government issued ID
#'  ind$REG05c - residency permit
#'  ind$REG05d - statelessness documentation
#'  ind$REG05e - household card of address/family book
#'  ind$REG05f - social security card
#'  ind$REG06 - any other document establishes identity
#'  add birth certificate as additional document from REG03
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome1_3 <- function(datalist){
  ## Mapper
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("Passport?", "Birth certificate?", "Civil/government-issued ID card ?", 
"Residency permit (both temporary and permanent)?", "Statelessness documentation?", 
"Household card of address / family book/ marriage certificate?", 
"Social security card?", "2. Does ${name_individual} have any other document that establishes his/her legal identity?", 
"3. Does ${name_individual} have a birth certificate?", "Passport?", 
"Civil/government-issued ID card ?", "Residency permit (both temporary and permanent)?", 
"Statelessness documentation?", "Household card of address / family book/ marriage certificate?", 
"Social security card?", "6. Does ${name_individual} have any other document that establishes your legal identity?"
)
              ,
            variable =  
c("REG01a", "REG01b", "REG01c", "REG01d", "REG01e", "REG01f", 
"REG01g", "REG02", "REG03", "REG05a", "REG05b", "REG05c", "REG05d", 
"REG05e", "REG05f", "REG06")
              ),
          modalitymap = data.frame(
            variable =  
c("REG01a", "REG01a", "REG01a", "REG01b", "REG01b", "REG01b", 
"REG01c", "REG01c", "REG01c", "REG01d", "REG01d", "REG01d", "REG01e", 
"REG01e", "REG01e", "REG01f", "REG01f", "REG01f", "REG01g", "REG01g", 
"REG01g", "REG02", "REG02", "REG02", "REG03", "REG03", "REG03", 
"REG05a", "REG05a", "REG05a", "REG05b", "REG05b", "REG05b", "REG05c", 
"REG05c", "REG05c", "REG05d", "REG05d", "REG05d", "REG05e", "REG05e", 
"REG05e", "REG05f", "REG05f", "REG05f", "REG06", "REG06", "REG06"
)
               ,
            label =  
c("Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Don't know", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond"
)
               ,
            standard =  
c("1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "98", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99"
)
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 1.3")
  } else {
  
  
datalist[["ind"]]$document_under5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG05a) == 1 | 
      as.integer(datalist[["ind"]]$REG05b) == 1 | 
      as.integer(datalist[["ind"]]$REG05c) == 1 | 
      as.integer(datalist[["ind"]]$REG05d) == 1 | 
      as.integer(datalist[["ind"]]$REG05e) == 1 | 
      as.integer(datalist[["ind"]]$REG05f) == 1 |
      as.integer(datalist[["ind"]]$REG06) == 1 | 
      as.integer(datalist[["ind"]]$REG03) == 1 ~ 1, 
      
      as.integer(datalist[["ind"]]$REG05a) != 1 &
      as.integer(datalist[["ind"]]$REG05b) != 1 & 
      as.integer(datalist[["ind"]]$REG05c) != 1 & 
      as.integer(datalist[["ind"]]$REG05d) != 1 & 
      as.integer(datalist[["ind"]]$REG05e) != 1 & 
      as.integer(datalist[["ind"]]$REG05f) != 1 & 
      as.integer(datalist[["ind"]]$REG06) != 1 & 
      as.integer(datalist[["ind"]]$REG03) != 1 ~ 0, 
      
      TRUE ~ NA_real_   )

datalist[["ind"]]$document_under5  <- labelled::labelled(datalist[["ind"]]$document_under5,
                            labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Proportion of Persons above 5 with legally
                      recognized identity documents or credentials")
  
  ###Calculate  valid identity documents for above 5 with REG01 and REG02 variables
  #ind$REG01a # passport
  #ind$REG01b # birth certificate
  #ind$REG01c # civil/ government issued ID
  #ind$REG01d # residency permit
  #ind$REG01e # statelessness documentation
  #ind$REG01f # household card of address/family book
  #ind$REG01g # social security card
  #ind$REG02 # any other document establishes identity

#Make sure to delete REG01e below from the script if you don't have any stateless   

datalist[["ind"]]$document_above5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG01a) == 1 | 
      as.integer(datalist[["ind"]]$REG01b) == 1 | 
      as.integer(datalist[["ind"]]$REG01c) == 1 | 
      as.integer(datalist[["ind"]]$REG01d) == 1 | 
      as.integer(datalist[["ind"]]$REG01e) == 1 | 
      as.integer(datalist[["ind"]]$REG01f) == 1 | 
      as.integer(datalist[["ind"]]$REG01g) == 1 |
      as.integer(datalist[["ind"]]$REG02) == 1 ~ 1,
      
      as.integer(datalist[["ind"]]$REG01a) != 1 & 
      as.integer(datalist[["ind"]]$REG01b) != 1 & 
      as.integer(datalist[["ind"]]$REG01c) != 1 & 
      as.integer(datalist[["ind"]]$REG01d) != 1 & 
      as.integer(datalist[["ind"]]$REG01e) != 1 & 
      as.integer(datalist[["ind"]]$REG01f) != 1 & 
      as.integer(datalist[["ind"]]$REG01g) != 1 & 
      as.integer(datalist[["ind"]]$REG02) != 1 ~ 0, 
      
      TRUE ~ NA_real_)

datalist[["ind"]]$document_above5  <- labelled::labelled(datalist[["ind"]]$document_above5,
                            labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Proportion of Persons above 5 with legally
                      recognized identity documents or credentials")
      
  ##Combine both age groups
datalist[["ind"]]$outcome1_3<- dplyr::case_when(
     (datalist[["ind"]]$document_above5 == 1 | 
      datalist[["ind"]]$document_under5 == 1 ) ~ 1,
     
     (datalist[["ind"]]$document_above5 == 0 | 
      datalist[["ind"]]$document_under5 == 0 ) ~ 0)

datalist[["ind"]]$outcome1_3  <- labelled::labelled(datalist[["ind"]]$outcome1_3,
                            labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Proportion of Persons with legally
                      recognized identity documents or credentials")
  
  }
   return(datalist)
}
```
  
```{r example-outcome1_3, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome1_3(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome1_3,
                     iconunicode = "f140")    

fct_plot_indic_donut(indicator = datalist[["ind"]]$document_above5,
                     iconunicode = "f140")    

fct_plot_indic_donut(indicator = datalist[["ind"]]$document_under5,
                     iconunicode = "f140")    
```
  
```{r tests-outcome1_3}
test_that("outcome1_3 works", {
  expect_true(inherits(outcome1_3, "function")) 
})
```
   
   
## outcome4_1
    
```{r function-outcome4_1}
#' outcome4_1
#' 
#' 
#' **Proportion of Persons of Concern who know where to access available GBV services**
#' 
#' The indicator is defined as the proportion of persons of concern who know where to access at least one of the four available gender-based violence services in the aftermath of a GBV incident.
#' 
#' This is linked to the Inter-Agency Minimum Standards for Gender-Based Violence in Emergencies Programming.
#' 
#' The response options will appear as below when the standardized module is used.
#' 
#' *Definitions:*
#' 
#' 1.  **GBV01a (**Health): "Medical treatment and health care to address the immediate and long-term physical and mental health effects of GBV. This can include initial examination and treatment, follow-up medical care, mental health care, and health-related legal services, such as preparation of documentation and provision of evidence during judicial and related processes."
#' 
#' 2.  **GBV01b** (Psycho-social/ case management): "Psychosocial care and support to assist with healing and recovery from emotional, psychological and social effects. This includes crisis care as well as longer-term emotional and practical support for the survivor and her/his family, information and advocacy, case management, and educating family members so that they can support the survivor's healing and recovery.
#' 
#' 3.  **GBV01c** (Safety/security): "Options for safety and protection for survivors and their families who are at risk of further violence and who wish to be protected. This can include safe shelters, police or community security, relocation, or in the case of children, alternative care arrangements".
#' 
#' 4.  **GBV01d** (Legal assistance): "Legal actors will clearly and honestly inform the victim/survivor of the #' procedures, limitations, pros, and cons of all existing legal options".
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       GBV01        |
#' 
#' **Numerator**: Total population who indicates knowing where to access available GBV services
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: ( *GBV01a=1 \| GBV01b=1 \| GBV01c=1 \| GBV01d=1) / Total population*
#' 
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome4_1 <- function(datalist){
  
  # mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("Health services", "Psycho-social services", "Safety and security services? (police, safe shelters)", 
"Legal assistance")
              ,
            variable =  
c("GBV01a", "GBV01b", "GBV01c", "GBV01d")
              ),
          modalitymap = data.frame(
            variable =  
c("GBV01a", "GBV01a", "GBV01a", "GBV01b", "GBV01b", "GBV01b", 
"GBV01c", "GBV01c", "GBV01c", "GBV01d", "GBV01d", "GBV01d")
               ,
            label =  
c("Yes", "No", "Don't know", "Yes", "No", "Don't know", "Yes", 
"No", "Don't know", "Yes", "No", "Don't know")
               ,
            standard =  
c("1", "0", "98", "1", "0", "98", "1", "0", "98", "1", "0", "98"
)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 4.1")
  } else {
  
datalist[["main"]]$outcome4_1 <- dplyr::case_when(
      as.integer(datalist[["main"]]$GBV01a) == 1 |  
      as.integer(datalist[["main"]]$GBV01b) == 1 |  
      as.integer(datalist[["main"]]$GBV01c) == 1 |  
      as.integer(datalist[["main"]]$GBV01d) == 1 ~ 1,
      TRUE ~ 0)
    
datalist[["main"]]$outcome4_1  <- labelled::labelled(datalist[["main"]]$outcome4_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
                               label = "Proportion of PoC who know where to 
                            access available GBV services")
  }
   return(datalist)
}
```
  
```{r example-outcome4_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome4_1(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome1_4,
                     iconunicode = "f140")   
```
  
```{r tests-outcome4_1}
test_that("outcome4_1 works", {
  expect_true(inherits(outcome4_1, "function")) 
})
```
     

## outcome4_2
    
```{r function-outcome4_2}
#' outcome4_1
#' 
#' 
#' **Proportion of Persons of Concern who do not accept violence against women**
#' 
#' This indicator measures the proportion of persons of concern who disagree that a husband is justified in hitting or beating his wife for a list of specific reasons.
#' This serves as a proxy indicator for those who do not accept violence against women.
#' 
#' This module is taken from [Domestic Violence Module](https://dhsprogram.com/pubs/pdf/DHSQMP/DHS6_Module_Domestic_Violence_6Aug2014_DHSQMP.pdf) from DHS and similar module used by MICS.
#' Due to its sensitivity, this module is only recommended for face-to-face surveys.
#' 
#' *Data Collection Safeguards*
#' 
#' Enumerators (and data collection teams) must be trained on GBV safe disclosures and referrals prior to undertaking household surveys (or at least get a briefing on the GBV referral pathway in their area).
#' To ensure quality feedback and limit risks of harm, it is advisable to administer the survey to members of the household separately in confidential spaces (consider using interview rooms at community centres in settings where layout of communities' homes do not allow for confidential discussions).
#' 
#' It is also recommended to ensure same-sex enumerators to minimize risks of SEA particularly for female respondents.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       VAW01        |
#' 
#' **Numerator**: Population 18 and above who disagree that a husband is justified in hitting or beating his wife for all the following reasons:
#' 
#' 1.  Going out without telling him.
#' 
#' 2.  Neglecting the children.
#' 
#' 3.  Arguing with him.
#' 
#' 4.  Refusing to have sexual intercourse with him.
#' 
#' 5.  Burning food.
#' 
#' **Denominator**: Total population 18 and above
#' 
#' **Formula**: ( *GBV01a=1 \| GBV01b=1 \| GBV01c=1 \| GBV01d=1) / Total population*
#' 
#' 
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' 
#' If randomly selected adult who believes that a  husband is justified in beating his wife in various circumstances
#' 
#' If yes selected for any of the circumstances
#' Prefer not to respond will be put into missing
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome4_2 <- function(datalist ){
  # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("If she goes out without telling him?", "If she neglects the children?", 
"If she argues with him?", "If she refuses to have sex with him?", 
"If she burns the food?")
              ,
            variable =  
c("VAW01a", "VAW01b", "VAW01c", "VAW01d", "VAW01e")
              ),
          modalitymap = data.frame(
            variable =  
c("VAW01a", "VAW01a", "VAW01a", "VAW01b", "VAW01b", "VAW01b", 
"VAW01c", "VAW01c", "VAW01c", "VAW01d", "VAW01d", "VAW01d", "VAW01e", 
"VAW01e", "VAW01e")
               ,
            label =  
c("Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond")
               ,
            standard =  
c("1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 4.2")
  } else {

datalist[["main"]]$outcome4_2<- dplyr::case_when(
     as.integer(datalist[["main"]]$VAW01a) == 1 | 
     as.integer(datalist[["main"]]$VAW01b) == 1 |  
     as.integer(datalist[["main"]]$VAW01c) == 1 |  
     as.integer(datalist[["main"]]$VAW01d) == 1 | 
     as.integer(datalist[["main"]]$VAW01e) == 1 ~ 0,
     
     as.integer(datalist[["main"]]$VAW01a) == 0 & 
     as.integer(datalist[["main"]]$VAW01b) == 0 &  
     as.integer(datalist[["main"]]$VAW01c) == 0 &  
     as.integer(datalist[["main"]]$VAW01d) == 0 & 
     as.integer(datalist[["main"]]$VAW01e) == 0 ~ 1,
     
     TRUE ~ NA_real_)

datalist[["main"]]$outcome4_2  <- labelled::labelled(datalist[["main"]]$outcome4_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                          label = "Proportion of PoC who do not accept 
                          violence against women" )  
  }
   return(datalist) 
}
```
  
```{r example-outcome4_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome4_2(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome4_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome4_2}
test_that("outcome4_2 works", {
  expect_true(inherits(outcome4_2, "function")) 
})
```

## outcome5_2
    
```{r function-outcome5_2}
#' outcome5_2
#' 
#' **Proportion of children who participate in community-based child protection programmes**
#' 
#' The indicator is defined as the the proportion of children who participate in community-based child protection programmes.
#' The module for this question comes from UNHCR Core indicator metadata.
#' 
#' Children' participation in community-based recreational and child protection activities is a key mechanism for the protection of children by providing children with a protected environment in which they can participate in organized activities to play, socialize, learn, and express themselves, promoting their psycho-social well-being and reducing the risk of abuse, violence or exploitation.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |   COMM01-COMM04    |
#' 
#' **Numerator**: Total number of children between 4-17 years who participate in community-based recreational and child protection programmes
#' 
#' **Denominator**: Total [number of children between 4-17 years
#' 
#' **Formula**: ( *COMM01=1 & COMM02 \>=2 \| & COMM03=1 & COMM04=1) / Total number of children 4-17 years*
#' This indicator comes from the individual level dataset
#' 
#'  
#' Children who participate in community-based programmes at least 2 times, under adult supervision in a physically safe area
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome5_2 <- function(datalist){
  ## Mapper , 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. Has ${child_edu_name} participated in sports, arts, cultural activities or other after-school programmes for children outside the home in the last month?", 
"2. In the past month, how many times did ${child_edu_name} participate in these activities?", 
"3. Were they in a physically safe area while participating in the activity?", 
"4. Were there adults supervising the activities?")
              ,
            variable =  
c("COMM01", "COMM02", "COMM03", "COMM04")
              ),
          modalitymap = data.frame(
            variable =  
c("COMM01", "COMM01", "COMM02", "COMM03", "COMM03", "COMM03", 
"COMM04", "COMM04", "COMM04")
               ,
            label =  
c("Yes", "No", NA, "Yes", "No", "Don't know", "Yes", "No", "Don't know"
)
               ,
            standard =  
c("1", "0", NA, "1", "0", "98", "1", "0", "98")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 5.2")
  } else {
  
datalist[["ind"]]$outcome5_2<- dplyr::case_when(
     ( as.integer(datalist[["ind"]]$COMM01) == 1 & 
       as.integer(datalist[["ind"]]$COMM02) >= 2 & 
       as.integer(datalist[["ind"]]$COMM03) == 1 & 
       as.integer(datalist[["ind"]]$COMM04) == 1) ~ 1,
     
     ( as.integer(datalist[["ind"]]$COMM01) == 0 | 
     ( as.integer(datalist[["ind"]]$COMM02) < 2 | 
       as.integer(datalist[["ind"]]$COMM02) == 98 ) | 
      ( as.integer(datalist[["ind"]]$COMM03) == 0 | 
        as.integer(datalist[["ind"]]$COMM03) == 98) |
       ( as.integer(datalist[["ind"]]$COMM04) == 0 | 
         as.integer(datalist[["ind"]]$COMM04) == 98)) ~ 0, 
     
     TRUE ~ NA_real_)

datalist[["ind"]]$outcome5_2  <- labelled::labelled(datalist[["ind"]]$outcome5_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                              label = "Proportion of children who participate 
                            in community-based child protection programmes")
  }
   return(datalist)
}
```
  
```{r example-outcome5_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome5_2(datalist  )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome5_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome5_2}
test_that("outcome5_2 works", {
  expect_true(inherits(outcome5_2, "function")) 
})
```
  

 
## outcome8_2
    
```{r function-outcome8_2}
#' outcome8_2
#' 
#' 
#' **Proportion of Persons of Concern with primary reliance on clean (cooking) fuels and technology**
#' 
#' This indicator measures the proportion of population who use clean fuel and technology as primary source of cooking.
#' Any type of cooking fuel and technology meeting the WHO set standards on indoor air emissions, as their main cooking solution.
#' This is also linked to SGD indicator [7.1.2](https://sdg-tracker.org/energy) .
#' 
#' The standard questions are similar to MICS and the calculation of indicators are based on [UNICEF MICS](https://mics.unicef.org/files?job=W1siZiIsIjIwMTcvMDIvMDMvMTYvMjcvMjUvNTk5L1BpY3RvcmlhbHNfV0hPX0hvdXNlaG9sZF9FbmVyZ3lfVXNlX0NhdGFsb2d1ZV9TZXB0ZW1iZXJfMjAxNl8ucGRmIl1d&sha=57b4a452fcc0ac88) and [WHO](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/5662) guidance on the calculation of the same SGD indicator.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |   COOK01- COOK03   |
#' 
#' **Numerator**: Percentage of population with primary reliance on clean fuels and technologies for cooking
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: COOK01=1 (there is a cooking device) & (COOK02=1,2,3,4,5) \| (COOK02=6 & COOK03=1,2) / Total Population
#' 
#' This indicator comes from household level dataset
#' Based on MICS calculation : TC4.1
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome8_2 <- function(datalist){
mapper = list(
           hierarchy = "ind",
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. Is any food or drink consumed by household members cooked or prepared at the household dwelling using a cookstove, fire or other cooking device?", 
"2. What does this household use for cooking most of the time, including cooking food, making tea/coffee, boiling drinking water?", 
"3. What type of fuel or energy source does this household use most of the time in this cookstove or device for cooking food, making tea/coffee and boiling drinking water?"
)
              ,
            variable =  
c("COOK01", "COOK02", "COOK03")
              ),
          modalitymap = data.frame(
            variable =  
c("COOK01", "COOK01", "COOK02", "COOK02", "COOK02", "COOK02", 
"COOK02", "COOK02", "COOK02", "COOK02", "COOK02", "COOK02", "COOK02", 
"COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", 
"COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", 
"COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", 
"COOK03")
               ,
            label =  
c("Yes", "No", "Solar cooker (thermal energy from the sun, not solar panels)", 
"Electric stove", "Piped natural gas stove", "Biogas stove", 
"Liquefied petroleum gas (LPG)/ cooking gas stove", "Liquid fuel stove", 
"Manufactured solid fuel stove", "Traditional solid fuel stove (non-manufactured)", 
"Moveable firepan", "Three stone stove/open fire", "Other, specify", 
"Alcohol/ethanol", "Liquefied petroleum gas", "Biogas", "Electricity from the national grid", 
"Electricity from solar mini-grid", "Electricity from diesel generator", 
"Electricity from hybrid mini-grid (i.e., solar+ diesel, solar+ national grid, etc..)", 
"Gasoline/diesel (not in generator)", "Kerosene/paraffin", "Coal/lignite unprocessed", 
"Coal/lignite briquettes/pellets", "Charcoal unprocessed", "Charcoal briquettes/pellets", 
"Wood (collected)", "Wood (distributed/purchased)", "Agricultural or crop residue/grass/ straw/ shrubs/ corn cobs", 
"Animal waste/dung", "Processed biomass pellets/briquettes", 
"Woodchips", "Garbage/plastic", "Sawdust", "Other, specify")
               ,
            standard =  
c("1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"96", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", 
"12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "96"
)
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 8.2")
  } else {
     
datalist[["main"]]$outcome8_2 <- dplyr::case_when(
       ( as.integer(datalist[["main"]]$COOK01) == 1 & 
           (datalist[["main"]]$COOK02 %in% c("1", "2", "3", "4", "5")) |
           (datalist[["main"]]$COOK02 %in% c("6") & 
            datalist[["main"]]$COOK03 %in% c("1", "3")) ) ~  1,
       
       ( as.integer(datalist[["main"]]$COOK01) == 1 & 
          (datalist[["main"]]$COOK02 %in% c("7", "8", "9", "10", "96")) |
          ((datalist[["main"]]$COOK02 %in% c("6") &
              !(datalist[["main"]]$COOK03 %in% c("1", "3") )))) ~  0 ,
       TRUE ~ NA_real_ )

datalist[["main"]]$outcome8_2  <- labelled::labelled(datalist[["main"]]$outcome8_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                    label = "Proportion of Persons of Concern with
                    primary reliance on clean (cooking) fuels and technology")
  }

   return(datalist)
}
```
  
```{r example-outcome8_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome8_2(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome8_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome8_2}
test_that("outcome8_2 works", {
  expect_true(inherits(outcome8_2, "function")) 
})
```
  

## outcome9_1
    
```{r function-outcome9_1}
#' outcome9_1
#' 
#' **Proportion of Persons of Concern living in habitable and affordable housing**
#' 
#' This indicator measures the proportion of persons of concern living in habitable and affordable housing.
#' This indicator focuses only on habitability and affordability.
#' It is limited in its reflection on other key aspects of adequate housing including security of tenure, availability of other basic services and infrastructure, accessibility, location of housing, and cultural appropriateness.
#' It is also linked to SGD indicator [11.1.1](https://unstats.un.org/sdgs/metadata/files/Metadata-11-01-01.pdf).
#' 
#' The right to access adequate housing is protected by international law.
#' The concept of "adequacy" means that housing is more than four walls and a roof as indicated in [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf).
#' Habitable housing primarily refers to the fact that the housing should provide protection from cold, damp, heat, rain, wind, and other threats to health, structural hazards, and disease vectors and it should not be overcrowded.
#' As shelter/housing is primarily a contextual element, there may be discrepancies from country to country on how this data is measured.Habitable shelter is measured based on having improved material for the dwelling as indicated in [DHS](https://dhsprogram.com/pubs/pdf/AS61/AS61.pdf) publication on housing conditions which is also used by [MICS6](https://mics.unicef.org/tools).
#' Overcrowding is also used which occurs if there are more than three people per habitable room as defined by [UN-Habitat](https://www.ncbi.nlm.nih.gov/books/NBK535289/table/ch3.tab2/).
#' 
#' Affordable housing refers to the fact that the cost of housing and its related expenditures on maintenance and household items should be at such a level that it should not compromise the attainment and satisfaction of other basic needs
#' 
#' |    Standard Questions     |
#' |:-------------------------:|
#' | DWE01-DWE05 & DWE08-DWE09 |
#' 
#' **Numerator**: Total population living in habitable and affordable housing
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *DWE01* = 1,2 & *DWE02* = 3,4,5,6,7,8,9 & *DWE03* = 8,9,10,11,12,13 & *DWE04* = 10,11,12,13,14,15 & crowding (*HH01*/*DWE05*) \<= 3 & (DWE08=1 & DWE09=1,2) \| DWE08=0
#'  
#' 
#' This indicator is calculated from the main dataset
#' 
#' classify as habitable when improved/adequate shelter
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome9_1 <- function(datalist){
  # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1.What type of dwelling does the household live in?", "2. Main material of the dwelling floor", 
"3. Main material of the roof.", "4. Main material of the exterior walls", 
"5. How many separate rooms do the members of your household occupy?", 
"8. Does your household pay any rent?", "9. Can your household generally afford to pay the rent without any major financial distress?", 
"What is the total number of persons in this household ? (including the respondent)"
)
              ,
            variable =  
c("DWE01", "DWE02", "DWE03", "DWE04", "DWE05", "DWE08", "DWE09", 
"HH01")
              ),
          modalitymap = data.frame(
            variable =  
c("DWE01", "DWE01", "DWE01", "DWE01", "DWE01", "DWE01", "DWE01", 
"DWE01", "DWE01", "DWE01", "DWE02", "DWE02", "DWE02", "DWE02", 
"DWE02", "DWE02", "DWE02", "DWE02", "DWE02", "DWE02", "DWE03", 
"DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", 
"DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE04", 
"DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", 
"DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", 
"DWE04", "DWE05", "DWE08", "DWE08", "DWE09", "DWE09", "DWE09", 
"DWE09", "HH01")
               ,
            label =  
c("Apartment", "House", "Tent", "Caravan", "Collective Center", 
"Worksite/Unfinished Home/ Abandoned Building", "Farm Building", 
"School, mosque, church or other religious building", "Garage, shop, workshop, or other structure not meant as residential space", 
"Other (Specify)", "Earth/sand", "Dung", "Wood planks", "Palm/bamboo", 
"Parquet or polished wood", "Vinyl or asphalt strips", "Ceramic tiles", 
"Cement", "Carpet", "Other (Specify)", "No roof", "Thatch/Palm leaf", 
"Sod", "Rustic mat", "Palm/bamboo", "Wood planks", "Cardboard", 
"Metal/tin", "Wood", "Calamine/Cement fibre", "Ceramic tiles", 
"Cement", "Roofing shingles", "Other (Specify)", "No walls", 
"Cane/Palm/ Trunks", "Dirt", "Bamboo with mud", "Stone with mud", 
"Uncovered adobe", "Plywood", "Cardboard", "Reused wood", "Cement", 
"Stone with lime/ cement", "Bricks", "Cement blocks", "Covered adobe", 
"Wood planks/shingles", "Other (Specify)", NA, "Yes", "No", "Always", 
"Often", "Sometimes", "Never", NA)
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "96", "1", "2", 
"3", "4", "5", "6", "7", "8", "9", "96", "1", "2", "3", "4", 
"5", "6", "7", "8", "9", "10", "11", "12", "13", "96", "1", "2", 
"3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", 
"15", "96", NA, "1", "0", "1", "2", "3", "4", NA)
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 9.1")
  } else {
  
 #Only apartment and house
datalist[["main"]]$dwe01_cat<- dplyr::case_when(
         (as.integer(datalist[["main"]]$DWE01) == 1 | 
          as.integer(datalist[["main"]]$DWE01) == 2) ~ 1, 
         TRUE ~ 0 )

datalist[["main"]]$dwe01_cat <- labelled::labelled(datalist[["main"]]$dwe01_cat,
                        labels = c('Yes' = 1, 'No' = 0 ),
           label = "Proportion of apartment and house")

#unimproved floor when not earth,sand,clay,mud, dung or other
datalist[["main"]]$dwe02_cat<- dplyr::case_when( 
    (as.integer(datalist[["main"]]$DWE02) == 1 | 
     as.integer(datalist[["main"]]$DWE02) == 2 | 
     as.integer(datalist[["main"]]$DWE02) == 96) ~ 0, 
    TRUE ~ 1 )
datalist[["main"]]$dwe02_cat <- labelled::labelled(datalist[["main"]]$dwe02_cat,
                        labels = c('Yes' = 1, 'No' = 0 ),
           label = "Proportion of improved floor, ie. no earth,sand,clay,mud, 
           dung or other")

#unimproved roof all options except metal,wood,ceramic tiles, cement, roofing shingles/sheets
datalist[["main"]]$dwe03_cat<- dplyr::case_when( 
    (as.integer(datalist[["main"]]$DWE03) == 8 |
     as.integer(datalist[["main"]]$DWE03) == 9 | 
     as.integer(datalist[["main"]]$DWE03) == 10 | 
     as.integer(datalist[["main"]]$DWE03) == 11 |
     as.integer(datalist[["main"]]$DWE03) == 12 | 
     as.integer(datalist[["main"]]$DWE03) == 13 ) ~ 1 , 
    TRUE ~ 0)
datalist[["main"]]$dwe03_cat <- labelled::labelled(datalist[["main"]]$dwe03_cat,
                        labels = c('Yes' = 1, 'No' = 0 ),
           label = "Proportion of improved roof all options except metal,
           wood,ceramic tiles, cement, roofing shingles/sheets")

#improved wall: cement,stone,bricks,cement blocks, covered adobe, wood planks
datalist[["main"]]$dwe04_cat<- dplyr::case_when( 
    ( as.integer(datalist[["main"]]$DWE04) == 10 | 
      as.integer(datalist[["main"]]$DWE04) == 11 | 
      as.integer(datalist[["main"]]$DWE04) == 12 | 
      as.integer(datalist[["main"]]$DWE04) == 13 | 
      as.integer(datalist[["main"]]$DWE04) == 14 | 
      as.integer(datalist[["main"]]$DWE04) == 15) ~ 1,
  TRUE ~ 0) 
datalist[["main"]]$dwe04_cat <- labelled::labelled(datalist[["main"]]$dwe04_cat,
                        labels = c('Yes' = 1, 'No' = 0 ),
           label = "Proportion of improved wall: cement,stone,bricks, 
           cement blocks, covered adobe, wood planks")

####Calculate crowding index - overcrowded when more than 3 persons

datalist[["main"]]$crowding <- as.integer(datalist[["main"]]$HH01) /
                               as.integer(datalist[["main"]]$DWE05)
##if crowding <= 3, not overcrowded 
datalist[["main"]]$dwe05_cat <- dplyr::case_when( 
    datalist[["main"]]$crowding <= 3 ~ 1, 
    TRUE ~ 0)
datalist[["main"]]$dwe05_cat <- labelled::labelled(datalist[["main"]]$dwe05_cat,
                        labels = c('Yes' = 1, 'No' = 0 ),
           label = "Proportion of overcrowded sheters") 


## Add DWE08 and DWE09 to calculations - 
# if household is paying rent, they should be able to afford to pay rent without any financial distress

#affordable if HH pays rent and often and always without financial distress
datalist[["main"]]$dwe09_cat <-  dplyr::case_when( 
  (as.integer(datalist[["main"]]$DWE08) == 1 &
     (as.integer(datalist[["main"]]$DWE09) == 1 | 
      as.integer(datalist[["main"]]$DWE09) == 2 ) ) ~ 1,
  
  (as.integer(datalist[["main"]]$DWE08) == 1 &
     (as.integer(datalist[["main"]]$DWE09) == 3 | 
      as.integer(datalist[["main"]]$DWE09) == 4 ) ) ~ 0,  
  
  datalist[["main"]]$DWE08== 0 ~ 1)

datalist[["main"]]$dwe09_cat <- labelled::labelled(datalist[["main"]]$dwe09_cat,
                        labels = c('Yes' = 1, 'No' = 0 ),
   label = "Proportion of affordable sheters - HH pays rent and often and always without financial distress")
      
####Combine all shelter indicators 

##dwe01_cat / dwe02_cat / dwe03_cat / dwe04_cat / dwe05_cat / dwe09_cat


datalist[["main"]]$outcome9_1 <- dplyr::case_when(
    datalist[["main"]]$dwe01_cat == 0 | 
    datalist[["main"]]$dwe02_cat == 0 | 
    datalist[["main"]]$dwe03_cat == 0 | 
    datalist[["main"]]$dwe04_cat == 0 | 
    datalist[["main"]]$dwe05_cat == 0 | 
    datalist[["main"]]$dwe09_cat == 0  ~ 0,
    
    datalist[["main"]]$dwe01_cat == 1 & 
    datalist[["main"]]$dwe02_cat == 1 & 
    datalist[["main"]]$dwe03_cat == 1 & 
    datalist[["main"]]$dwe04_cat == 1 & 
    datalist[["main"]]$dwe05_cat == 1 & 
    datalist[["main"]]$dwe09_cat == 1 ~ 1)

datalist[["main"]]$outcome9_1  <- labelled::labelled(datalist[["main"]]$outcome9_1,
                        labels = c('Yes' = 1, 'No' = 0 ),
   label = "Proportion of PoCs living in habitable and affordable housing")

  }
   return(datalist) 
}
```
  
```{r example-outcome9_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome9_1(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome9_1,
                     iconunicode = "f140")   
```
  
```{r tests-outcome9_1}
test_that("outcome9_1 works", {
  expect_true(inherits(outcome9_1, "function")) 
})
```

## outcome9_2
    
```{r function-outcome9_2}
#' outcome9_2
#' 
#' 
#' **Proportion of Persons of Concern that have energy to ensure lighting**
#' 
#' This indicator measures the percentage of Persons of Concern who have access to clean and sustainable source of lighting at household level.
#' Safe and sustainable access to clean energy is increasingly recognized as human right and is an integral part of the Sustainable Development Goals.
#' 
#' The indicator for lighting is constructed from the essential questions *LIGHT01* and *LIGHT02* which captures the most used light source.
#' [LSMS Guidebook](https://documents1.worldbank.org/curated/en/557341633679857128/pdf/Measuring-Energy-Access-A-Guide-to-Collecting-Data-Using-the-Core-Questions-on-Household-Energy-Use.pdf) is the main source for measuring energy access as defined for SGD 7.1.12.
#' 
#' | Standard Questions |
#' |:------------------:|
#' | LIGHT01 - LIGHT03  |
#' 
#' : $\frac{Population with reliance on clean fuels and technologies for lighting}{Total population}$
#' 
#' **Numerator**: Population living in households with primary reliance on clean fuels and technologies for lighting
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *LIGHT01* = 1 & *LIGHT02* = 1, 3, 4, 5, 6, 7, 8 / Total Population
#' 
#' This comes from the main dataset
#' 
#'  The below Calculates percentage of PoC having access to clean fuel for lighting and / or basic connectivity (9.1 Outcome Indicator)
#'  
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome9_2 <- function(datalist ){
   # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("4. Does this household use anything for lighting?", "5. What does this household use most of the time as energy for lighting, or as a light source?", 
"6. What source of electricity is used most of the time in this household?"
)
              ,
            variable =  
c("LIGHT01", "LIGHT02", "LIGHT03")
              ),
          modalitymap = data.frame(
            variable =  
c("LIGHT01", "LIGHT01", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT03", "LIGHT03", 
"LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", 
"LIGHT03", "LIGHT03")
               ,
            label =  
c("Yes", "No", "Electricity (including solar mini-grids, hybrid mini-grids and national grid)", 
"Electricity (from diesel generator)", "Solar home system", "Solar-powered lantern or flashlight", 
"Rechargeable flashlight, mobile, torch or lantern", "Battery powered flashlight, torch or lantern", 
"Biogas lamp", "LPG lamp", "Gasoline lamp", "Kerosene or paraffin lamp", 
"Oil lamp", "Candle", "Open fire", "Other, specify", "No electricity in household", 
"National grid connection from [COMPANY]", "Local mini grid", 
"Solar home system", "Solar lantern", "Electric generator", "Rechargeable battery", 
"Dry cell battery / torch", "Other, specify", "Don't know")
               ,
            standard =  
c("1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "96", "1", "2", "3", "4", "5", "6", "7", "8", 
"96", "98")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 9.2")
  } else {
    
datalist[["main"]]$outcome9_2 <- dplyr::case_when(
  as.integer(datalist[["main"]]$LIGHT01) == 1 & 
     (as.integer(datalist[["main"]]$LIGHT02) == 1 |
      as.integer(datalist[["main"]]$LIGHT02) == 3 | 
      as.integer(datalist[["main"]]$LIGHT02) == 4 | 
      as.integer(datalist[["main"]]$LIGHT02) == 5 |
      as.integer(datalist[["main"]]$LIGHT02) == 6 |
      as.integer(datalist[["main"]]$LIGHT02) == 7 |
      as.integer(datalist[["main"]]$LIGHT02) == 8 )  ~ 1, 
     TRUE ~ 0)

datalist[["main"]]$outcome9_2  <- labelled::labelled(datalist[["main"]]$outcome9_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
  label = "Proportion of PoC that have energy to ensure lighting")

}
   return(datalist)
}
```
  
```{r example-outcome9_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome9_2(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome9_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome9_2}
test_that("outcome9_2 works", {
  expect_true(inherits(outcome9_2, "function")) 
})
```

## outcome10_1
    
```{r function-outcome10_1}
#' outcome10_1
#' 
#' 
#' **Proportion of children aged 9 months to five years who have received measles vaccination**
#' 
#' Coverage of measles vaccination in children in the target age group of 9 months to 5 years of age.
#' Measles vaccination is an essential preventive primary care intervention to protect children from measles infection.
#' 
#' Standard module is from [UNICEF MICS6](https://mics.unicef.org/tools#survey-design) Children under 5 module.
#' The calculation of this module is also aligned with UNICEF MICS6.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    MMR01-MMR04     |
#' 
#' **Numerator**: Total number of children 9 months to 5 years who have received a measles containing vaccine (measles or MMR- Measles Mumps and Rubella)
#' 
#' **Denominator**: Total number of children 9 months to 5 years
#' 
#' **Formula**: *MMR03=*1 / Total number of children 9 months to 5 years
#' 
#' This comes from the main dataset
#' 
#' MICS TC.1.1 UNICEF calculates on the first dose received##
#' Children who had et least one dose of measles vaccination
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome10_1 <- function(datalist){
  # Mapper , 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
"3. Has ${indiv_05Less_name} ever received a measles containing vaccine(i.e. measles, MR or MMR)? That is a shot at the age of 9 months or older - to prevent (him/her) from getting measles"
              ,
            variable =  
"MMR03"
              ),
          modalitymap = data.frame(
            variable =  
c("MMR03", "MMR03", "MMR03")
               ,
            label =  
c("Yes", "No", "Don't know")
               ,
            standard =  
c("1", "0", "98")
              ))
  
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 10.1")
  } else {
  
  
datalist[["ind"]]$outcome10_1 <- dplyr::case_when(
    as.integer(datalist[["ind"]]$MMR03) == 1 ~ 1, 
    
    as.integer(datalist[["ind"]]$MMR03) == 0  |
    as.integer(datalist[["ind"]]$MMR03) == 98 ~ 0)

datalist[["ind"]]$outcome10_1  <- labelled::labelled(datalist[["ind"]]$outcome10_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
     label = "Proportion of children aged 9 months to five years who have received measles vaccination")
}
   return(datalist)
}
```
  
```{r example-outcome10_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))

## Apply indicator function on datalist
datalist <- outcome10_1(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome10_1,
                     iconunicode = "f140")   
```
  
```{r tests-outcome10_1}
test_that("outcome10_1 works", {
  expect_true(inherits(outcome10_1, "function")) 
})
```
  
 

## outcome10_2
    
```{r function-outcome10_2}
#' outcome10_2
#' 
#' **Proportion of births attended by skilled health personnel**
#' 
#' This indicator measures the percentage of births attended by personnel trained to give the necessary supervision, care, and advice to women during pregnancy, labor, and the postpartum period; to conduct deliveries on their own; and to care for newborns.
#' This indicator is linked to SGD [3.1.2](https://unstats.un.org/sdgs/metadata/files/Metadata-03-01-02.pdf).
#' 
#' National-level household surveys are the main data sources used to collect data for skilled health personnel providing childbirth care.
#' These surveys include Demographic and Health Surveys (DHS), Multiple Indicator Cluster Surveys (MICS), Reproductive Health Surveys (RHS) and other national surveys based on similar methodologies.
#' Standard module is from [UNICEF MICS6](https://mics.unicef.org/tools#survey-design) individual questionnaire for woman.
#' The calculation of this module is also aligned with UNICEF MICS6.
#' 
#' The national categories of skilled health personnel are verified, and the estimates for some countries may include additional categories of trained personnel beyond doctor, nurse, and midwife.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    BIR01-BIR04     |
#' 
#' **Numerator**: Total number of births attended by skilled health personnel)
#' 
#' **Denominator**: Total number of live births
#' 
#' **Formula**: (BIR01=1 | BIR02=1) & (BIR03=1,2,3) / Total number of live births
#' This comes from the main dataset
#' MICS TM.5.a UNICEF MICS calculation if there was a trained health personnel ##
#' If there are live births in the last 2 years 
#'  Traditional birth attendant and community health worker can be included if they are trained
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome10_2 <- function(datalist){
  ## Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. In addition to ${namechild2less} was there any live birth in this household in the past 2 years?", 
"2. Was there any live birth in this household in the past 2 years?", 
"3. Who assisted with the delivery of  the latest child born alive ?", 
"4. Where did the birth take place for the latest child born alive ?"
)
              ,
            variable =  
c("BIR01", "BIR02", "BIR03", "BIR04")
              ),
          modalitymap = data.frame(
            variable =  
c("BIR01", "BIR01", "BIR02", "BIR02", "BIR03", "BIR03", "BIR03", 
"BIR03", "BIR03", "BIR03", "BIR03", "BIR03", "BIR04", "BIR04", 
"BIR04", "BIR04")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Health professional", "Doctor", 
"Nurse/midwife", "Traditional birth attendant", "Community health worker", 
"Relative/friend", "Other (specify)", "Don't know", "Respondent’s home", 
"Public sector", "Private sector", "Other, specify")
               ,
            standard =  
c("1", "0", "1", "0", "1", "2", "3", "4", "5", "6", "96", "98", 
"1", "2", "3", "96")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 10.2")
  } else {
    
datalist[["main"]]$outcome10_2 <- dplyr::case_when( 
    ( as.integer(datalist[["main"]]$BIR01) == 1 | 
     as.integer(datalist[["main"]]$BIR02) == 1) &
    (as.integer(datalist[["main"]]$BIR03) == 1 |
     as.integer(datalist[["main"]]$BIR03) == 2 |
     as.integer(datalist[["main"]]$BIR03) == 3 )   ~ 1,
    
    (as.integer(datalist[["main"]]$BIR01) == 1 | 
     as.integer(datalist[["main"]]$BIR02) == 1) & (
     as.integer(datalist[["main"]]$BIR03) == 4 | 
     as.integer(datalist[["main"]]$BIR03) == 5 | 
     as.integer(datalist[["main"]]$BIR03) == 6 | 
     as.integer(datalist[["main"]]$BIR03) == 96| 
     as.integer(datalist[["main"]]$BIR03) == 98) ~ 0, 
    
    TRUE ~ NA_real_)

datalist[["main"]]$outcome10_2  <- labelled::labelled(datalist[["main"]]$outcome10_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                 label = "Proportion of births attended
                            by skilled health personnel")
}
   return(datalist)
}
```
  
```{r example-outcome10_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome10_2(datalist  )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome10_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome10_2}
test_that("outcome10_2 works", {
  expect_true(inherits(outcome10_2, "function")) 
})
```
  

 
 
## outcome12_1
    
```{r function-outcome12_1}
#' outcome12_1
#' 
#' **Proportion of Persons of Concern using at least basic drinking water services**
#' 
#' This indicator is defined as the percentage of PoCs using at least basic water services.
#' Access to clean drinking water is essential for a person's survival and well being and a precursor for achieving protection outcomes related to health, education and economic developed.
#' The calculation for access drinking water is linked to SGD Indicator [6.1.1](https://unstats.un.org/sdgs/metadata/files/Metadata-06-01-01.pdf).
#' The questionnaire module and the analysis guidance is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis).
#' 
#' 
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    DWA01-DWA04     |
#' 
#' **Numerator**: Population using improved sources of drinking water either in their dwelling/yard/plot or within 30 minutes round trip collection time
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: 
#'   *DWA03* \< 30 (under 30 minutes), &
#'  *DWA01* !=7,9,13,96,98 &
#'   *DWA02* !=3
#' 
#' This comes from the main dataset
#' There are two conditions as below improved source, in dwelling/yard/plot or reachable under 30 minutes 
#' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome12_1 <- function(datalist ){
  # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. What is the main source of drinking water for this household?", 
"2. Where is this ${source} - ${source2} located?", "Unit", "Time", 
"4. In the last 30 days, has there been any time when your household did not have sufficient quantities of drinking water when needed?"
)
              ,
            variable =  
c("DWA01", "DWA02", "DWA03a", "DWA03b", "DWA04")
              ),
          modalitymap = data.frame(
            variable =  
c("DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA02", "DWA02", "DWA02", 
"DWA03a", "DWA03a", "DWA03b", "DWA04", "DWA04")
               ,
            label =  
c("Piped Into Dwelling", "Piped Into Yard/Plot", "Piped To Neighbor", 
"Public Tap/Standpipe", "Tube Well/Borehole", "Protected Dug Well", 
"Unprotected Dug Well", "Protected Spring", "Unprotected Spring", 
"Rain Water Collection", "Tanker Truck/Water Vendor", "Cart With Small Tank/Drum", 
"Surface Water (River, Stream, Pond, Dam, Canal)", "Bottled Water", 
"Sachet Water", "Water Kiosk", "Other (Specify)", "Don't Know", 
"In Own Dwelling", "In Own Yard/Plot", "Elsewhere", "Minutes", 
"Hours", NA, "Yes", "No")
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 
"13", "14", "15", "16", "96", "98", "1", "2", "3", "1", "2", 
NA, "1", "0")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 12.1")
  } else {
  
  #convert hour into minutes
datalist[["main"]]$time_DWA <- dplyr::case_when(
    as.integer(datalist[["main"]]$DWA03a) == 1 ~ 1, 
    as.integer(datalist[["main"]]$DWA03a) == 2 ~ 60)

datalist[["main"]]$time_tot <- datalist[["main"]]$time_DWA * 
                                as.integer(datalist[["main"]]$DWA03b)

# reachable under 30 minutes
datalist[["main"]]$reachableU30 <- dplyr::case_when( 
  datalist[["main"]]$time_tot > 30 ~ 0,
  TRUE ~ 1) 

# improved source
datalist[["main"]]$dwa_cond1 <- dplyr::case_when(
  as.integer(datalist[["main"]]$DWA01) != 7 |
  as.integer(datalist[["main"]]$DWA01) != 9 |
  as.integer(datalist[["main"]]$DWA01) != 13 | 
  as.integer(datalist[["main"]]$DWA01) != 96 |
  as.integer(datalist[["main"]]$DWA01) != 98 ~ 1,
  
  TRUE ~ 0) 

datalist[["main"]]$dwa_cond1  <- labelled::labelled(datalist[["main"]]$dwa_cond1 ,
                            labels = c('Yes' = 1, 'No' = 0 ),
                            label = "Water: improved source") 

## Second condition

datalist[["main"]]$dwa_cond2 <- dplyr::case_when( 
  
  as.integer(datalist[["main"]]$DWA02) == 3   ~ 1, 
  
  #UNDER30 MIN
  as.integer(datalist[["main"]]$reachableU30) == 1 & 
  # NOT UNDER30 MIN
  as.integer(datalist[["main"]]$reachableU30) == 0 & 
  as.integer(datalist[["main"]]$DWA02) == 3 ~ 0, 
  
  # in the dwelling/yard/plot
  as.integer(datalist[["main"]]$DWA02) == 1 | 
  as.integer(datalist[["main"]]$DWA02) == 2 ~ 1, 
  
  TRUE ~ NA ) 

datalist[["main"]]$dwa_cond2  <- labelled::labelled(datalist[["main"]]$dwa_cond2 ,
                            labels = c('Yes' = 1, 'No' = 0 ),
                            label = "Water accessible") 


## Composite
datalist[["main"]]$outcome12_1 <- dplyr::case_when(
     (datalist[["main"]]$dwa_cond1 == 1 & 
      datalist[["main"]]$dwa_cond2 == 1 ) ~ 1, 
    TRUE ~ 0)

datalist[["main"]]$outcome12_1  <- labelled::labelled(datalist[["main"]]$outcome12_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
          label = "Proportion of PoC using at least basic drinking water services") 

   }
   return(datalist)
}
```
  
```{r example-outcome12_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome12_1(datalist  )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome12_1,
                     iconunicode = "f140")   
```
  
```{r tests-outcome12_1}
test_that("outcome12_1 works", {
  expect_true(inherits(outcome12_1, "function")) 
})
```
   

## outcome12_2
    
```{r function-outcome12_2}
#' outcome12_2
#' 
#' **Proportion of Persons of Concern with access to a safe household toilet**
#' 
#' This indicator measures the proportion of persons of concerns with access to at least basic sanitation services -- toilets -- that are not shared with other households.
#' A toilet is defined as a basic sanitation facility.
#' This indicator is linked to SGD indicator [6.2.1](https://sdg-tracker.org/water-and-sanitation#:~:text=Definition%3A%20Indicator%206.2.,at%20least%20basic%20handwashing%20facilities.).
#' The standard module is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis) main household questionnaire.
#' Calculation of the indicator is based on [MICS6 analysis tools](https://mics.unicef.org/tools#analysis).
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    TOI01-TOI05     |
#' 
#' **Numerator**: Total population with access to sanitation facility at their household
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *TOI01*=1,2,3,4,5,6,7,9 & (*TOI02* =1 & *TOI03*=1,2,3,4) & *TOI05*=1
#' This comes from the main dataset
#' MICS calculation WS3.1/WS3.4
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome12_2 <- function(datalist ){
  ## mapper, 
  mapper = list(
           hierarchy = "main",
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. What is the MAIN type of toilet facility used by your household?", 
"2. Has your toilet ever been emptied?", "3. The last time it was emptied, where were the contents emptied to?", 
"4. Where is this toilet facility located?", "5. Does your household share this facility with others households?"
)
              ,
            variable =  
c("TOI01", "TOI02", "TOI03", "TOI04", "TOI05")
              ),
          modalitymap = data.frame(
            variable =  
c("TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI01", 
"TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI02", 
"TOI02", "TOI02", "TOI03", "TOI03", "TOI03", "TOI03", "TOI03", 
"TOI03", "TOI03", "TOI04", "TOI04", "TOI04", "TOI05", "TOI05"
)
               ,
            label =  
c("Flush/pour flush to the piped sewer system", "Flush/pour-flush to septic tank", 
"Flush/pour-flush to pit latrine", "Flush/pour-flush to open drain", 
"Flush/pour-flush to don't know where", "Ventilated improved pit latrine", 
"Pit latrine with slab", "Pit latrine without slab/open pit", 
"Composting toilet", "Bucket", "Hanging toilet/hanging latrine", 
"No facility/bush/field", "Other (Specify)", "Yes, emptied", 
"No, never emptied", "Don't know", "Removed by a service provider to a treatment plant", 
"Removed by a service provider and buried in a covered pit", 
"Removed by a service provider to don’t know where", "Emptied by household and buried in a covered pit", 
"Emptied by household to uncovered pit, open ground, water body, or elsewhere", 
"Other (specify)", "Don’t know", "In Own Dwelling", "In Own Yard/Plot", 
"Elsewhere", "Yes", "No")
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 
"96", "1", "2", "98", "1", "2", "3", "4", "5", "96", "98", "1", 
"2", "3", "1", "0")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 12.2")
  } else {
  
    
datalist[["main"]]$toi_cond1 <- dplyr::case_when(
  as.integer(datalist[["main"]]$TOI01) == 1 |
  as.integer(datalist[["main"]]$TOI01) == 2 | 
  as.integer(datalist[["main"]]$TOI01) == 3 | 
  as.integer(datalist[["main"]]$TOI01) == 4 |
  as.integer(datalist[["main"]]$TOI01) == 5 |
  as.integer(datalist[["main"]]$TOI01) == 6 | 
  as.integer(datalist[["main"]]$TOI01) == 7 | 
  as.integer(datalist[["main"]]$TOI01) == 9 ~ 1,
  
  as.integer(datalist[["main"]]$TOI01) == 8 | 
  as.integer(datalist[["main"]]$TOI01) == 10 | 
  as.integer(datalist[["main"]]$TOI01) == 11 | 
  as.integer(datalist[["main"]]$TOI01) == 12 | 
  as.integer(datalist[["main"]]$TOI01) == 96 ~ 0,
  
  TRUE ~ NA_real_)

#Unsafe disposal
datalist[["main"]]$toi_cond2 <- dplyr::case_when(
 
    as.integer(datalist[["main"]]$TOI02) == 1 & 
    ( as.integer(datalist[["main"]]$TOI03) == 1 |
      as.integer(datalist[["main"]]$TOI03) == 2 |
      as.integer(datalist[["main"]]$TOI03) == 3 |
      as.integer(datalist[["main"]]$TOI03) == 4 ) ~ 1, 
    
    as.integer(datalist[["main"]]$TOI02) == 1 & 
      (as.integer(datalist[["main"]]$TOI03) ==5 |
       as.integer(datalist[["main"]]$TOI03) == 96 | 
       as.integer(datalist[["main"]]$TOI03) == 98) ~ 0, 
  
  as.integer(datalist[["main"]]$TOI02) == 2 ~  0, 
  as.integer(datalist[["main"]]$TOI02) == 98 ~ 0, 
  TRUE ~ NA_real_)

 # toilet not shared with other households
datalist[["main"]]$toi_cond3<- dplyr::case_when(
    as.integer(datalist[["main"]]$TOI05) == 1 ~ 0, 
    as.integer(datalist[["main"]]$TOI05) == 0 ~ 1) 


###Combine all three conditions below
### improved sanitation facility / 
# Safe disposal in situ of excreta from on-site sanitation facilities / 
# not shared with other HHs

datalist[["main"]]$outcome12_2<- dplyr::case_when(
    datalist[["main"]]$toi_cond1 == 1 | 
    datalist[["main"]]$toi_cond2 == 1 |
    datalist[["main"]]$toi_cond3 == 1 ~ 1,
    TRUE ~ 0)

datalist[["main"]]$outcome12_2  <- labelled::labelled(datalist[["main"]]$outcome12_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                label = "Proportion of Persons of Concern 
                            with acess to a safe household toilet")
}
   return(datalist)
}
```
  
```{r example-outcome12_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome12_2(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome12_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome12_2}
test_that("outcome12_2 works", {
  expect_true(inherits(outcome12_2, "function")) 
})
```

## outcome13_1 
    
```{r function-outcome13_1}
#' outcome13_1
#' 
#' **Proportion of Persons of Concern with an account at a bank or other financial institution or with a mobile-money-service provider**
#' 
#' This indicator measures the percentage of persons of concern (ages 15+) who report having an account (by themselves or together with someone else) at a bank or another type of financial institution or personally using a mobile money service in the past 12 months in the country of asylum or habitual residence (for returnees, countries of origin are included).
#' 
#' The methodology is taken from [The Global Findex Database](https://www.worldbank.org/en/publication/globalfindex) which is developed by the World Bank.
#' This indicator is also linked to SGD Indicator [8.10.2](https://unstats.un.org/sdgs/metadata/files/Metadata-08-10-02.pdf).
#' 
#' | Standard Questions |
#' |:------------------:|
#' |   BANK01-BANK05    |
#' 
#' **Numerator**: Total population having a personal mobile or bank account
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *BANK01*=1 \| *BANK02*=1 \| *BANK03*=1 \|*BANK05*=1
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' include if the respondent has an account on their own/with someone else, ATM card, personal bank card
#' or personally used phone to send money (proxy)
#' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome13_1 <- function(datalist){
  
  ## Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. Do you, either by yourself or together with someone else, currently have an account at a bank or another type of formal financial institution in ${countryname} ?", 
"2. Do you, personally, have a/an [local terminology for ATM/debit card] in ${countryname} ?", 
"3. Is this [local terminology for ATM/debit card] connected to an account with your name on it in ${countryname} ?", 
"4. In the past 12 months, have you used a mobile phone to make payments, to buy things, or to send or receive money?", 
"5. In the past 12 months, have you, personally, used a mobile phone to make payments, to buy things, or to send or receive money using a service such as [local example of mobile money from GSMA database, like M-PESA]?"
)
              ,
            variable =  
c("BANK01", "BANK02", "BANK03", "BANK04", "BANK05")
              ),
          modalitymap = data.frame(
            variable =  
c("BANK01", "BANK01", "BANK02", "BANK02", "BANK03", "BANK03", 
"BANK04", "BANK04", "BANK05", "BANK05")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", 
"No")
               ,
            standard =  
c("1", "0", "1", "0", "1", "0", "1", "0", "1", "0")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 13.1")
  } else {
  
datalist[["main"]]$outcome13_1 <- dplyr::case_when(
      as.integer(datalist[["main"]]$BANK01) == 1 | 
      as.integer(datalist[["main"]]$BANK02) == 1 | 
      as.integer(datalist[["main"]]$BANK03) == 1 |
      as.integer(datalist[["main"]]$BANK05) == 1 ~ 1,
      
      as.integer(datalist[["main"]]$BANK01) == 0 & 
      as.integer(datalist[["main"]]$BANK02) == 0 & 
      as.integer(datalist[["main"]]$BANK03) == 0 & 
      as.integer(datalist[["main"]]$BANK05) == 0 ~ 0,
      TRUE ~ 0)

datalist[["main"]]$outcome13_1  <- labelled::labelled(datalist[["main"]]$outcome13_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
                label = "PoC with an account at a bank or other financial 
                institution or with a mobile-money service provider")
  
}
   return(datalist)
}
```
  
```{r example-outcome13_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome13_1(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome13_1,
                     iconunicode = "f140")   
```
  
```{r tests-outcome13_1}
test_that("outcome13_1 works", {
  expect_true(inherits(outcome13_1, "function")) 
})
```
  


## outcome13_2
    
```{r function-outcome13_2}
#' outcome13_2
#' 
#' **Proportion of Persons of Concern who self-report positive changes in their income compared to previous year**
#' 
#' This indicator measures the proportion of PoC who self-report positive changes in their income compared to previous year.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       INC01        |
#' 
#' **Numerator**: Population 18 and above who self-report increased income compared to last year
#' 
#' **Denominator**: Total population 18 and above
#' 
#' **Formula**: *INC01*=1
#'
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#'  Only calculate as positive if they responded 'more' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome13_2 <- function(datalist){
  ## Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
"11. Compared to this time last year, do you think you can now afford more goods and services, the same, or fewer goods and services?"
              ,
            variable =  
"INC01"
              ),
          modalitymap = data.frame(
            variable =  
c("INC01", "INC01", "INC01", "INC01")
               ,
            label =  
c("More", "The same", "Fewer", "Don't know")
               ,
            standard =  
c("1", "2", "3", "98")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 13.2")
  } else {
  
datalist[["main"]]$outcome13_2<- dplyr::case_when(
  
    as.integer(datalist[["main"]]$INC01) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$INC01) == 2 |
    as.integer(datalist[["main"]]$INC01) == 3 |
    as.integer(datalist[["main"]]$INC01) == 98 ~ 0 )

datalist[["main"]]$outcome13_2  <- labelled::labelled(datalist[["main"]]$outcome13_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
    label = "Proportion of PoC who self-report positive changes in their income compared to previous year")

}
 return(datalist)
}
```
  
```{r example-outcome13_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome13_2(datalist)

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome13_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome13_2}
test_that("outcome13_2 works", {
  expect_true(inherits(outcome13_2, "function")) 
})
```
  
 

## outcome13_3
    
```{r function-outcome13_3}
#' outcome13_3#' 
#' 
#' **Proportion of Persons of Concern (working age) who are unemployed**
#' The unemployment rate is a standard indicator to measure the efficiency and effectiveness of an economy.
#' For Persons of Concern, access to employment is central for self-reliance, socio-economic inclusion and dignity and often restricted through laws, policies or practical barriers.
#' This indicator is also linked to SGD [8.5.2](https://unstats.un.org/sdgs/metadata/files/Metadata-08-05-02.pdf).
#' The standard questionnaire module is from [Standardized Employment Module](https://www.unhcr.org/5ea81b954) of UNHCR.
#' The calculations are also done based on the same guidance.
#' | Standard Questions |
#' |:------------------:|
#' |   UNEM01-UNEM10    |
#' 
#' **Numerator**: Unemployed working age population within a country
#' 
#' **Denominator**: Total working age population who are employed and unemployed within a country (often referred to as labour force)
#' 
#' **Formula**: *UNEM01*=1 \| (*UNEM02*=1 & *UNEM07*=3) \| *UNEM04*=1 \| (*UNEM02*=1 & *UNEM07*=1 &( *UNEM08*=1,2)) \|(*UNEM05*=1 & *UNEM06*=3) \| ( *UNEM05*=1 & ( *UNEM06*=1,2 \| *UNEM08*=1,2)
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' 
#' 
#' #Numerator: Those of working age who were not in employment, looked for employment in the past 30 days and were available to take up employment
####Denominator: Those of working age in labour force
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome13_3 <- function(datalist ){
  # mapper , 

mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. During the past 7 days, did ${name_selectedadult18} work for someone else for pay, for one or more hours?", 
"2. During the past 7 days, did ${name_selectedadult18} run or do any kind of business, farming, or other activity to generate income?", 
"3. During the past 7 days, did ${name_selectedadult18} help in a family business or farm?", 
"4. Even though ${name_selectedadult18} did not work, during the past 7 days, did he/she have a paid job from which he/she was temporarily absent?", 
"5. Even though ${name_selectedadult18} did not work, during the past 7 days, did he/she have a business or a helper job in a family business/farm from which he/she was temporarily absent?", 
"6. Last week, did ${name_selectedadult18} do any work in…?", 
"7. Was this work that  ${name_selectedadult18} mentioned in...?", 
"8. Thinking about this work, are the products intended...?", 
"9. During the last 30 days, did ${name_selectedadult18} do anything to find a paid job or try to start a business?", 
"10. Could ${name_selectedadult18} start working within the next two weeks?"
)
              ,
            variable =  
c("UNEM01", "UNEM02", "UNEM03", "UNEM04", "UNEM05", "UNEM06", 
"UNEM07", "UNEM08", "UNEM09", "UNEM10")
              ),
          modalitymap = data.frame(
            variable =  
c("UNEM01", "UNEM01", "UNEM02", "UNEM02", "UNEM03", "UNEM03", 
"UNEM04", "UNEM04", "UNEM05", "UNEM05", "UNEM06", "UNEM06", "UNEM06", 
"UNEM07", "UNEM07", "UNEM07", "UNEM08", "UNEM08", "UNEM08", "UNEM08", 
"UNEM09", "UNEM09", "UNEM10", "UNEM10")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", 
"No", "Farming or rearing farm animals", "Fishing or fish farming", 
"None of the above", "Farming or rearing farm animals", "Fishing or fish farming", 
"None of the above", "Only for sale", "Mainly for sale", "Only for family use", 
"Mainly for family use", "Yes", "No", "Yes", "No")
               ,
            standard =  
c("1", "0", "1", "0", "1", "0", "1", "0", "1", "0", "1", "2", 
"3", "1", "2", "3", "1", "2", "3", "4", "1", "0", "1", "0")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 13.23")
  } else {
  

datalist[["main"]]$employed <- dplyr::case_when(
  
    as.integer(datalist[["main"]]$UNEM01) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$UNEM02) == 1 & 
    as.integer(datalist[["main"]]$UNEM07) == 3 ~ 1,
    
    as.integer(datalist[["main"]]$UNEM04) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$UNEM02) == 1 & 
    as.integer(datalist[["main"]]$UNEM07) == 1 & 
      (as.integer(datalist[["main"]]$UNEM08) == 1 | 
       as.integer(datalist[["main"]]$UNEM08) == 2) ~ 1,
    
    as.integer(datalist[["main"]]$UNEM05) == 1 & 
    as.integer(datalist[["main"]]$UNEM06) == 3 ~ 1,
    as.integer(datalist[["main"]]$UNEM05) == 1 & 
     ( as.integer(datalist[["main"]]$UNEM06) == 1 | 
       as.integer(datalist[["main"]]$UNEM06) == 2) & 
     ( as.integer(datalist[["main"]]$UNEM08) == 1 | 
       as.integer(datalist[["main"]]$UNEM08) == 2) ~ 1,
    TRUE ~ 0)


datalist[["main"]]$employed  <- labelled::labelled(datalist[["main"]]$employed,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion employed")


datalist[["main"]]$unemployed<- dplyr::case_when(
    as.integer(datalist[["main"]]$employed) == 0 & 
    as.integer(datalist[["main"]]$UNEM09) == 1 & 
    as.integer(datalist[["main"]]$UNEM10) == 1 ~ 1,
    TRUE ~ 0)


datalist[["main"]]$unemployed  <- labelled::labelled(datalist[["main"]]$unemployed,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion unemployed")

datalist[["main"]]$labour_force <- dplyr::case_when(
    datalist[["main"]]$employed == 1 | 
    datalist[["main"]]$unemployed == 1 ~ 1)


datalist[["main"]]$labour_force  <- labelled::labelled(datalist[["main"]]$labour_force,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion forming labour force")

datalist[["main"]]$outcome13_3 <- dplyr::case_when(
  (datalist[["main"]]$unemployed == 1 &  
  datalist[["main"]]$labour_force == 1)  ~ 1,
  (datalist[["main"]]$employed == 1 &  
  datalist[["main"]]$labour_force == 1)  ~ 0,
      TRUE ~ NA_real_   )
  

datalist[["main"]]$outcome13_3  <- labelled::labelled(datalist[["main"]]$outcome13_3,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion of unemployed while being part of labour force")

  }
 return(datalist)
    
}
```
  
```{r example-outcome13_3, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome13_3(datalist )

table( datalist[["main"]]$outcome13_3, useNA = "ifany")
## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome13_3,
                     iconunicode = "f140")   
```
  
```{r tests-outcome13_3}
test_that("outcome13_3 works", {
  expect_true(inherits(outcome13_3, "function")) 
})
```

## outcome14_1
    
```{r function-outcome14_1}
#' outcome14_1
#' 
#' **Proportion of returnees with legally recognized identity documents or credentials**
#' 
#' This indicator measures the proportion of returned refugees who possess legally recognized and valid identity documents or credentials to support their return .
#' 
#' Commonly in the context of return, returnees require civil documentation or credentials and inclusion in or updating of civil registries , as well as access to services.
#' 
#' ***Definitions***
#' 
#' • Identity document or credential is any document or credential which may be used as proof of identity, which may also include reference to the individuals' legal status and associated rights vis-à-vis the host State and/or UNHCR.
#' 
#' |          Standard Questions           |
#' |:-------------------------------------:|
#' | REG01 - REG02 - REG03 / REG05 - REG06 |
#' 
#' **Numerator**: Total number of returnees with with legally recognized identity documents or credentials
#' 
#' **Denominator**: Total number of returnees
#' 
#' **Formula**: *REG01*=1 \| *REG02*=1 \| *REG03*=1 \| *REG05*=1 \| *REG06*=1
#' 
#'This indicator comes from the individual dataset
#' Calculate valid identity documents for under 5 with REG05 and REG06 variables
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome14_1 <- function(datalist ){
  ## Mapper , 

mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("Passport?", "Birth certificate?", "Civil/government-issued ID card ?", 
"Residency permit (both temporary and permanent)?", "Statelessness documentation?", 
"Household card of address / family book/ marriage certificate?", 
"Social security card?", "2. Does ${name_individual} have any other document that establishes his/her legal identity?", 
"3. Does ${name_individual} have a birth certificate?", "4. Has ${name_individual}'s birth been registered with civil authorities?", 
"Passport?", "Civil/government-issued ID card ?", "Residency permit (both temporary and permanent)?", 
"Statelessness documentation?", "Household card of address / family book/ marriage certificate?", 
"Social security card?", "6. Does ${name_individual} have any other document that establishes your legal identity?"
)
              ,
            variable =  
c("REG01a", "REG01b", "REG01c", "REG01d", "REG01e", "REG01f", 
"REG01g", "REG02", "REG03", "REG04", "REG05a", "REG05b", "REG05c", 
"REG05d", "REG05e", "REG05f", "REG06")
              ),
          modalitymap = data.frame(
            variable =  
c("REG01a", "REG01a", "REG01a", "REG01b", "REG01b", "REG01b", 
"REG01c", "REG01c", "REG01c", "REG01d", "REG01d", "REG01d", "REG01e", 
"REG01e", "REG01e", "REG01f", "REG01f", "REG01f", "REG01g", "REG01g", 
"REG01g", "REG02", "REG02", "REG02", "REG03", "REG03", "REG03", 
"REG04", "REG04", "REG04", "REG04", "REG05a", "REG05a", "REG05a", 
"REG05b", "REG05b", "REG05b", "REG05c", "REG05c", "REG05c", "REG05d", 
"REG05d", "REG05d", "REG05e", "REG05e", "REG05e", "REG05f", "REG05f", 
"REG05f", "REG06", "REG06", "REG06")
               ,
            label =  
c("Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Don't know", "Yes", "No", "Don't know", "Prefer not to say", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond")
               ,
            standard =  
c("1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "98", "1", "0", "98", "99", "1", "0", "99", "1", "0", 
"99", "1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", 
"99", "1", "0", "99")
              ))
       
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 14.1")
  } else {

datalist[["ind"]]$document_under5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG05a) == 1 |  #ind$REG05a - passport
      as.integer(datalist[["ind"]]$REG05b) == 1 |  #ind$REG05b - civil/government issued ID
      as.integer(datalist[["ind"]]$REG05c) == 1 |  #ind$REG05c - residency permit
      as.integer(datalist[["ind"]]$REG05d) == 1 |  #ind$REG05d - statelessness documentation
      as.integer(datalist[["ind"]]$REG05e) == 1 |  #ind$REG05e - household card of address/family book
      as.integer(datalist[["ind"]]$REG05f) == 1 |  #ind$REG05f - social security card
      as.integer(datalist[["ind"]]$REG06)  == 1 | #ind$REG06 - any other document establishes identity
      as.integer(datalist[["ind"]]$REG03)  == 1   #add birth certificate as additional document from REG03
           ~ 1,
      as.integer(datalist[["ind"]]$REG05a) == 0 & 
      as.integer(datalist[["ind"]]$REG05b) == 0 & 
      as.integer(datalist[["ind"]]$REG05c) == 0 & 
      as.integer(datalist[["ind"]]$REG05d) == 0 & 
      as.integer(datalist[["ind"]]$REG05e) == 0 & 
      as.integer(datalist[["ind"]]$REG05f) == 0 & 
      as.integer(datalist[["ind"]]$REG06) == 0 & 
      as.integer(datalist[["ind"]]$REG03) == 0 ~ 0, 
      TRUE ~ NA_real_ )
  
  ###Calculate  valid identity documents for above 5 with REG01 and REG02 variables
  
  
  #ind$REG01a # passport
  #ind$REG01b # birth certificate
  #ind$REG01c # civil/ government issued ID
  #ind$REG01d # residency permit
  #ind$REG01e # statelessness documentation
  #ind$REG01f # household card of address/family book
  #ind$REG01g # social security card
  #ind$REG02 # any other document establishes identity
  
datalist[["ind"]]$document_above5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG01a) == 1 | 
      as.integer(datalist[["ind"]]$REG01b) == 1 | 
      as.integer(datalist[["ind"]]$REG01c) == 1 | 
      as.integer(datalist[["ind"]]$REG01d) == 1 | 
      as.integer(datalist[["ind"]]$REG01e) == 1 | 
      as.integer(datalist[["ind"]]$REG01f) == 1 | 
      as.integer(datalist[["ind"]]$REG01g) == 1 |
      as.integer(datalist[["ind"]]$REG02) == 1 ~ 1,
      
      as.integer(datalist[["ind"]]$REG01a) == 0 & 
      as.integer(datalist[["ind"]]$REG01b) == 0 & 
      as.integer(datalist[["ind"]]$REG01c) == 0 & 
      as.integer(datalist[["ind"]]$REG01d) == 0 & 
      as.integer(datalist[["ind"]]$REG01e) == 0 & 
      as.integer(datalist[["ind"]]$REG01f) == 0 & 
      as.integer(datalist[["ind"]]$REG01g) == 0 & 
      as.integer(datalist[["ind"]]$REG02) == 0 ~ 0, 
      
      TRUE ~ NA_real_)
      
  ##Combine both age groups
datalist[["ind"]]$outcome14_1<- dplyr::case_when(
     (datalist[["ind"]]$document_above5 == 1 | 
      datalist[["ind"]]$document_under5 == 1) ~ 1,
     
     (datalist[["ind"]]$document_above5 == 0 | 
      datalist[["ind"]]$document_under5 == 0) ~ 0)

datalist[["ind"]]$outcome14_1  <- labelled::labelled(datalist[["ind"]]$outcome14_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
                label = "Proportion of returnees with legally recognized identity 
                documents or credentials")
  }
   return(datalist)
}
```
  
```{r example-outcome14_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))

## Apply indicator function on datalist
datalist <- outcome14_1(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome14_1,
                     iconunicode = "f140")   
```
  
```{r tests-outcome14_1}
test_that("outcome14_1 works", {
  expect_true(inherits(outcome14_1, "function")) 
})
```

## outcome16_1
    
```{r function-outcome16_1}
#' outcome16_1
#' 
#'  **Proportion of Persons of Concern with secure tenure rights and/or property rights to housing and/or land**
#'  
#'  This indicator measures the proportion of persons of concern that have secure tenure rights to housing and/or land.
#' Security of tenure means that persons of concern can live in their homes without fear of forced eviction, whether in communal settlement situations, informal settlements, host communities or after return.
#' 
#' This indicator is linked to SGD Indicator [1.4.2](https://unstats.un.org/sdgs/metadata/files/Metadata-01-04-02.pdf). The further guidance can be found [here](https://gltn.net/download/measuring-individuals-rights-to-land-an-integrated-approach-to-data-collection-for-sdg-indicators-1-4-2-and-5-a-1-english/?wpdmdl=16316&refresh=5efb342458df61593521188)
#' 
#'  *Concept*
#' 
#' -   Secure tenure rights: comprised of two sub-components: (i) legally recognized documentation and (ii) perception of the security of tenure, which are both necessary to provide a full measurement of tenure security.
#' 
#' -   Legally recognized documentation: Legal documentation of rights refers to the recording and publication of information on the nature and location of land, rights and right holders in a form that is recognized by government, and is therefore official.
#' 
#' -   Perceived security of tenure: Perception of tenure security refers to an individual's perception of the likelihood of involuntary loss of land, such as disagreement of the ownership rights over land or ability to use it, regardless of the formal status and can be more optimistic or pessimistic.
#' 
#' |    Standard Questions     |
#' |:-------------------------:|
#' | DWE06-DWE07 & DWE10-DWE11 |
#' 
#' **Numerator**: Total population with secure tenure rights to housing and/or land
#' 
#' **Denominator**: Total population
#' **Formula**: *DWE011* = 1,2 & *DWE10* = 1,2,3,4,5,6 & *DWE06* != 9, 96,98,99 & *DWE07* = 9, 96,98,99 
#' This indicator is calculated from the main dataset
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome16_1 <- function(datalist ){
  # Mapper , 

mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("6. Who owns the dwelling that you currently live in?", "7. Who owns the land that your current dwelling is built on?", 
"10. What type of documents does your household have for the housing you live in?", 
"11. In the next 12 months, how likely or unlikely is it that you could lose your right to this housing and/or land, against your will?"
)
              ,
            variable =  
c("DWE06", "DWE07", "DWE10", "DWE11")
              ),
          modalitymap = data.frame(
            variable =  
c("DWE06", "DWE06", "DWE06", "DWE06", "DWE06", "DWE06", "DWE06", 
"DWE06", "DWE06", "DWE06", "DWE06", "DWE06", "DWE07", "DWE07", 
"DWE07", "DWE07", "DWE07", "DWE07", "DWE07", "DWE07", "DWE07", 
"DWE07", "DWE07", "DWE07", "DWE07", "DWE07", "DWE10", "DWE10", 
"DWE10", "DWE10", "DWE10", "DWE10", "DWE10", "DWE11", "DWE11", 
"DWE11", "DWE11", "DWE11")
               ,
            label =  
c("Respondent or another HH member", "Unrelated Person", "Friend Or Relative", 
"Ngo/Non-Religious Charity", "Government Agency Or Municipality", 
"UNHCR", "Religious Organization/ Charity", "Foreign Government", 
"Unowned/Squatting", "Other (Specify)", "Don't know", "Prefer not to respond", 
"Respondent or another HH member", "Unrelated Person", "Friend Or Relative", 
"Ngo/Non-Religious Charity", "Government Agency Or Municipality", 
"UNHCR", "Religious Organization/ Charity", "Foreign Government", 
"Unowned/Squatting", "Apartment Building", "Community", "Other(Specify)", 
"Don't know", "Prefer not to respond", "Title deed", "Certificate of customary ownership", 
"Certificate of occupancy", "Certificate of hereditary acquisition listed in registry", 
"Rental contract", "Lease registered", "Other (Specify)", "Very unlikely", 
"Somewhat unlikely", "Somewhat likely", "Very likely", "Don't Know"
)
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "96", "98", "99", 
"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "96", 
"98", "99", "1", "2", "3", "4", "5", "6", "96", "1", "2", "3", 
"4", "99")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 16.1")
  } else {
  
  # likelihood of losing right for housing is unlikely
  datalist[["main"]]$housing_cond1<- dplyr::case_when(
         (as.integer(datalist[["main"]]$DWE11) == 1 | 
          as.integer(datalist[["main"]]$DWE11) == 2 ) ~ 1, 
         TRUE ~ 0)
# have official documents to proof residency
  datalist[["main"]]$housing_cond2 <- dplyr::case_when(
    as.integer(datalist[["main"]]$DWE10) == 96 ~ 0, 
    as.integer(datalist[["main"]]$DWE10) == 1 | 
    as.integer(datalist[["main"]]$DWE10) == 2 |  
    as.integer(datalist[["main"]]$DWE10) == 3 | 
    as.integer(datalist[["main"]]$DWE10) == 4 | 
    as.integer(datalist[["main"]]$DWE10) == 5 | 
    as.integer(datalist[["main"]]$DWE10) == 6 ~ 1)
  
# not un-owned or not squatting
  datalist[["main"]]$housing_cond3 <- dplyr::case_when(
    as.integer(datalist[["main"]]$DWE06) == 9 | 
    as.integer(datalist[["main"]]$DWE06) == 96 | 
    as.integer(datalist[["main"]]$DWE06) == 98 | 
    as.integer(datalist[["main"]]$DWE06) == 99 | 
    as.integer(datalist[["main"]]$DWE07) == 9 | 
    as.integer(datalist[["main"]]$DWE07) == 96 | 
    as.integer(datalist[["main"]]$DWE07) == 98 | 
    as.integer(datalist[["main"]]$DWE07) == 99 ~ 0, 
    TRUE ~ 1)
  
datalist[["main"]]$outcome16_1<- dplyr::case_when(
    as.integer(datalist[["main"]]$housing_cond1) == 1 & 
    as.integer(datalist[["main"]]$housing_cond2) == 1 & 
    as.integer(datalist[["main"]]$housing_cond3) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$housing_cond1) == 0 | 
    as.integer(datalist[["main"]]$housing_cond2) == 0 | 
    as.integer(datalist[["main"]]$housing_cond3) == 0 ~ 0)

datalist[["main"]]$outcome16_1  <- labelled::labelled(datalist[["main"]]$outcome16_1,
      labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion of PoC with secure tenure rights and/or property rights to housing and/or land")
  }
   return(datalist)
}
```
  
```{r example-outcome16_1, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))

## Apply indicator function on datalist
datalist <- outcome16_1(datalist )

## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome16_1,
                     iconunicode = "f140")    
```
  
```{r tests-outcome16_1}
test_that("outcome16_1 works", {
  expect_true(inherits(outcome16_1, "function")) 
})
```


## outcome16_2
    
```{r function-outcome16_2}
#' outcome16_2
#' 
#'  **Proportion of Persons of Concern covered by social protection floors/systems**
#'  This indicator measures the proportion of persons of concern who receive government social protection benefits.
#'  Social protection is a set of policies and programmes aimed at preventing or 
#'  protecting all people against poverty, vulnerability and social exclusion 
#'  throughout their life-course, with particular emphasis on vulnerable groups.
#'   For persons of concern, being part of a social protection system is a measure
#'    of integration and stability. This indicator is linked to SGD indicator
#'     [1.3.1](https://unstats.un.org/sdgs/metadata/files/Metadata-01-03-01a.pdf).
#'  
#'  This indicator focuses on the social benefits received from the government in which UNHCR might be supporting UNHCR.
#'  
#'  |    Standard Questions     | 
#'  |:-------------------------:|
#'  | SPF01                     |
#'  
#'  **Numerator**: Total population covered by social protection floors/systems
#'  **Denominator**: Total population
#'  **Formula**: *SPF01*=1 
#'  
#' This indicator is calculated from the main dataset
#' If PoC has covered by at least one of the social protection floors/systems
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
outcome16_2 <- function(datalist ){
   # Mapper , 

mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("Social protection cash benefit", "Parental benefit", "Disability benefit", 
"Unemployment benefit", "Employment injury benefit", "Old-age pension", 
"Other vulnerability benefit", "Social assistance cash benefit"
)
              ,
            variable =  
c("SPF01a", "SPF01b", "SPF01c", "SPF01d", "SPF01e", "SPF01f", 
"SPF01g", "SPF01h")
              ),
          modalitymap = data.frame(
            variable =  
c("SPF01a", "SPF01a", "SPF01a", "SPF01b", "SPF01b", "SPF01b", 
"SPF01c", "SPF01c", "SPF01c", "SPF01d", "SPF01d", "SPF01d", "SPF01e", 
"SPF01e", "SPF01e", "SPF01f", "SPF01f", "SPF01f", "SPF01g", "SPF01g", 
"SPF01g", "SPF01h", "SPF01h", "SPF01h")
               ,
            label =  
c("Yes", "No", "Don't know", "Yes", "No", "Don't know", "Yes", 
"No", "Don't know", "Yes", "No", "Don't know", "Yes", "No", "Don't know", 
"Yes", "No", "Don't know", "Yes", "No", "Don't know", "Yes", 
"No", "Don't know")
               ,
            standard =  
c("1", "0", "98", "1", "0", "98", "1", "0", "98", "1", "0", "98", 
"1", "0", "98", "1", "0", "98", "1", "0", "98", "1", "0", "98"
)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 16.2")
  } else {
  
datalist[["main"]]$outcome16_2 <- dplyr::case_when(
    datalist[["main"]]$SPF01a == 1 |
    datalist[["main"]]$SPF01b == 1 |
    datalist[["main"]]$SPF01c == 1 |
    datalist[["main"]]$SPF01d == 1 | 
    datalist[["main"]]$SPF01e == 1 | 
    datalist[["main"]]$SPF01f == 1 | 
    datalist[["main"]]$SPF01g == 1 | 
    datalist[["main"]]$SPF01h == 1 ~ 1, 
    TRUE ~ 0)

  datalist[["main"]]$outcome16_2  <- labelled::labelled(datalist[["main"]]$outcome16_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
   label = "Proportion of Persons of Concern covered by social protection 
   floors/systems")
  
  }
   return(datalist)
}
```
  
```{r example-outcome16_2, message=TRUE, warning=FALSE}
## data, cf example  fct_re_map()
datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
                                                 package = "IndicatorCalc"))
## Apply indicator function on datalist
datalist <- outcome16_2(datalist)

table( datalist[["main"]]$outcome16_2, useNA = "ifany")
## Visualise value
fct_plot_indic_donut(indicator = datalist[["main"]]$outcome16_2,
                     iconunicode = "f140")   
```
  
```{r tests-outcome16_2}
test_that("outcome16_2 works", {
  expect_true(inherits(outcome16_2, "function")) 
})
```
  

--- 
 
```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(flat_file = "dev/indicators.Rmd", vignette_name = "Indicators calculation functions")
```

 
