# WARNING - Generated by {fusen} from dev/utilities.Rmd: do not edit by hand

#' fct_build_map
#' 
#' Quick helper to reformat the data from the mapping file into the mapping file
#' to use  with each indicator calculation. T
#' 
#' his needs to be done in two steps: 
#' one for `ind` for individual level and 
#' one for `main` for household level
#' 
#' @param mappingfile full path to the xlsx file with the revise variable mapping generated with `fct_var_mapping()`
#' 
#' @param IndicatorRequirementFile path to the file where the standard mapping is depending on form version
#' 
#' @param thisMeasureLevel can be `ind` for individual level or `main` for household level
#' 
#' @import readxl
#' @import dplyr
#' 
#' @return a list 
#' 
#' @export
#' @examples
#' mappingfile <- system.file("RMS_CAPI_v2_mapping.xlsx", 
#'                            package = "IndicatorCalc")
#'
#' IndicatorRequirementFile <- system.file("RMS_CAPI_v2_mapper.xlsx", 
#'                            package = "IndicatorCalc")
#'
#' mappermain <- fct_build_map(mappingfile = mappingfile, 
#'                             IndicatorRequirementFile = IndicatorRequirementFile,
#'                             thisMeasureLevel = "main")
#'
#' mapperind <- fct_build_map(mappingfile = mappingfile,
#'                             IndicatorRequirementFile = IndicatorRequirementFile,
#'                            thisMeasureLevel = "ind")
#'
fct_build_map <- function(mappingfile,
                          IndicatorRequirementFile,
                          thisMeasureLevel){
  
  IndicMap <- readxl::read_excel( IndicatorRequirementFile)
  ## Merge the map...
  MeasureLevelQ <- IndicMap |>
               dplyr::select(MeasureLevel, QuestionVar)  |>
               dplyr::filter(MeasureLevel == thisMeasureLevel)|>
               dplyr::distinct()
  
  revisemapIndic <- readxl::read_excel( mappingfile, 
    sheet = "result_matchInd")
  
   revisemapIndic2 <- MeasureLevelQ |>
                dplyr::left_join(revisemapIndic, by = c("QuestionVar") ) |>
                dplyr::rename(#QuestionVar, 
                              #label, 
                              mappattern = "best_name") |>
                dplyr::select(QuestionVar, label, mappattern)|>
               dplyr::distinct()
   
   # names( IndicMap)
   # names(revisemapIndic2)  
   # names(revisemapMod)   
   
   
  revisemapMod <- readxl::read_excel( mappingfile, 
    sheet = "result_matchMod")
  revisemapMod2 <- MeasureLevelQ  |>
                dplyr::left_join(revisemapMod, by = c("QuestionVar") ) |>
                dplyr::rename(#variable = "QuestionVar", 
                             # label= "label_mod" ,   
                             # standard = "name_mod" , 
                              map = "best_name") |>
                dplyr::select(QuestionVar, label_mod, name_mod, map)
   
 
   
  filemap <- tempfile()
  filemaplab <- tempfile()
  #filemap <- "dev/test1.R"
  if (file.exists(filemap)) file.remove(filemap) 
     
     cat( paste0( "thismapper = list("), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "           hierarchy = \"", thisMeasureLevel,"\","), file = filemap , sep = "\n", append = TRUE)
     
 
     ## Mapping variables
     thisvar <- revisemapIndic2 |>  
                    dplyr::select(QuestionVar, label, mappattern) |> 
                    dplyr::distinct()  
     cat( paste0( "          variablemap = data.frame("), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            label = "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around labels
          dput( thisvar |> dplyr::pull(label) , file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "              ,"), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            mappattern = "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around mappattern
          dput( thisvar |> dplyr::pull(mappattern) , file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "              ,"), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            variable =  "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around  variable
      dput( thisvar |> dplyr::pull(QuestionVar), file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "              ),"), file = filemap , sep = "\n", append = TRUE)
    
      ## Mapping modality
     thismod <- revisemapMod2 |> 
                    dplyr::select(QuestionVar, label_mod, name_mod, map) |> 
                    dplyr::filter(! (is.null(name_mod)) ) |> 
                    dplyr::distinct()  
     cat( paste0( "          modalitymap = data.frame("), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            variable =  "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around variable for modalities
      dput( thismod |> dplyr::pull(QuestionVar) , file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "               ,"), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            label =  "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around labels for modalities
      dput( thismod |> dplyr::pull(label_mod) , file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "               ,"), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            map =  "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around labels for modalities
      dput( thismod |> dplyr::pull(map) , file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "               ,"), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "            standard =  "), file = filemap , sep = "\n", append = TRUE)
     ## Looping around standard for modalities
      dput( thismod |> dplyr::pull(name_mod) , file = filemaplab )
          file_str <- paste(readLines(filemaplab), collapse="\n")
     cat( paste0(file_str), file = filemap , sep = "\n", append = TRUE)
     cat( paste0( "              ))"), file = filemap , sep = "\n", append = TRUE) 
     
    source(filemap)
     
 return(thismapper)
}
