# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' fct_check_map
#' 
#' This check is the standard variable and modalities
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                    
#' @param mapper a list providing the mapping of the variables used for the 
#' calculation - this mapper is potentially to be adjusted in relation with deviation
#' between the the standard XlsForm and the contextualized dataset
#' 
#' 
#' @return TRUE or FALSE
#' 
#' @export
#' @examples
#'
#' mapper = list(
#'             hierarchy = "main",
#'             variablemap = data.frame(
#'               label = c("Does this household use anything for lighting?",
#'                         "What source of electricity is used most of the time in this household?"),
#'               variable = c("LIGHT01", 
#'                            "LIGHT03"),
#'               mappattern = c("LIGHT01", 
#'                            "LIGHT03") ),
#'             modalitymap = data.frame(
#'               variable = c( "LIGHT01", 
#'                             "LIGHT03", "LIGHT03", "LIGHT03"),
#'               label = c( "yes",
#'                         "No electricity in household", "Other, specify", "Don't know"),
#'               standard = c( "1",
#'                            "1", "96", "98"),
#'               map = c("1",
#'                       "1", "96", "98")
#'             )
#'           )
#'
#' ## Correct format
#' data <- list(main = data.frame(
#'                 LIGHT01 = c("1",  "1",  "0", "1",  "1",  "0", "1",  "1",  "1"),
#'                 LIGHT03 = c("1", "96", "98", "1", "96", "98", "0", "96", "98"))
#'              )
#' fct_check_map(datalist = data, mapper = mapper )
#'
#' ## One variable is not correctly 
#' data <- list(main = data.frame(
#'                 LIGHT01 = c("1",  "1",  "0", "1",  "1",  "0", "1",  "1",  "1"),
#'                 LIGH03 = c("1", "96", "98", "1", "96", "98", "0", "96", "98"))
#'              )
#' fct_check_map(datalist = data, mapper = mapper )
#'
#' ## The first variable does not include a single 1...
#' data <- list(main = data.frame(
#'                 LIGHT01 = c("0",  "0",  "0", "0",  "0",  "0", "0",  "0",  "0"),
#'                 LIGHT03 = c("1", "96", "98", "1", "96", "98", "0", "96", "98"))
#'              )
#' fct_check_map(datalist = data, mapper = mapper )
fct_check_map <- function(datalist, mapper){

   ## Loop around the variables within mapper
   for ( i in 1:nrow(mapper[["variablemap"]]) ) {
     # i <- 1
     thisvar <-  mapper[["variablemap"]][["variable"]][[i]]
    if ( is.null(datalist[[mapper[["hierarchy"]] ]] [[ thisvar ]]) ) 
    {cli::cli_alert_info(paste0( thisvar ," standard variable was not found in the dataset.\n"))
      }
     else {
       ## If present check modalities
       mod <- mapper[["modalitymap"]] |>
         dplyr::filter( variable == thisvar ) |>
         dplyr::pull(standard)
      
      if( any(levels(as.factor(datalist[[mapper[["hierarchy"]] ]] [[ thisvar ]])) %in%  mod ) )
           { cat(paste0( thisvar ," is in the dataset and has at least one of the expected modality for calculation\n")) } else {
            cli::cli_alert_info(paste0( thisvar ,
                  " standard variable in the dataset misses at least one response among : ",
                                    mod))  }
     }
   }
}
