# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' fct_get_all_variable_names
#' 
#' Generate a map of all variables within the datalist obtained from RIDL - 
#'   standard Kobo extract in Excel
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @return dataframe with variables and list member names 
#' 
#' @importFrom purrr imap list_rbind
#' @importFrom tibble tibble as_tibble_col
#' @importFrom tidyr unnest
#' 
#' @export
#' @examples
#' data <- kobocruncher::kobo_data( here::here("data-raw", "data2.xlsx"))
#' varname <-   fct_get_all_variable_names(datalist = data)
#' head(varname, 10)
fct_get_all_variable_names <- function(datalist){
  
    dico <- purrr::imap(datalist,
       function(x, y) tibble::tibble(df = y,
                      vars = tibble::as_tibble_col(names(x))) |> 
         tidyr::unnest(vars)) |>
       purrr::list_rbind()
    
    return(dico)
    
}
