# WARNING - Generated by {fusen} from dev/utilities.Rmd: do not edit by hand

#' fct_var_mapping
#' 
#' Create a diff to identify the mapping between expected variables / modalities and 
#' what is has been configured in a specific xlsform
#' 
#' @param xlsformpath path to the xlsform
#' @param mappingfile_out path to file to out the mapping
#' 
#' @return a list with the best mapping...
#' 
#' @export
#' @examples
#'
#' form <- system.file("RMSCAPI.xlsx", package = "IndicatorCalc")
#' #fct_var_mapping(xlsformpath = form)
fct_var_mapping <- function(xlsformpath){
  
  IndicMap <- readxl::read_excel( system.file("IndicMap.xlsx", package = "IndicatorCalc"))
  dico <- kobocruncher::kobo_dico(xlsformpath)
  
  ## Map variable
  
  
  ## Map modalities
    
}
