# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' impact2_3
#' 
#' **Proportion of PoC with access to health services** 
#' 
#' This indicator measures access to primary health care services for persons 
#' of concern in need of health services.
#' 
#' Health services refers to preventive, pro-motive, curative, rehabilitative 
#' and palliative health services.
#' 
#' It is linked to SDG indicator [3.8.1](https://www.who.int/data/gho/data/themes/topics/service-coverage) 
#' on the coverage of essential health services.
#' 
#' The standard questions for this indicator are taken from UNHCR's [HAUS](https://www.unhcr.org/strategic-health-information.html) monitors trends
#'  in how refugees outside of camps access and utilize health services over time.
#'  Healthcare can be delivered through a combination of community level, mobile
#'   and fixed healthcare facilities.
#'   The number, type and location of each will vary by context.
#'   The standard questionnaire module will help us to understand these differences.
#'   
#'   | Standard Questions |
#'   |:------------------:|
#'   |  HACC01 - HACC04   |
#'   
#'   **Numerator**: Population who have received the asked for health services in the previous 30 days
#'   
#'   **Denominator**: Total population who have asked for health services in the previous 30 days
#'   
#'   **Formula**: *HACC01*=1 + / ((*HACC03*=1 & *HACC04*!=7,8,96) + *HACC01*=1)
#'   
#'   This indicator comes from the individual dataset 
#'   Calculate those who were not able to access due to reasons 
#'   unrelated to asked services (when HACC04 is 7 or 8 or 96)
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                                           
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' # datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#' #                                                  package = "IndicatorCalc"))
#' # ## Apply calculation
#' # datalist <- impact2_3(datalist )
#' # 
#' # ## Visualise value
#' # fct_plot_indic_donut(indicator = datalist[["ind"]]$impact2_3,
#' #                      iconunicode = "f140") 
#'
impact2_3 <- function(datalist ){
  
#   # Mapper , 
# mapper = list(
#            hierarchy = "ind",
#           variablemap = data.frame(
#             label = 
# c("1. During the past 30 days, has ${name_individual} consulted a health practitioner, dentist, traditional healer, or pharmacist, or visited a health center?", 
# "2. For what reason(s) did ${name_individual} seek consultation?", 
# "3. During the past 30 days, has ${name_individual} needed health services that’s/he could not have access to?", 
# "4. Why has ${name_individual} been unable to access a medical treatment in the past 30 days?"
# )
#               ,
#             variable =  
# c("HACC01", "HACC02", "HACC03", "HACC04")
#               ),
#           modalitymap = data.frame(
#             variable =  
# c("HACC01", "HACC01", "HACC02", "HACC02", "HACC02", "HACC02", 
# "HACC02", "HACC02", "HACC03", "HACC03", "HACC04", "HACC04", "HACC04", 
# "HACC04", "HACC04", "HACC04", "HACC04", "HACC04", "HACC04", "HACC04", 
# "HACC04")
#                ,
#             label =  
# c("Yes", "No", "Illness", "Injury", "General check-up (not for pregnancy)", 
# "Pre/Postnatal check-up", "Giving birth", "Other (Specify)", 
# "Yes", "No", "Lack of money", "No medical personnel available", 
# "Turned away because facility was full", "Turned away because facility was closed", 
# "Hospital/Clinic not having enough supplies or tests", "Health facility is too far", 
# "Fear of contracting a communicable disease (e.g. COVID-19)", 
# "Lockdown/Travel restrictions", "Too Far/transport issues", "Health facility is destroyed", 
# "Other (Specify)")
#                ,
#             standard =  
# c("1", "0", "1", "2", "3", "4", "5", "96", "1", "0", "1", "2", 
# "3", "4", "5", "6", "7", "8", "9", "10", "96")
#               ))
#   ## So first we check that we have what we need in the data set based on the mapper
#   check_map <- fct_check_map(datalist = datalist,
#                              mapper = mapper)
#   if ( check_map == FALSE) {
#    cat( "There are missing data requirement to calculate Indicator Impact 2.3")
#   } else {
#  
#  
#   datalist[["ind"]]$health_NOacc <- dplyr::case_when(
#     as.integer(datalist[["ind"]]$HACC03) ==  1 & 
#       (as.integer(datalist[["ind"]]$HACC04_7) ==  1 | 
#        as.integer(datalist[["ind"]]$HACC04_8) ==  1 | 
#        as.integer(datalist[["ind"]]$HACC04_96) ==  1 ) ~  0,
#     
#     as.integer(datalist[["ind"]]$HACC03) ==  1 & 
#      (as.integer(datalist[["ind"]]$HACC04_1) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_2) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_3) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_4) ==  1 |
#       as.integer(datalist[["ind"]]$HACC04_5) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_6) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_9) ==  1 | 
#       as.integer(datalist[["ind"]]$HACC04_10) ==  1) ~  1, 
#     
#     TRUE ~  0)
# # table(datalist[["ind"]]$health_NOacc, useNA = "ifany")
#  
# datalist[["ind"]]$health_NOacc <- as.numeric(datalist[["ind"]]$health_NOacc)
# datalist[["ind"]]$HACC01 <- as.numeric(datalist[["ind"]]$HACC01)
# 
# 
#  ## Add up who needed services ( both who accessed and did not access)
# datalist[["ind"]]$HACC_need <- datalist[["ind"]]$HACC01 + datalist[["ind"]]$health_NOacc
# 
# datalist[["ind"]]$impact2_3 <- datalist[["ind"]]$HACC01 / datalist[["ind"]]$HACC_need 
# 
# datalist[["ind"]]$impact2_3 <- dplyr::case_when(
#     datalist[["ind"]]$impact2_3 == 1   ~ 1, 
#     datalist[["ind"]]$impact2_3 == 0.5 ~ 0,
#     datalist[["ind"]]$impact2_3 == 0   ~ 0, 
#     TRUE ~ NA_real_ )
# 
# datalist[["ind"]]$impact2_3  <- labelled::labelled( datalist[["ind"]]$impact2_3,
#    labels =c( "Yes"=1,   "No"=0 ),
#    label = "Proportion of PoC with access to health services")
#    }
#    return(datalist)
}
