# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' impact3_3
#' 
#' **Proportion of population that feel safe walking alone in their neighbourhood**
#' 
#' This indicator measures the proportion of persons of concern who self-report 
#' feeling safe while walking alone in her/his neighborhood after dark.
#' It is linked to SDG indicator [16.1.4](https://unstats.un.org/sdgs/metadata/files/Metadata-16-01-04.pdf).
#' 
#' The standard module for this indicator is taken from SGD indicator owner UNODC.
#' This indicator only pertains to self-reported feeling of 'safety' and not 
#' 'security' since security is associated with additional external factors.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       SAF01        |
#' 
#' **Numerator**: Population who self-report feeling safe walking alone in 
#' their neighborhood after dark
#' 
#' **Denominator**: Total population
#' **Formula**: *SAF01*=1,2 / *SAF01*=1,2,3,4
#' 
#' This indicator comes from main dataset based on the respondent randomly
#'  selected for individual level
#'  
#'  if unsafe or very unsafe 0, 98 and 99 go into blank
#'  I never walk alone will also go into blank if any
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply calculation
#' datalist <- impact3_3(datalist)
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$impact3_3,
#'                      iconunicode = "f140")   
impact3_3 <- function(datalist ){
  
  # Mapper 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
"1. How safe does ${name_selectedadult18} feel walking alone in your area/neighbourhood after dark?"
              ,
            variable =  
"SAF01"
              ),
          modalitymap = data.frame(
            variable =  
c("SAF01", "SAF01", "SAF01", "SAF01", "SAF01", "SAF01")
               ,
            label =  
c("Very safe", "Fairly safe", "Bit unsafe", "Very unsafe", "Don\u2019t know", 
"Prefer not to respond")
               ,
            standard =  
c("1", "2", "3", "4", "98", "99")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 3.3")
  } else {
  
datalist[["main"]]$impact3_3 <- dplyr::case_when(
     as.integer(datalist[["main"]]$SAF01) == 1 | 
     as.integer(datalist[["main"]]$SAF01) == 2 ~ 1,
     as.integer(datalist[["main"]]$SAF01) == 3 | 
     as.integer(datalist[["main"]]$SAF01) == 4 ~ 0 , 
     as.integer(datalist[["main"]]$SAF01) == 98 | 
     as.integer(datalist[["main"]]$SAF01) == 99 ~ NA_real_) 

datalist[["main"]]$impact3_3  <- labelled::labelled(datalist[["main"]]$impact3_3,
   labels = c('Yes' = 1, 'No' = 0 ),
   label = "Proportion of population that feel safe walking alone in their neighbourhood") 

   }
   return(datalist)
}
