# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' impact3_2b
#' 
#' **Proportion of Persons of Concern enrolled in secondary education**
#' 
#' This indicator measures the number of students enrolled in secondary education,
#'  regardless of age, expressed as a percentage of the official school-age population
#'   corresponding to the respective same level of education.
#'   
#'   This is also referred to as Gross enrollment rate (GER).
#'   It is linked to SGD indicator 4.1.1 on quality education.
#'   
#'   The standard questions for this indicator are taken from UNHCR's [Standardized Education Module](https://www.unhcr.org/60804b214.pdf) which are adapted primarily from 
#'   the IHSN/EPDC and MICS indicator and questionnaire frameworks.
#'   
#'   Definitions:
#'   
#'   1.  "Enrollment" refers individuals officially registered in a primary/secondary school education programme.
#'   
#'   2.  "Secondary education" provides learning and educational activities building on primary education and preparing for both first labour market entry as well as further study.
#'   
#'   The common duration is 6 years and is often divided between lower and upper secondary education (corresponding respectively to ISCED 2 and 3).
#'   
#'   3.  "Secondary school age" depends on the education system and differ from 
#'   country to country. 
#'   Children typically enter secondary education between age 11 and 13 and leave between age 17-19.
#'   
#'   4.  Whenever possible, operations are encouraged also to disaggregate data between lower and upper secondary
#'   
#'   | Standard Questions |
#'   |:------------------:|
#'   |    EDU01-EDU04     |
#'   
#'   **Numerator**: Population enrolled in secondary education (regardless of age)
#'   **Denominator**: Total secondary school age population (to be adjusted by the country for enumeration)
#'   
#'   **Formula**: (*EDU01*=1 & *EDU02*=1 & (*EDU03*=3,4) / Number of children aged from 11 to 18
#'   
#'   This indicator comes from the individual dataset
#'   
#'   Include if they are attending secondary or secondary -technical and vocational
#'    
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply calculation
#' datalist <- impact3_2b(datalist )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$impact3_2b,
#'                      iconunicode = "f140")  
#'  
impact3_2b <- function(datalist ){
  # mapper , 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. Has ${child_edu_name} ever attended school?", "2. Did ${child_edu_name} attend school or pre-school at any time during current school year?", 
"3. During this/that school year , what level is (was) ${child_edu_name} attending?", 
"4. What type of school?", "6. Can you estimate how old is ${HH02}?"
)
              ,
            variable =  
c("EDU01", "EDU02", "EDU03", "EDU04", "HH07")
              ),
          modalitymap = data.frame(
            variable =  
c("EDU01", "EDU01", "EDU02", "EDU02", "EDU03", "EDU03", "EDU03", 
"EDU03", "EDU03", "EDU03", "EDU03", "EDU04", "EDU04", "EDU04", 
"EDU04", "EDU04", "EDU04", "EDU04", "HH07")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Early Childhood Education or Pre-primary", 
"Primary", "Secondary", "Secondary - Technical and Vocational Education and Training (TVET)", 
"Post-secondary - Technical and Vocational Education and Training (TVET)", 
"Tertiary", "Don’t know", "Government or public", "UN or NGO (non-governmental organization)", 
"Religious or faith-based organization", "Community", "Private", 
"Other (specify)", "Don’t know", NA)
               ,
            standard =  
c("1", "0", "1", "0", "1", "2", "3", "4", "5", "6", "98", "1", 
"2", "3", "4", "5", "96", "98", NA)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 3.2.b")
  } else {
  
datalist[["ind"]]$edu_secondary<- dplyr::case_when(
    as.integer(datalist[["ind"]]$EDU01) == 1 & 
    as.integer(datalist[["ind"]]$EDU02) == 1 & 
     ( as.integer(datalist[["ind"]]$EDU03) == 3 | 
       as.integer(datalist[["ind"]]$EDU03) == 4) ~ 1, 
    
    as.integer(datalist[["ind"]]$EDU01) == 0 | 
    as.integer(datalist[["ind"]]$EDU02) == 0 ~ 0, 
    TRUE ~ 0)


#Adjust age group for secondary school enrollment 
##calculated as 11 to 18 above  --> put as function variable...

datalist[["ind"]]$age_secondary<- dplyr::case_when(
    as.integer(datalist[["ind"]]$HH07) >= 11 & 
    as.integer(datalist[["ind"]]$HH07) <= 18 ~ 1, 
    TRUE ~ NA_real_)
    
datalist[["ind"]]$impact3_2b <- sum(datalist[["ind"]]$edu_secondary, na.rm= TRUE) / 
                                sum(datalist[["ind"]]$age_secondary, na.rm = TRUE)

datalist[["ind"]]$impact3_2b  <- labelled::labelled(datalist[["ind"]]$impact3_2b,
                            labels = c('Yes' = 1, 'No' = 0 ),
  label = "Proportion of persons of concern enrolled in secondary education")

   }
   return(datalist)
}
