# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' impact_2_2
#' 
#' **Proportion of Persons of Concern residing in physically safe and secure 
#' settlements with access to basic facilities**
#' 
#' Once electricity, healthcare, drinking water and adequate shelter are
#'  calculated, check the values for each variable before, 
#'  calculating 2.2 impact indicator. 
#'  
#'  
#' ---------
#' # inter_electricity
#' 
#'  Households lighting provides a sense of safety and security within and outside 
#'  the households after sunset.
#'  
#'  If households lack access to electricity, especially for lighting and 
#'  connectivity, this affects the occupants' security and limits their 
#'  opportunities for socialization, learning and self-reliance.
#'  
#'  **Numerator**: Population with access to electricity, especially for lighting 
#'  and connectivity
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: *LIGHT01* = 1 & *LIGHT03* != 1, 96, 98
#'  
#' ---------
#' # inter_healthcare
#' 
#' Access to healthcare depends on availability of healthcare, including physical 
#' reach, acceptability and affordability for all.
#' For this indicator, the focus is on the availability of healthcare system.
#' According to [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf),
#'  primary healthcare facility should be accessible within one hour's walk from dwellings.
#'  **Numerator**: Population that can reach a primary healthcare facility within one hour from dwellings
#'  **Denominator**: Total population
#'  **Formula**: *HEA01* != 96, 98 & *HEA03* <= 60 
#'  (reachable within one hour/60 minutes)
#'  
#'  
#' ---------
#' # inter_drinkingwater
#' 
#' Access to clean drinking water is essential for a person's survival and well 
#' being and a precursor for achieving protection outcomes related to health, 
#' education and economic developed.
#' The calculation for access drinking water is linked to SGD Indicator
#'  [6.1.1](https://unstats.un.org/sdgs/metadata/files/Metadata-06-01-01.pdf).
#'  The questionnaire module and the analysis guidance is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis).
#'  
#'  **Numerator**: Population using improved sources of drinking water either in their dwelling/yard/plot or within 30 minutes round trip collection time
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: 
#'   *DWA03* < 30 (under 30 minutes), &
#'   *DWA01* != 7,9,13,96,98 &
#'   *DWA02* != 3
#'   
#'  This basic service is calculated from the main dataset
#'  There are three conditions as below  improved source, 
#'  in dwelling/yard/plot and reachable under 30 minutes 
#'  
#'  
#' ---------
#'  # inter_shelter
#' 
#' The right to access adequate housing is protected by international law.
#' The concept of "adequacy" means that housing is more than four walls and a 
#' roof as indicated in [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf).
#' Habitable housing primarily refers to the fact that the housing should provide
#'  protection from cold, damp, heat, rain, wind, and other threats to health,
#'   structural hazards, and disease vectors and it should not be overcrowded.
#'   As shelter/housing is primarily a contextual element, there may be 
#'   discrepancies from country to country on how this data is measured.
#'   
#'   Adequate shelter is measured based on having improved material for the
#'    dwelling as indicated in [DHS](https://dhsprogram.com/pubs/pdf/AS61/AS61.pdf) 
#'    publication on housing conditions which is also used by [MICS6](https://mics.unicef.org/tools).
#'    
#'    Overcrowding is also used which occurs if there are more than three people
#'     per habitable room as defined by [UN-Habitat](https://www.ncbi.nlm.nih.gov/books/NBK535289/table/ch3.tab2/).
#'     
#'     **Numerator**: Population that have access to adequate housing
#'     **Denominator**: Total population
#'     
#' **Formula**: 
#' 
#'      *DWE01* = 1,2 &
#'      *DWE02* = 3,4,5,6,7,8,9 & 
#'      *DWE03* = 8,9,10,11,12,13 & 
#'      *DWE04* = 10,11,12,13,14,15 & 
#'      crowding (*HH01*/*DWE05*) \<= 3
#' 
#' Adequate shelter is calculated from the main dataset
#' classify as habitable when improved/adequate shelter
#' 
#'  
#'  
#' ---------
#' # Compile alll
#'  Once all variables are correctly calculated, we can compute the final 
#'  variable for impact 2.2 indicator.
#'  **Numerator**: Population residing in physically safe and secure settlements with access to basic facilities
#'  **Denominator**: Total population
#'  **Formula**: *shelter*=1 & *electricity*=1 & *healthcare*=1 & *drinkingwater*=1
#'  
#'  Impact 2.2 is "1" if all services above are accessible
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                                           
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply calculation
#' datalist <-  impact_2_2(datalist)
#'
#' table(datalist[["main"]]$impact2_2, useNA = "ifany")
#'
#' fct_plot_indic_donut(indicator = datalist[["main"]]$impact2_2,
#'                      iconunicode = "f140") 
#'
#'
#' ## Can get the details as well
#'
#' table(datalist[["main"]]$electricity, useNA = "ifany")
#' fct_plot_indic_donut(indicator = datalist[["main"]]$electricity,
#'                      iconunicode = "f0e7") 
#'
#' table(datalist[["main"]]$healthcare, useNA = "ifany")
#' fct_plot_indic_donut(indicator = datalist[["main"]]$healthcare,
#'                      iconunicode = "f479") 
#'
#'  
#' table(datalist[["main"]]$drinkingwater, useNA = "ifany")
#' fct_plot_indic_donut(indicator = datalist[["main"]]$drinkingwater,
#'                      iconunicode = "e006") 
#'
#' ## Check intermediary variables
#' table(datalist[["main"]]$dwa_cond1, useNA = "ifany")
#' table(datalist[["main"]]$reachableU30, useNA = "ifany")
#' table(datalist[["main"]]$DWA02, useNA = "ifany")
#' table(datalist[["main"]]$dwa_cond2, useNA = "ifany")
#'
#' # Tabulate
#' table(datalist[["main"]]$dwe01_cat, useNA = "ifany")
#' table(datalist[["main"]]$dwe02_cat, useNA = "ifany")
#' table(datalist[["main"]]$dwe03_cat, useNA = "ifany")
#' table(datalist[["main"]]$dwe04_cat, useNA = "ifany")
#' table(datalist[["main"]]$dwe05_cat, useNA = "ifany")
#' table(datalist[["main"]]$shelter, useNA = "ifany")
#' #plot
#' fct_plot_indic_donut(datalist[["main"]]$shelter,
#'                      iconunicode = "e54f") 
#'
impact_2_2 <- function(datalist ){
  
  ## Mapper 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. When anyone in your household is sick, where do they go to seek care?", 
"2. How do you reach this facility if you need to seek care?", 
"3. How long does it take to go there when you use the mode of transport that you mentioned above?", 
"4. Does this household use anything for lighting?", "5. What does this household use most of the time as energy for lighting, or as a light source?", 
"6. What source of electricity is used most of the time in this household?", 
"1. What is the main source of drinking water for this household?", 
"2. Where is this ${source} - ${source2} located?", "Unit", "Time", 
"4. In the last 30 days, has there been any time when your household did not have sufficient quantities of drinking water when needed?", 
"1.What type of dwelling does the household live in?", "2. Main material of the dwelling floor", 
"3. Main material of the roof.", "4. Main material of the exterior walls", 
"5. How many separate rooms do the members of your household occupy?", 
"8. Does your household pay any rent?", "9. Can your household generally afford to pay the rent without any major financial distress?", 
"What is the total number of persons in this household ? (including the respondent)"
)
              ,
            variable =  
c("HEA01", "HEA02", "HEA03", "LIGHT01", "LIGHT02", "LIGHT03", 
"DWA01", "DWA02", "DWA03a", "DWA03b", "DWA04", "DWE01", "DWE02", 
"DWE03", "DWE04", "DWE05", "DWE08", "DWE09", "HH01")
              ),
          modalitymap = data.frame(
            variable =  
c("HEA01", "HEA01", "HEA01", "HEA01", "HEA01", "HEA01", "HEA01", 
"HEA02", "HEA02", "HEA02", "HEA02", "HEA03", "LIGHT01", "LIGHT01", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", 
"LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA02", "DWA02", "DWA02", 
"DWA03a", "DWA03a", "DWA03b", "DWA04", "DWA04", "DWE01", "DWE01", 
"DWE01", "DWE01", "DWE01", "DWE01", "DWE01", "DWE01", "DWE01", 
"DWE01", "DWE02", "DWE02", "DWE02", "DWE02", "DWE02", "DWE02", 
"DWE02", "DWE02", "DWE02", "DWE02", "DWE03", "DWE03", "DWE03", 
"DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", "DWE03", 
"DWE03", "DWE03", "DWE03", "DWE03", "DWE04", "DWE04", "DWE04", 
"DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", 
"DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE04", "DWE05", 
"DWE08", "DWE08", "DWE09", "DWE09", "DWE09", "DWE09", "HH01")
               ,
            label =  
c("NGO facility (charity, faith-based organization)", "UNHCR Health Partner (Caritas, Save the Children)", 
"Public Clinics / Hospitals", "Private Clinics / Hospitals", 
"Pharmacy", "Other, specify", "Don't know", "By walk", "Private car", 
"Public transport (bus, boat)", "Other, specify", NA, "Yes", 
"No", "Electricity (including solar mini-grids, hybrid mini-grids and national grid)", 
"Electricity (from diesel generator)", "Solar home system", "Solar-powered lantern or flashlight", 
"Rechargeable flashlight, mobile, torch or lantern", "Battery powered flashlight, torch or lantern", 
"Biogas lamp", "LPG lamp", "Gasoline lamp", "Kerosene or paraffin lamp", 
"Oil lamp", "Candle", "Open fire", "Other, specify", "No electricity in household", 
"National grid connection from [COMPANY]", "Local mini grid", 
"Solar home system", "Solar lantern", "Electric generator", "Rechargeable battery", 
"Dry cell battery / torch", "Other, specify", "Don't know", "Piped Into Dwelling", 
"Piped Into Yard/Plot", "Piped To Neighbor", "Public Tap/Standpipe", 
"Tube Well/Borehole", "Protected Dug Well", "Unprotected Dug Well", 
"Protected Spring", "Unprotected Spring", "Rain Water Collection", 
"Tanker Truck/Water Vendor", "Cart With Small Tank/Drum", "Surface Water (River, Stream, Pond, Dam, Canal)", 
"Bottled Water", "Sachet Water", "Water Kiosk", "Other (Specify)", 
"Don't Know", "In Own Dwelling", "In Own Yard/Plot", "Elsewhere", 
"Minutes", "Hours", NA, "Yes", "No", "Apartment", "House", "Tent", 
"Caravan", "Collective Center", "Worksite/Unfinished Home/ Abandoned Building", 
"Farm Building", "School, mosque, church or other religious building", 
"Garage, shop, workshop, or other structure not meant as residential space", 
"Other (Specify)", "Earth/sand", "Dung", "Wood planks", "Palm/bamboo", 
"Parquet or polished wood", "Vinyl or asphalt strips", "Ceramic tiles", 
"Cement", "Carpet", "Other (Specify)", "No roof", "Thatch/Palm leaf", 
"Sod", "Rustic mat", "Palm/bamboo", "Wood planks", "Cardboard", 
"Metal/tin", "Wood", "Calamine/Cement fibre", "Ceramic tiles", 
"Cement", "Roofing shingles", "Other (Specify)", "No walls", 
"Cane/Palm/ Trunks", "Dirt", "Bamboo with mud", "Stone with mud", 
"Uncovered adobe", "Plywood", "Cardboard", "Reused wood", "Cement", 
"Stone with lime/ cement", "Bricks", "Cement blocks", "Covered adobe", 
"Wood planks/shingles", "Other (Specify)", NA, "Yes", "No", "Always", 
"Often", "Sometimes", "Never", NA)
               ,
            standard =  
c("1", "2", "3", "4", "5", "96", "98", "1", "2", "3", "96", NA, 
"1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "96", "1", "2", "3", "4", "5", "6", "7", "8", 
"96", "98", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "14", "15", "16", "96", "98", "1", "2", "3", 
"1", "2", NA, "1", "0", "1", "2", "3", "4", "5", "6", "7", "8", 
"9", "96", "1", "2", "3", "4", "5", "6", "7", "8", "9", "96", 
"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 
"13", "96", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "14", "15", "96", NA, "1", "0", "1", "2", "3", 
"4", NA)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Impact 2.2")
  } else {

    ## now pull the calculation...
  
  ## Electricity ########
  datalist[["main"]]$electricity <-  dplyr::case_when(
    datalist[["main"]]$LIGHT01 == 1 & 
                       (as.integer(datalist[["main"]]$LIGHT03) != 1 | 
                        as.integer(datalist[["main"]]$LIGHT03)!= 96 |
                        as.integer(datalist[["main"]]$LIGHT03) != 98)  ~ 1, 
                     TRUE ~ 0 )
 
  datalist[["main"]]$electricity <- labelled::labelled(  
                            datalist[["main"]]$electricity,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                 label = "Access to electricity")
  ## healthcare ########
  datalist[["main"]]$healthcare <- 
           dplyr::case_when((
             as.integer(datalist[["main"]]$HEA01) != 96 | 
             as.integer(datalist[["main"]]$HEA01) != 98) & 
             as.integer(datalist[["main"]]$HEA03) <= 60 ~ 1,
                     TRUE ~ 0)

  datalist[["main"]]$healthcare <- labelled::labelled(datalist[["main"]]$healthcare,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                label = "Access to healthcare facility")

  ## Drinking Water #################
  datalist[["main"]]$time_DWA <-  dplyr::case_when(
    as.integer(datalist[["main"]]$DWA03a) == 1 ~ 1, 
    as.integer(datalist[["main"]]$DWA03a) == 2 ~ 60) 
  #convert hour into minutes
  # datalist[["main"]]$time_DWA <- as.numeric(datalist[["main"]]$time_DWA)
  datalist[["main"]]$time_tot <- datalist[["main"]]$time_DWA * 
      as.numeric(datalist[["main"]]$DWA03b)
  
  datalist[["main"]]$reachableU30 <-  dplyr::case_when( 
    datalist[["main"]]$time_tot > 30 ~  0, 
                                TRUE ~ 1) 
  # reachable under 30 minutes
  datalist[["main"]]$dwa_cond1 <-  dplyr::case_when(
    as.integer(datalist[["main"]]$DWA01) != 7 |
    as.integer(datalist[["main"]]$DWA01) != 9 |
    as.integer(datalist[["main"]]$DWA01) !=  13 | 
    as.integer(datalist[["main"]]$DWA01) !=  96 |
    as.integer(datalist[["main"]]$DWA01) !=  98 ~ 1,
                               TRUE ~ 0) 
  # improved source
  datalist[["main"]]$dwa_cond2 <- dplyr::case_when( 
    
    #UNDER30 MIN
    as.integer(datalist[["main"]]$reachableU30) == 1 & 
    as.integer(datalist[["main"]]$DWA02) == 3 ~ 1, 
    
    # NOT UNDER30 MIN
    as.integer(datalist[["main"]]$reachableU30) == 0 & 
    as.integer(datalist[["main"]]$DWA02) == 3 ~ 0, 
    
    # in the dwelling/yard/plot
    as.integer(datalist[["main"]]$DWA02) == 1 | 
    as.integer(datalist[["main"]]$DWA02) == 2 ~ 1, 
      TRUE ~ NA ) 
  
  datalist[["main"]]$drinkingwater <- dplyr::case_when(
      (as.integer(datalist[["main"]]$dwa_cond1) == 1 & 
        as.integer(datalist[["main"]]$dwa_cond2) == 1 ) ~ 1, 
      TRUE ~ 0)
  
  datalist[["main"]]$drinkingwater <- labelled::labelled(datalist[["main"]]$drinkingwater,
                              labels = c('Yes' = 1, 'No' = 0 ),
                                    label = "Access to drinking water")
  
  
  ## shelter #########
  #Only apartment and house
  datalist[["main"]]$dwe01_cat <- 
    dplyr::case_when(
      ( as.integer(datalist[["main"]]$DWE01) == 1 | 
        as.integer(datalist[["main"]]$DWE01) == 2) ~ 1, 
      TRUE ~ 0 )
  ## unimproved floor when earth,sand,clay,mud, dung or other
  datalist[["main"]]$dwe02_cat<- dplyr::case_when( 
      (as.integer(datalist[["main"]]$DWE02) == 1 | 
       as.integer(datalist[["main"]]$DWE02) == 2 | 
       as.integer(datalist[["main"]]$DWE02) == 96) ~ 0, 
      TRUE ~ 1 )
  ## unimproved roof all options except metal,wood,ceramic tiles, cement, roofing shingles/sheets
  datalist[["main"]]$dwe03_cat<- dplyr::case_when( 
      (as.integer(datalist[["main"]]$DWE03) == 8 |
       as.integer(datalist[["main"]]$DWE03) == 9 | 
       as.integer(datalist[["main"]]$DWE03) == 10 | 
       as.integer(datalist[["main"]]$DWE03) == 11 |
       as.integer(datalist[["main"]]$DWE03) == 12 | 
       as.integer(datalist[["main"]]$DWE03) == 13 ) ~ 1 , 
      TRUE ~ 0)
  
  ## improved wall: cement,stone,bricks,cement blocks, covered adobe, wood planks
  datalist[["main"]]$dwe04_cat<- dplyr::case_when( 
      (as.integer(datalist[["main"]]$DWE04) == 10| 
      as.integer(datalist[["main"]]$DWE04) == 11 | 
      as.integer(datalist[["main"]]$DWE04) == 12 | 
      as.integer(datalist[["main"]]$DWE04) == 13 | 
      as.integer(datalist[["main"]]$DWE04) == 14 | 
      as.integer(datalist[["main"]]$DWE04) == 15 ) ~ 1,
      TRUE ~ 0)
  
  ## Calculate crowding index - overcrowded when more than 3 persons
  datalist[["main"]]$crowding <- as.numeric(datalist[["main"]]$HH01) / 
       as.numeric(datalist[["main"]]$DWE05)
  
  datalist[["main"]]$dwe05_cat<- dplyr::case_when( ##if crowding <= 3, not overcrowded 
      datalist[["main"]]$crowding <= 3 ~ 1, 
      TRUE ~ 0)
  
  ####Calculate if all 5 conditions are met for adequate shelter
  ##dwe01_cat / dwe02_cat / dwe03_cat / dwe04_cat / dwe05_cat
  
  datalist[["main"]]$shelter<- dplyr::case_when(
      as.integer(datalist[["main"]]$dwe01_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe02_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe03_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe04_cat) == 0 | 
      as.integer(datalist[["main"]]$dwe05_cat) == 0  ~  0, 
      
      as.integer(datalist[["main"]]$dwe01_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe02_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe03_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe04_cat)  == 1 & 
      as.integer(datalist[["main"]]$dwe05_cat)  == 1 ~  1)
  
  datalist[["main"]]$shelter <- labelled::labelled(  datalist[["main"]]$shelter,
                              labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Access to adequate shelter") 

  ## Compile alll ####
datalist[["main"]]$impact2_2 <- dplyr::case_when(
    as.integer(datalist[["main"]]$shelter) == 0 | 
    as.integer(datalist[["main"]]$electricity) == 0 | 
    as.integer(datalist[["main"]]$drinkingwater) == 0 | 
    as.integer(datalist[["main"]]$healthcare) == 0 ~  0,
    
    as.integer(datalist[["main"]]$shelter) == 1 & 
    as.integer(datalist[["main"]]$electricity) == 1 & 
    as.integer(datalist[["main"]]$drinkingwater) == 1 & 
    as.integer(datalist[["main"]]$healthcare) == 1 ~  1)

datalist[["main"]]$impact2_2 <- labelled::labelled(
  datalist[["main"]]$impact2_2,
                            labels =c(
                              "Yes" = 1,
                              "No" = 0
                            ),
    label = "Proportion of PoCs residing in physically safe and secure settlements with access to basic facilities") 

  }
  return(datalist)
}
