# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' inter_healthcare
#' 
#' Access to healthcare depends on availability of healthcare, including physical 
#' reach, acceptability and affordability for all.
#' For this indicator, the focus is on the availability of healthcare system.
#' According to [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf),
#'  primary healthcare facility should be accessible within one hour's walk from dwellings.
#'  **Numerator**: Population that can reach a primary healthcare facility within one hour from dwellings
#'  **Denominator**: Total population
#'  **Formula**: *HEA01* != 96, 98 & *HEA03* <= 60 
#'  (reachable within one hour/60 minutes)
#' 
#'  
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                    
#' @param mapper a list providing the mapping of the variables used for the 
#' calculation - this mapper is potentially to be adjusted in relation with deviation
#' between the the standard XlsForm and the contextualized dataset
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' @importFrom cli cli_alert_info
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' 
#' @examples
#' datalist <- kobocruncher::kobo_data( system.file("test.xlsx",
#'                                                  package = "IndicatorCalc"))
#'
#' mapper <-  list(
#'             hierarchy = "main",
#'             variablemap = data.frame(
#'               label = c(
#' "In general, when anyone in your household is sick, where do they go to seek care?",
#' "How long it takes to go there when you use the mode of transport mentioned above?"),
#'               variable = c("HEA01", 
#'                            "HEA03"),
#'               mappattern = c("HEA01", 
#'                            "HEA03") ),
#'             modalitymap = data.frame(
#'               variable = c( "HEA01", "HEA01" ),
#'               label = c(  "Other, specify", "Don't know"),
#'               standard = c("96", "98" ),
#'               map = c("96", "98" )))
#'
#' datalist <- inter_healthcare(datalist, mapper )
#'
#' table(datalist[["main"]]$healthcare)
#' fct_plot_indic_donut(indicator = datalist[["main"]]$healthcare,
#'                      iconunicode = "f479") 
#'
inter_healthcare <- function(datalist, 
         mapper = list(
            hierarchy = "main",
            variablemap = data.frame(
              label = c(
  "In general, when anyone in your household is sick,  where do they go to seek care?",
  "How long does it take to go there when you use the mode of transport that you mentioned above?"),
              variable = c("HEA01", 
                           "HEA03"),
              mappattern = c("HEA01", 
                           "HEA03") ),
            modalitymap = data.frame(
              variable = c( "HEA01", "HEA01" ),
              label = c(  "Other, specify", "Don't know"),
              standard = c("96", "98" ),
              map = c("96", "98" ))) ){
  
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  #if (check_map == FALSE) {
    datalist <- fct_re_map(datalist = datalist,
                              mapper = mapper)
  #}
  

datalist[["main"]]$healthcare <- 
           dplyr::case_when((datalist[["main"]]$HEA01!="96" | 
                               datalist[["main"]]$HEA01!="98") & 
                              datalist[["main"]]$HEA03 <= 60 ~ "1",
                     TRUE ~ "0")

datalist[["main"]]$healthcare = labelled::labelled(datalist[["main"]]$healthcare,
                                labels = c(
                                  "Yes" = "1",
                                  "No" = "0"),
                                label = "Access to healthcare facility")

return(datalist)
}
