# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' inter_drinkingwater
#' 
#' Access to clean drinking water is essential for a person's survival and well 
#' being and a precursor for achieving protection outcomes related to health, 
#' education and economic developed.
#' The calculation for access drinking water is linked to SGD Indicator
#'  [6.1.1](https://unstats.un.org/sdgs/metadata/files/Metadata-06-01-01.pdf).
#'  The questionnaire module and the analysis guidance is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis).
#'  
#'  **Numerator**: Population using improved sources of drinking water either in their dwelling/yard/plot or within 30 minutes round trip collection time
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: 
#'   *DWA03* < 30 (under 30 minutes), &
#'   *DWA01* != 7,9,13,96,98 &
#'   *DWA02* != 3
#'   
#'  This basic service is calculated from the main dataset
#'  There are three conditions as below  improved source, 
#'  in dwelling/yard/plot and reachable under 30 minutes 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                    
#' @param mapper a list providing the mapping of the variables used for the 
#' calculation - this mapper is potentially to be adjusted in relation with deviation
#' between the the standard XlsForm and the contextualized dataset
#' 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' datalist <- kobocruncher::kobo_data( system.file("test.xlsx",
#'                                                  package = "IndicatorCalc"))
#'
#' ## in the contextualised form - DWA03a has been skipped and all results are in min... 
#' ## only manual transformation can adjust this before we use the mapper..
#'
#' datalist[["main"]]$DWA03a  <- "1" 
#'
#' datalist[["main"]]$DWA03b <- 
#'   datalist[["main"]]$VulnerabilityScoring.BasicNeeds.DWA03
#'
#' # now the mapper
#' mapper <-  list(
#'             hierarchy = "main",
#'             variablemap = data.frame(
#'               label = c(
#'    "What is the main source of drinking water for this household?",
#'   "Where is this source located?",
#'   "Unit used to measure time to access",
#'   "How long does it take to go there, wait get water, and come back?"),
#'               variable = c("DWA01", 
#'                            "DWA02", 
#'                            "DWA03a", 
#'                            "DWA03b" ),
#'               mappattern = c("DWA01", 
#'                            "DWA02", 
#'                            "DWA03a", 
#'                            "DWA03b" ) ),
#'             modalitymap = data.frame(
#'              variable = c("DWA01",  "DWA01", "DWA01","DWA01",  "DWA01", 
#'                    "DWA02","DWA02", "DWA02",
#'                    "DWA03a","DWA03a"),
#'              label = c( 
#'                 ##DWA01
#'                 "Unprotected Dug Well", 
#'                 "Unprotected Spring",
#'                 "Surface Water (River, Stream, Pond, Dam, Canal)",
#'                 "Other, specify",
#'                 "Don't know",
#'                 ##DWA02
#'                 "In Own Dwelling", 
#'                 "In Own Yard/Plot",
#'                 "Elsewhere",
#'                 ## DWA03a
#'                 "Minutes", 
#'                 "Hours"    ),
#'              standard = c( "7", "9", "13", "96", "98",
#'                            "1", "2", "3",
#'                            "1", "2"),
#'              map = c( "7", "9", "13", "96", "98",
#'                        "1", "2", "3",
#'                         "1", "2") ) 
#'          )
#'   
#' datalist <- inter_drinkingwater(datalist, mapper )
#'
#' ## Indicator summary
#' table(datalist[["main"]]$drinkingwater, useNA = "ifany")
#' fct_plot_indic_donut(indicator = datalist[["main"]]$drinkingwater,
#'                      iconunicode = "e006") 
#'
#' ## Check auxilliary
#' table(datalist[["main"]]$dwa_cond1, useNA = "ifany")
#' table(datalist[["main"]]$reachableU30, useNA = "ifany")
#' table(datalist[["main"]]$DWA02, useNA = "ifany")
#' table(datalist[["main"]]$dwa_cond2, useNA = "ifany")
inter_drinkingwater <- function(
        datalist, 
         mapper = list(
            hierarchy = "main",
            variablemap = data.frame(
              label = c(
                "What is the main source of drinking water for this household?",
                "Where is this source located?",
                "Unit used to measure time to access",
                "How long does it take to go there, get water, and come back,
                  including waiting time?"),
              variable = c("DWA01", 
                           "DWA02", 
                           "DWA03a", 
                           "DWA03b" ),
              mappattern = c("DWA01", 
                           "DWA02", 
                           "DWA03a", 
                           "DWA03b" ) ),
             modalitymap = data.frame(
             variable = c("DWA01", 
                          "DWA01", 
                          "DWA01", 
                          "DWA01", 
                          "DWA01", 
                           "DWA02",
                           "DWA02",
                           "DWA02",
                           "DWA03a",
                           "DWA03a"),
              label = c( 
                ##DWA01
                "Unprotected Dug Well", 
                "Unprotected Spring",
                "Surface Water (River, Stream, Pond, Dam, Canal)",
                "Other, specify",
                "Don't know",
                ##DWA02
                "In Own Dwelling", 
                "In Own Yard/Plot",
                "Elsewhere",
                ## DWA03
                "Minutes", "Hours" ),
              standard = c( "7", "9", "13", "96", "98",
                           "1", "2", "3",
                           "1", "2"),
              map = c( "7", "9", "13", "96", "98",
                       "1", "2", "3",
                        "1", "2"))) 
         ){
  
    ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
 # if (check_map == FALSE) {
    datalist <- fct_re_map(datalist = datalist,
                              mapper = mapper)
 # }
  
datalist[["main"]]$time_DWA <-  dplyr::case_when(
    datalist[["main"]]$DWA03a=="1"~ 1, 
    datalist[["main"]]$DWA03a=="2"~ 60) #convert hour into minutes
# datalist[["main"]]$time_DWA <- as.numeric(datalist[["main"]]$time_DWA)

datalist[["main"]]$time_tot <- datalist[["main"]]$time_DWA * 
    as.numeric(datalist[["main"]]$DWA03b)

datalist[["main"]]$reachableU30 <-  dplyr::case_when( 
  datalist[["main"]]$time_tot > 30 ~ "0", 
                              TRUE ~ "1") # reachable under 30 minutes

datalist[["main"]]$dwa_cond1 <-  dplyr::case_when(
  datalist[["main"]]$DWA01!="7" |
  datalist[["main"]]$DWA01 !="9" |
  datalist[["main"]]$DWA01 != "13" | 
  datalist[["main"]]$DWA01 != "96" |
  datalist[["main"]]$DWA01 !="98" ~ "1",
                             TRUE ~ "0") # improved source

datalist[["main"]]$dwa_cond2= dplyr::case_when( 
  
  #UNDER30 MIN
  datalist[["main"]]$reachableU30 == "1" & 
  datalist[["main"]]$DWA02 == "3" ~ "1", 
  
  # NOT UNDER30 MIN
  datalist[["main"]]$reachableU30 == "0" & 
  datalist[["main"]]$DWA02 == "3" ~ "0", 
  
  # in the dwelling/yard/plot
  datalist[["main"]]$DWA02 == "1" | 
  datalist[["main"]]$DWA02 == "2" ~ "1", 
    TRUE ~ NA_character_ ) 

datalist[["main"]]$drinkingwater <- dplyr::case_when(
    (datalist[["main"]]$dwa_cond1 == "1" & 
      datalist[["main"]]$dwa_cond2 == "1" ) ~ "1", 
    TRUE ~ "0")

datalist[["main"]]$drinkingwater = labelled::labelled(datalist[["main"]]$drinkingwater,
                                  labels = c(
                                    "Yes" = "1",
                                    "No" = "0"
                                  ),
                                  label = "Access to drinking water")
    return(datalist)
}
