# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' inter_shelter
#' 
#' The right to access adequate housing is protected by international law.
#' The concept of "adequacy" means that housing is more than four walls and a 
#' roof as indicated in [The Sphere Handbook](https://spherestandards.org/wp-content/uploads/Sphere-Handbook-2018-EN.pdf).
#' Habitable housing primarily refers to the fact that the housing should provide
#'  protection from cold, damp, heat, rain, wind, and other threats to health,
#'   structural hazards, and disease vectors and it should not be overcrowded.
#'   As shelter/housing is primarily a contextual element, there may be 
#'   discrepancies from country to country on how this data is measured.
#'   
#'   Adequate shelter is measured based on having improved material for the
#'    dwelling as indicated in [DHS](https://dhsprogram.com/pubs/pdf/AS61/AS61.pdf) 
#'    publication on housing conditions which is also used by [MICS6](https://mics.unicef.org/tools).
#'    
#'    Overcrowding is also used which occurs if there are more than three people
#'     per habitable room as defined by [UN-Habitat](https://www.ncbi.nlm.nih.gov/books/NBK535289/table/ch3.tab2/).
#'     
#'     **Numerator**: Population that have access to adequate housing
#'     **Denominator**: Total population
#'     
#' **Formula**: 
#' 
#'      *DWE01* = 1,2 &
#'      *DWE02* = 3,4,5,6,7,8,9 & 
#'      *DWE03* = 8,9,10,11,12,13 & 
#'      *DWE04* = 10,11,12,13,14,15 & 
#'      crowding (*HH01*/*DWE05*) \<= 3
#' 
#' Adequate shelter is calculated from the main dataset
#' classify as habitable when improved/adequate shelter
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                    
#' @param mapper a list providing the mapping of the variables used for the 
#' calculation - this mapper is potentially to be adjusted in relation with deviation
#' between the the standard XlsForm and the contextualized dataset
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' datalist <- kobocruncher::kobo_data( system.file("test.xlsx", 
#'                                                  package = "IndicatorCalc"))
#'
#' mapper <- list(
#'             hierarchy = "main",
#'             variablemap = data.frame(
#'               label = c(
#'                 "What type of dwelling does the household live in?",
#' "Main material of the dwelling floor",
#' "Main material of the roof",
#' "Main material of the exterior walls",
#' "How many separate rooms do the members of your household occupy?",
#' "What is the total number of persons in this household?"),
#'               variable = c("DWE01","DWE02","DWE03","DWE04","DWE05", 
#'                            "HH01"),
#'               mappattern = c("DWE01","DWE02","DWE03","DWE04","DWE05", 
#'                            "progres_groupsize") ),
#'             modalitymap = data.frame(
#'               variable = c( "DWE01","DWE01",
#'                             "DWE02","DWE02","DWE02",
#'                             "DWE03","DWE03","DWE03","DWE03","DWE03","DWE03",
#'                             "DWE04","DWE04","DWE04","DWE04","DWE04","DWE04"),
#'               label = c(  "Apartment", "House", # DWE01
#'                          "Earth/sand", "Dung", "Other (Specify)", #DWE02
#'                          
#'                          "Metal/tin", "Wood", "Calamine/Cement fibre", 
#'                          "Ceramic tiles", "Cement", "Roofing shingles",#DWE03
#'                          
#'                          "Cement", "Stone with lime/ cement", "Bricks", 
#'                          "Cement blocks", "Covered adobe", "Wood planks/shingles" # DWE04
#'                          ),
#'               standard = c( "1","2",
#'                            "1", "2","96",
#'                            "8","9","10","11","12","13",
#'                            "10","11","12","13","14","15"),
#'               map = c("1","2",
#'                            "1", "2","96",
#'                            "8","9","10","11","12","13",
#'                            "10","11","12","13","14","15"))) 
#' ## Calculate
#' datalist <-  inter_shelter(datalist, mapper)
#' # Tabulate
#' table(datalist[["main"]]$dwe01_cat)
#' table(datalist[["main"]]$dwe02_cat)
#' table(datalist[["main"]]$dwe03_cat)
#' table(datalist[["main"]]$dwe04_cat)
#' table(datalist[["main"]]$dwe05_cat)
#' table(datalist[["main"]]$shelter)
#' #plot
#' fct_plot_indic_donut(datalist[["main"]]$shelter,
#'                      iconunicode = "e54f") 
inter_shelter <- function(datalist, 
         mapper = list(
            hierarchy = "main",
            variablemap = data.frame(
              label = c(
                "What type of dwelling does the household live in?",
"Main material of the dwelling floor",
"Main material of the roof",
"Main material of the exterior walls",
"How many separate rooms do the members of your household occupy?",
"What is the total number of persons in this household?"),
              variable = c("DWE01","DWE02","DWE03","DWE04","DWE05", 
                           "HH01"),
              mappattern = c("DWE01","DWE02","DWE03","DWE04","DWE05", 
                           "HH01") ),
            modalitymap = data.frame(
              variable = c( "DWE01","DWE01",
                            "DWE02","DWE02","DWE02",
                            "DWE03","DWE03","DWE03","DWE03","DWE03","DWE03",
                            "DWE04","DWE04","DWE04","DWE04","DWE04","DWE04"),
              label = c(  "Apartment", "House", # DWE01
                         "Earth/sand", "Dung", "Other (Specify)", #DWE02
                         
                         "Metal/tin", "Wood", "Calamine/Cement fibre", 
                         "Ceramic tiles", "Cement", "Roofing shingles",#DWE03
                         
                         "Cement", "Stone with lime/ cement", "Bricks", 
                         "Cement blocks", "Covered adobe", "Wood planks/shingles" # DWE04
                         ),
              standard = c( "1","2",
                           "1", "2","96",
                           "8","9","10","11","12","13",
                           "10","11","12","13","14","15"),
              map = c("1","2",
                           "1", "2","96",
                           "8","9","10","11","12","13",
                           "10","11","12","13","14","15")))  ){
  
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
 # if (check_map == FALSE) {
    datalist <- fct_re_map(datalist = datalist,
                              mapper = mapper)
 # }
    
 #Only apartment and house
datalist[["main"]]$dwe01_cat <- 
  dplyr::case_when(
    (datalist[["main"]]$DWE01=="1" | 
     datalist[["main"]]$DWE01=="2") ~ "1", 
    TRUE ~ "0" )
## unimproved floor when earth,sand,clay,mud, dung or other
datalist[["main"]]$dwe02_cat= dplyr::case_when( 
    (datalist[["main"]]$DWE02=="1" | 
     datalist[["main"]]$DWE02=="2" | 
     datalist[["main"]]$DWE02=="96") ~ "0", 
    TRUE ~ "1" )
## unimproved roof all options except metal,wood,ceramic tiles, cement, roofing shingles/sheets
datalist[["main"]]$dwe03_cat= dplyr::case_when( 
    (datalist[["main"]]$DWE03=="8" |
     datalist[["main"]]$DWE03=="9" | 
     datalist[["main"]]$DWE03=="10" | 
     datalist[["main"]]$DWE03=="11" |
     datalist[["main"]]$DWE03=="12" | 
     datalist[["main"]]$DWE03=="13" ) ~ "1" , 
    TRUE ~ "0")

## improved wall: cement,stone,bricks,cement blocks, covered adobe, wood planks
datalist[["main"]]$dwe04_cat= dplyr::case_when( 
    (datalist[["main"]]$DWE04=="10"| 
    datalist[["main"]]$DWE04=="11"| 
    datalist[["main"]]$DWE04=="12"| 
    datalist[["main"]]$DWE04=="13"| 
    datalist[["main"]]$DWE04=="14"| 
    datalist[["main"]]$DWE04=="15") ~ "1",
    TRUE ~ "0")

## Calculate crowding index - overcrowded when more than 3 persons
datalist[["main"]]$crowding <- as.numeric(datalist[["main"]]$HH01) / 
     as.numeric(datalist[["main"]]$DWE05)

datalist[["main"]]$dwe05_cat= dplyr::case_when( ##if crowding <= 3, not overcrowded 
    datalist[["main"]]$crowding <= 3 ~ "1", 
    TRUE ~ "0")
  
####Calculate if all 5 conditions are met for adequate shelter
##dwe01_cat / dwe02_cat / dwe03_cat / dwe04_cat / dwe05_cat

datalist[["main"]]$shelter= dplyr::case_when(
    datalist[["main"]]$dwe01_cat=="0" | 
    datalist[["main"]]$dwe02_cat=="0" | 
    datalist[["main"]]$dwe03_cat=="0" | 
    datalist[["main"]]$dwe04_cat=="0" | 
    datalist[["main"]]$dwe05_cat=="0"  ~ "0", 
    
    datalist[["main"]]$dwe01_cat=="1" & 
    datalist[["main"]]$dwe02_cat=="1" & 
    datalist[["main"]]$dwe03_cat=="1" & 
    datalist[["main"]]$dwe04_cat=="1" & 
    datalist[["main"]]$dwe05_cat=="1" ~ "1")

datalist[["main"]]$shelter = labelled::labelled(
  datalist[["main"]]$shelter,
         labels = c(
                               "Yes" = "1",
                               "No" = "0"
                             ),
                             label = "Access to adequate shelter") 
return(datalist)
}
