# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' inter_electricity
#' 
#'  Households lighting provides a sense of safety and security within and outside 
#'  the households after sunset.
#'  
#'  If households lack access to electricity, especially for lighting and 
#'  connectivity, this affects the occupants' security and limits their 
#'  opportunities for socialization, learning and self-reliance.
#'  
#'  **Numerator**: Population with access to electricity, especially for lighting 
#'  and connectivity
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: *LIGHT01* = 1 & *LIGHT03* != 1, 96, 98
#' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#'                    
#' @param mapper a list providing the mapping of the variables used for the 
#' calculation - this mapper is potentially to be adjusted in relation with deviation
#' between the the standard XlsForm and the contextualized dataset
#'                       
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' datalist <- kobocruncher::kobo_data( system.file("test.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' mapper <- list(
#'             hierarchy = "main",
#'             variablemap = data.frame(
#'               label = c("Does this household use anything for lighting?",
#'        "What source of electricity is used most of the time in this household?"),
#'               variable = c("LIGHT01", 
#'                            "LIGHT03"),
#'               mappattern = c("LIGHT01", 
#'                            "LIGHT03") ),
#'             modalitymap = data.frame(
#'               variable = c( "LIGHT01", 
#'                             "LIGHT03", "LIGHT03", "LIGHT03"),
#'               label = c( "yes",
#'                         "No electricity in household", "Other, specify", "Don't know"),
#'               standard = c( "1",
#'                            "1", "96", "98"),
#'               map = c("yes",
#'                       "1", "96", "98"))) 
#'
#' datalist <- inter_electricity( datalist =datalist, mapper = mapper  )
#'
#'
#' table(datalist[["main"]]$electricity)
#' fct_plot_indic_donut(indicator = datalist[["main"]]$electricity,
#'                      iconunicode = "f0e7") 
#'
inter_electricity <- function(datalist, 
         mapper = list(
            hierarchy = "main",
            variablemap = data.frame(
              label = c("Does this household use anything for lighting?",
       "What source of electricity is used most of the time in this household?"),
              variable = c("LIGHT01", 
                           "LIGHT03"),
              mappattern = c("LIGHT01", 
                           "LIGHT03") ),
            modalitymap = data.frame(
              variable = c( "LIGHT01", 
                            "LIGHT03", "LIGHT03", "LIGHT03"),
              label = c( "yes",
                        "No electricity in household", "Other, specify", "Don't know"),
              standard = c( "1",
                           "1", "96", "98"),
              map = c("1",
                      "1", "96", "98")))  ) {
  
  ## So first we check that we have what we need in the data set based on the mapper
   fct_check_map(datalist = datalist,
                             mapper = mapper)
  #if (check_map == FALSE) {
  datalist <- fct_re_map(datalist = datalist,
                              mapper = mapper)
 # }
  
  ## now pull the calculation...
  datalist[["main"]]$electricity <-  dplyr::case_when(datalist[["main"]]$LIGHT01=="1" & 
                       (datalist[["main"]]$LIGHT03!="1" | 
                        datalist[["main"]]$LIGHT03!="96" |
                        datalist[["main"]]$LIGHT03!="98")  ~ "1", 
                     TRUE ~ "0" )
  ## Apply Label
  datalist[["main"]]$electricity <- labelled::labelled(  
                            datalist[["main"]]$electricity,
                                 labels = c(
                                   "Yes" = "1",
                                   "No" = "0"
                                 ),
                                 label = "Access to electricity")
  return(datalist)
}
