# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome9_2
#' 
#' 
#' **Proportion of Persons of Concern that have energy to ensure lighting**
#' 
#' This indicator measures the percentage of Persons of Concern who have access to clean and sustainable source of lighting at household level.
#' Safe and sustainable access to clean energy is increasingly recognized as human right and is an integral part of the Sustainable Development Goals.
#' 
#' The indicator for lighting is constructed from the essential questions *LIGHT01* and *LIGHT02* which captures the most used light source.
#' [LSMS Guidebook](https://documents1.worldbank.org/curated/en/557341633679857128/pdf/Measuring-Energy-Access-A-Guide-to-Collecting-Data-Using-the-Core-Questions-on-Household-Energy-Use.pdf) is the main source for measuring energy access as defined for SGD 7.1.12.
#' 
#' | Standard Questions |
#' |:------------------:|
#' | LIGHT01 - LIGHT03  |
#' 
#' : $\frac{Population with reliance on clean fuels and technologies for lighting}{Total population}$
#' 
#' **Numerator**: Population living in households with primary reliance on clean fuels and technologies for lighting
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *LIGHT01* = 1 & *LIGHT02* = 1, 3, 4, 5, 6, 7, 8 / Total Population
#' 
#' This comes from the main dataset
#' 
#'  The below Calculates percentage of PoC having access to clean fuel for lighting and / or basic connectivity (9.1 Outcome Indicator)
#'  
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome9_2(datalist )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome9_2,
#'                      iconunicode = "f140")   
outcome9_2 <- function(datalist ){
   # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("4. Does this household use anything for lighting?", "5. What does this household use most of the time as energy for lighting, or as a light source?", 
"6. What source of electricity is used most of the time in this household?"
)
              ,
            variable =  
c("LIGHT01", "LIGHT02", "LIGHT03")
              ),
          modalitymap = data.frame(
            variable =  
c("LIGHT01", "LIGHT01", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", 
"LIGHT02", "LIGHT02", "LIGHT02", "LIGHT02", "LIGHT03", "LIGHT03", 
"LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", "LIGHT03", 
"LIGHT03", "LIGHT03")
               ,
            label =  
c("Yes", "No", "Electricity (including solar mini-grids, hybrid mini-grids and national grid)", 
"Electricity (from diesel generator)", "Solar home system", "Solar-powered lantern or flashlight", 
"Rechargeable flashlight, mobile, torch or lantern", "Battery powered flashlight, torch or lantern", 
"Biogas lamp", "LPG lamp", "Gasoline lamp", "Kerosene or paraffin lamp", 
"Oil lamp", "Candle", "Open fire", "Other, specify", "No electricity in household", 
"National grid connection from [COMPANY]", "Local mini grid", 
"Solar home system", "Solar lantern", "Electric generator", "Rechargeable battery", 
"Dry cell battery / torch", "Other, specify", "Don't know")
               ,
            standard =  
c("1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"11", "12", "13", "96", "1", "2", "3", "4", "5", "6", "7", "8", 
"96", "98")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 9.2")
  } else {
    
datalist[["main"]]$outcome9_2 <- dplyr::case_when(
  as.integer(datalist[["main"]]$LIGHT01) == 1 & 
     (as.integer(datalist[["main"]]$LIGHT02) == 1 |
      as.integer(datalist[["main"]]$LIGHT02) == 3 | 
      as.integer(datalist[["main"]]$LIGHT02) == 4 | 
      as.integer(datalist[["main"]]$LIGHT02) == 5 |
      as.integer(datalist[["main"]]$LIGHT02) == 6 |
      as.integer(datalist[["main"]]$LIGHT02) == 7 |
      as.integer(datalist[["main"]]$LIGHT02) == 8 )  ~ 1, 
     TRUE ~ 0)

datalist[["main"]]$outcome9_2  <- labelled::labelled(datalist[["main"]]$outcome9_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
  label = "Proportion of PoC that have energy to ensure lighting")

}
   return(datalist)
}
