# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome10_2
#' 
#' **Proportion of births attended by skilled health personnel**
#' 
#' This indicator measures the percentage of births attended by personnel trained to give the necessary supervision, care, and advice to women during pregnancy, labor, and the postpartum period; to conduct deliveries on their own; and to care for newborns.
#' This indicator is linked to SGD [3.1.2](https://unstats.un.org/sdgs/metadata/files/Metadata-03-01-02.pdf).
#' 
#' National-level household surveys are the main data sources used to collect data for skilled health personnel providing childbirth care.
#' These surveys include Demographic and Health Surveys (DHS), Multiple Indicator Cluster Surveys (MICS), Reproductive Health Surveys (RHS) and other national surveys based on similar methodologies.
#' Standard module is from [UNICEF MICS6](https://mics.unicef.org/tools#survey-design) individual questionnaire for woman.
#' The calculation of this module is also aligned with UNICEF MICS6.
#' 
#' The national categories of skilled health personnel are verified, and the estimates for some countries may include additional categories of trained personnel beyond doctor, nurse, and midwife.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    BIR01-BIR04     |
#' 
#' **Numerator**: Total number of births attended by skilled health personnel)
#' 
#' **Denominator**: Total number of live births
#' 
#' **Formula**: (BIR01=1 | BIR02=1) & (BIR03=1,2,3) / Total number of live births
#' This comes from the main dataset
#' MICS TM.5.a UNICEF MICS calculation if there was a trained health personnel ##
#' If there are live births in the last 2 years 
#'  Traditional birth attendant and community health worker can be included if they are trained
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome10_2(datalist  )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome10_2,
#'                      iconunicode = "f140")   
outcome10_2 <- function(datalist){
  ## Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. In addition to ${namechild2less} was there any live birth in this household in the past 2 years?", 
"2. Was there any live birth in this household in the past 2 years?", 
"3. Who assisted with the delivery of  the latest child born alive ?", 
"4. Where did the birth take place for the latest child born alive ?"
)
              ,
            variable =  
c("BIR01", "BIR02", "BIR03", "BIR04")
              ),
          modalitymap = data.frame(
            variable =  
c("BIR01", "BIR01", "BIR02", "BIR02", "BIR03", "BIR03", "BIR03", 
"BIR03", "BIR03", "BIR03", "BIR03", "BIR03", "BIR04", "BIR04", 
"BIR04", "BIR04")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Health professional", "Doctor", 
"Nurse/midwife", "Traditional birth attendant", "Community health worker", 
"Relative/friend", "Other (specify)", "Don't know", "Respondent’s home", 
"Public sector", "Private sector", "Other, specify")
               ,
            standard =  
c("1", "0", "1", "0", "1", "2", "3", "4", "5", "6", "96", "98", 
"1", "2", "3", "96")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 10.2")
  } else {
    
datalist[["main"]]$outcome10_2 <- dplyr::case_when( 
    ( as.integer(datalist[["main"]]$BIR01) == 1 | 
     as.integer(datalist[["main"]]$BIR02) == 1) &
    (as.integer(datalist[["main"]]$BIR03) == 1 |
     as.integer(datalist[["main"]]$BIR03) == 2 |
     as.integer(datalist[["main"]]$BIR03) == 3 )   ~ 1,
    
    (as.integer(datalist[["main"]]$BIR01) == 1 | 
     as.integer(datalist[["main"]]$BIR02) == 1) & (
     as.integer(datalist[["main"]]$BIR03) == 4 | 
     as.integer(datalist[["main"]]$BIR03) == 5 | 
     as.integer(datalist[["main"]]$BIR03) == 6 | 
     as.integer(datalist[["main"]]$BIR03) == 96| 
     as.integer(datalist[["main"]]$BIR03) == 98) ~ 0, 
    
    TRUE ~ NA_real_)

datalist[["main"]]$outcome10_2  <- labelled::labelled(datalist[["main"]]$outcome10_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                 label = "Proportion of births attended
                            by skilled health personnel")
}
   return(datalist)
}
