# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome12_2
#' 
#' **Proportion of Persons of Concern with access to a safe household toilet**
#' 
#' This indicator measures the proportion of persons of concerns with access to at least basic sanitation services -- toilets -- that are not shared with other households.
#' A toilet is defined as a basic sanitation facility.
#' This indicator is linked to SGD indicator [6.2.1](https://sdg-tracker.org/water-and-sanitation#:~:text=Definition%3A%20Indicator%206.2.,at%20least%20basic%20handwashing%20facilities.).
#' The standard module is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis) main household questionnaire.
#' Calculation of the indicator is based on [MICS6 analysis tools](https://mics.unicef.org/tools#analysis).
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    TOI01-TOI05     |
#' 
#' **Numerator**: Total population with access to sanitation facility at their household
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *TOI01*=1,2,3,4,5,6,7,9 & (*TOI02* =1 & *TOI03*=1,2,3,4) & *TOI05*=1
#' This comes from the main dataset
#' MICS calculation WS3.1/WS3.4
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome12_2(datalist)
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome12_2,
#'                      iconunicode = "f140")   
outcome12_2 <- function(datalist ){
  ## mapper, 
  mapper = list(
           hierarchy = "main",
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. What is the MAIN type of toilet facility used by your household?", 
"2. Has your toilet ever been emptied?", "3. The last time it was emptied, where were the contents emptied to?", 
"4. Where is this toilet facility located?", "5. Does your household share this facility with others households?"
)
              ,
            variable =  
c("TOI01", "TOI02", "TOI03", "TOI04", "TOI05")
              ),
          modalitymap = data.frame(
            variable =  
c("TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI01", 
"TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI01", "TOI02", 
"TOI02", "TOI02", "TOI03", "TOI03", "TOI03", "TOI03", "TOI03", 
"TOI03", "TOI03", "TOI04", "TOI04", "TOI04", "TOI05", "TOI05"
)
               ,
            label =  
c("Flush/pour flush to the piped sewer system", "Flush/pour-flush to septic tank", 
"Flush/pour-flush to pit latrine", "Flush/pour-flush to open drain", 
"Flush/pour-flush to don\'t know where", "Ventilated improved pit latrine", 
"Pit latrine with slab", "Pit latrine without slab/open pit", 
"Composting toilet", "Bucket", "Hanging toilet/hanging latrine", 
"No facility/bush/field", "Other (Specify)", "Yes, emptied", 
"No, never emptied", "Don\'t know", "Removed by a service provider to a treatment plant", 
"Removed by a service provider and buried in a covered pit", 
"Removed by a service provider to don\u2019t know where", "Emptied by household and buried in a covered pit", 
"Emptied by household to uncovered pit, open ground, water body, or elsewhere", 
"Other (specify)", "Don\u2019t know", "In Own Dwelling", "In Own Yard/Plot", 
"Elsewhere", "Yes", "No")
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 
"96", "1", "2", "98", "1", "2", "3", "4", "5", "96", "98", "1", 
"2", "3", "1", "0")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 12.2")
  } else {
  
    
datalist[["main"]]$toi_cond1 <- dplyr::case_when(
  as.integer(datalist[["main"]]$TOI01) == 1 |
  as.integer(datalist[["main"]]$TOI01) == 2 | 
  as.integer(datalist[["main"]]$TOI01) == 3 | 
  as.integer(datalist[["main"]]$TOI01) == 4 |
  as.integer(datalist[["main"]]$TOI01) == 5 |
  as.integer(datalist[["main"]]$TOI01) == 6 | 
  as.integer(datalist[["main"]]$TOI01) == 7 | 
  as.integer(datalist[["main"]]$TOI01) == 9 ~ 1,
  
  as.integer(datalist[["main"]]$TOI01) == 8 | 
  as.integer(datalist[["main"]]$TOI01) == 10 | 
  as.integer(datalist[["main"]]$TOI01) == 11 | 
  as.integer(datalist[["main"]]$TOI01) == 12 | 
  as.integer(datalist[["main"]]$TOI01) == 96 ~ 0,
  
  TRUE ~ NA_real_)

#Unsafe disposal
datalist[["main"]]$toi_cond2 <- dplyr::case_when(
 
    as.integer(datalist[["main"]]$TOI02) == 1 & 
    ( as.integer(datalist[["main"]]$TOI03) == 1 |
      as.integer(datalist[["main"]]$TOI03) == 2 |
      as.integer(datalist[["main"]]$TOI03) == 3 |
      as.integer(datalist[["main"]]$TOI03) == 4 ) ~ 1, 
    
    as.integer(datalist[["main"]]$TOI02) == 1 & 
      (as.integer(datalist[["main"]]$TOI03) ==5 |
       as.integer(datalist[["main"]]$TOI03) == 96 | 
       as.integer(datalist[["main"]]$TOI03) == 98) ~ 0, 
  
  as.integer(datalist[["main"]]$TOI02) == 2 ~  0, 
  as.integer(datalist[["main"]]$TOI02) == 98 ~ 0, 
  TRUE ~ NA_real_)

 # toilet not shared with other households
datalist[["main"]]$toi_cond3<- dplyr::case_when(
    as.integer(datalist[["main"]]$TOI05) == 1 ~ 0, 
    as.integer(datalist[["main"]]$TOI05) == 0 ~ 1) 


###Combine all three conditions below
### improved sanitation facility / 
# Safe disposal in situ of excreta from on-site sanitation facilities / 
# not shared with other HHs

datalist[["main"]]$outcome12_2<- dplyr::case_when(
    datalist[["main"]]$toi_cond1 == 1 | 
    datalist[["main"]]$toi_cond2 == 1 |
    datalist[["main"]]$toi_cond3 == 1 ~ 1,
    TRUE ~ 0)

datalist[["main"]]$outcome12_2  <- labelled::labelled(datalist[["main"]]$outcome12_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                                label = "Proportion of Persons of Concern 
                            with acess to a safe household toilet")
}
   return(datalist)
}
