# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome1_2 
#' 
#' **Proportion of children under 5 years of age whose births have been registered with a civil authority**
#' 
#' This indicator measures the proportion of children under 5 years old whose births
#'  have been registered with a civil authority and civil documentation has been issued.
#'  This is directly linked to SGD indicator [16.9.1](https://unstats.un.org/sdgs/metadata/files/Metadata-16-09-01.pdf).
#'  
#'  The standard module for this indicator is taken from MICS and adjusted to UNHCR context.
#'  
#'  **Definitions**
#'  
#'  •**Birth registration** refers to the registration of new births by civil 
#'  authorities and completion of the process through the issuance of a birth certificate.
#'  This also includes documents issued by UNHCR or other relevant organizations 
#'  when **given the authority by the State and these documents are recognized by national authorities**.
#'  
#'  **Clarifications**
#'  
#'  •Birth notifications or other hospital records and records from midwives or 
#'  traditional birth attendants, **issued solely by UNHCR or its partners shall
#'   not be considered** as birth certificates although they are important sources 
#'   for establishing the total number of births.
#'   Operations are encouraged to track both the number of birth notifications and
#'    birth registrations but for the purpose of this indicator should report 
#'    the number of births registered.
#'    
#'    • The standard indicator used in DHS, MICS and RMS to report on birth 
#'    registration refers to the percentage of children under age 5 (0-59 months) 
#'    with a birth certificate, regardless of whether or not it was seen by the 
#'    interviewer, or whose birth was reported as registered with civil
#'     authorities at the time of survey.
#'     
#'     | Standard Questions |
#'     |:------------------:|
#'     |   REG03 - REG04    |
#'     
#'     **Numerator**: Number of children under 5 years old who are registered with civil authorities
#'     **Denominator**: Total number of children under 5 years old
#'     **Formula**: (*REG03=1 \| REG04=1) / Number of children under 5*
#'     
#'     This indicator comes from the individual dataset
#'      ind$REG03 - birth certificate
#'      ind$REG04 - birth has been registered
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#'
#' ## Apply indicator function on datalist
#' datalist <- outcome1_2(datalist)
#' table(datalist[["ind"]]$outcome1_2, useNA = "ifany")
#' table(datalist[["ind"]]$less_than_5, useNA = "ifany")
#' table(datalist[["ind"]]$HH07, useNA = "ifany")
#' barplot(as.integer(datalist[["ind"]]$HH07))
#' table(datalist[["ind"]]$birthCertificate, useNA = "ifany")
#' table(datalist[["ind"]]$birthRegistered, useNA = "ifany")
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome1_2,
#'                      iconunicode = "f140")   
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$birthCertificate,
#'                      iconunicode = "f140")   
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$birthRegistered,
#'                      iconunicode = "f140")   
outcome1_2 <- function(datalist){
  ## mapper
mapper = list(
  hierarchy = "ind",
  variablemap = data.frame(
    label =
      c("3. Does ${name_individual} have a birth certificate?", "4. Has ${name_individual}\'s birth been registered with civil authorities?",
        "6. Can you estimate how old is ${HH02}?")
    ,
    variable =
      c("REG03", "REG04", "HH07")
  ),
  modalitymap = data.frame(
    variable =
      c("REG03", "REG03", "REG03", "REG04", "REG04", "REG04", "REG04",
        "HH07")
    ,
    label =
      c("Yes", "No", "Don\'t know", "Yes", "No", "Don\'t know", "Prefer not to say",
        NA)
    ,
    standard =
      c("1", "0", "98", "1", "0", "98", "99", NA)
  ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 1.2")
  } else {
  
  ##Calculate children who has a birth certificate
  datalist[["ind"]]$birthCertificate <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG03) == 0 | 
      as.integer(datalist[["ind"]]$REG03) == 98 ~ 0, 
      as.integer(datalist[["ind"]]$REG03) == 1 ~ 1)

  datalist[["ind"]]$birthCertificate  <- labelled::labelled(datalist[["ind"]]$birthCertificate,
   labels = c('Yes' = 1, 'No' = 0 ),
   label = "Children with a birth certificate")
  
  ##Calculate children who has been registered with civil authorities
  datalist[["ind"]]$birthRegistered <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG04) == 0 | 
      as.integer(datalist[["ind"]]$REG04) == 98 ~ 0, 
      as.integer(datalist[["ind"]]$REG04) == 1 ~ 1, 
      as.integer(datalist[["ind"]]$REG04) == 99 ~ NA_real_)
  
   datalist[["ind"]]$birthRegistered  <- labelled::labelled(datalist[["ind"]]$birthRegistered,
    labels = c('Yes' = 1, 'No' = 0 ),
    label = "Children with birth registered with civil authorities")
  
   ## less than 5
  datalist[["ind"]]$less_than_5 <- dplyr::case_when(
       as.numeric(datalist[["ind"]]$HH07) <  5  ~ 1, 
       TRUE ~ 0)
  datalist[["ind"]]$less_than_5  <- labelled::labelled(datalist[["ind"]]$less_than_5,
    labels = c('Yes' = 1, 'No' = 0 ),
    label = "Is a Children")
  
  ##if the birth is registered or child has a birth certificate
  datalist[["ind"]]$outcome1_2 <- dplyr::case_when(
      (datalist[["ind"]]$birthRegistered == 1 | 
       datalist[["ind"]]$birthCertificate == 1) & 
        as.integer(datalist[["ind"]]$HH07) <  5 ~ 1, 
      
      (datalist[["ind"]]$birthRegistered == 0 & 
       datalist[["ind"]]$birthCertificate == 0) & 
        as.integer(datalist[["ind"]]$HH07) < 5 ~ 0, 
      
      TRUE ~ NA_real_ )

    datalist[["ind"]]$outcome1_2  <- labelled::labelled(datalist[["ind"]]$outcome1_2,
      labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion of children under 5 years of age whose births have been registered with a civil authority")

  }
   return(datalist) 
}
