# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome12_1
#' 
#' **Proportion of Persons of Concern using at least basic drinking water services**
#' 
#' This indicator is defined as the percentage of PoCs using at least basic water services.
#' Access to clean drinking water is essential for a person's survival and well being and a precursor for achieving protection outcomes related to health, education and economic developed.
#' The calculation for access drinking water is linked to SGD Indicator [6.1.1](https://unstats.un.org/sdgs/metadata/files/Metadata-06-01-01.pdf).
#' The questionnaire module and the analysis guidance is taken from [UNICEF MICS6](https://mics.unicef.org/tools#analysis).
#' 
#' 
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    DWA01-DWA04     |
#' 
#' **Numerator**: Population using improved sources of drinking water either in their dwelling/yard/plot or within 30 minutes round trip collection time
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: 
#'   *DWA03* \< 30 (under 30 minutes), &
#'  *DWA01* !=7,9,13,96,98 &
#'   *DWA02* !=3
#' 
#' This comes from the main dataset
#' There are two conditions as below improved source, in dwelling/yard/plot or reachable under 30 minutes 
#' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome12_1(datalist  )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome12_1,
#'                      iconunicode = "f140")   
outcome12_1 <- function(datalist ){
  # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. What is the main source of drinking water for this household?", 
"2. Where is this ${source} - ${source2} located?", "Unit", "Time", 
"4. In the last 30 days, has there been any time when your household did not have sufficient quantities of drinking water when needed?"
)
              ,
            variable =  
c("DWA01", "DWA02", "DWA03a", "DWA03b", "DWA04")
              ),
          modalitymap = data.frame(
            variable =  
c("DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", "DWA01", 
"DWA01", "DWA01", "DWA01", "DWA01", "DWA02", "DWA02", "DWA02", 
"DWA03a", "DWA03a", "DWA03b", "DWA04", "DWA04")
               ,
            label =  
c("Piped Into Dwelling", "Piped Into Yard/Plot", "Piped To Neighbor", 
"Public Tap/Standpipe", "Tube Well/Borehole", "Protected Dug Well", 
"Unprotected Dug Well", "Protected Spring", "Unprotected Spring", 
"Rain Water Collection", "Tanker Truck/Water Vendor", "Cart With Small Tank/Drum", 
"Surface Water (River, Stream, Pond, Dam, Canal)", "Bottled Water", 
"Sachet Water", "Water Kiosk", "Other (Specify)", "Don't Know", 
"In Own Dwelling", "In Own Yard/Plot", "Elsewhere", "Minutes", 
"Hours", NA, "Yes", "No")
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", 
"13", "14", "15", "16", "96", "98", "1", "2", "3", "1", "2", 
NA, "1", "0")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 12.1")
  } else {
  
  #convert hour into minutes
datalist[["main"]]$time_DWA <- dplyr::case_when(
    as.integer(datalist[["main"]]$DWA03a) == 1 ~ 1, 
    as.integer(datalist[["main"]]$DWA03a) == 2 ~ 60)

datalist[["main"]]$time_tot <- datalist[["main"]]$time_DWA * 
                                as.integer(datalist[["main"]]$DWA03b)

# reachable under 30 minutes
datalist[["main"]]$reachableU30 <- dplyr::case_when( 
  datalist[["main"]]$time_tot > 30 ~ 0,
  TRUE ~ 1) 

# improved source
datalist[["main"]]$dwa_cond1 <- dplyr::case_when(
  as.integer(datalist[["main"]]$DWA01) != 7 |
  as.integer(datalist[["main"]]$DWA01) != 9 |
  as.integer(datalist[["main"]]$DWA01) != 13 | 
  as.integer(datalist[["main"]]$DWA01) != 96 |
  as.integer(datalist[["main"]]$DWA01) != 98 ~ 1,
  
  TRUE ~ 0) 

datalist[["main"]]$dwa_cond1  <- labelled::labelled(datalist[["main"]]$dwa_cond1 ,
                            labels = c('Yes' = 1, 'No' = 0 ),
                            label = "Water: improved source") 

## Second condition

datalist[["main"]]$dwa_cond2 <- dplyr::case_when( 
  
  as.integer(datalist[["main"]]$DWA02) == 3   ~ 1, 
  
  #UNDER30 MIN
  as.integer(datalist[["main"]]$reachableU30) == 1 & 
  # NOT UNDER30 MIN
  as.integer(datalist[["main"]]$reachableU30) == 0 & 
  as.integer(datalist[["main"]]$DWA02) == 3 ~ 0, 
  
  # in the dwelling/yard/plot
  as.integer(datalist[["main"]]$DWA02) == 1 | 
  as.integer(datalist[["main"]]$DWA02) == 2 ~ 1, 
  
  TRUE ~ NA ) 

datalist[["main"]]$dwa_cond2  <- labelled::labelled(datalist[["main"]]$dwa_cond2 ,
                            labels = c('Yes' = 1, 'No' = 0 ),
                            label = "Water accessible") 


## Composite
datalist[["main"]]$outcome12_1 <- dplyr::case_when(
     (datalist[["main"]]$dwa_cond1 == 1 & 
      datalist[["main"]]$dwa_cond2 == 1 ) ~ 1, 
    TRUE ~ 0)

datalist[["main"]]$outcome12_1  <- labelled::labelled(datalist[["main"]]$outcome12_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
          label = "Proportion of PoC using at least basic drinking water services") 

   }
   return(datalist)
}
