# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome14_1
#' 
#' **Proportion of returnees with legally recognized identity documents or credentials**
#' 
#' This indicator measures the proportion of returned refugees who possess legally recognized and valid identity documents or credentials to support their return .
#' 
#' Commonly in the context of return, returnees require civil documentation or credentials and inclusion in or updating of civil registries , as well as access to services.
#' 
#' ***Definitions***
#' 
#' • Identity document or credential is any document or credential which may be used as proof of identity, which may also include reference to the individuals' legal status and associated rights vis-à-vis the host State and/or UNHCR.
#' 
#' |          Standard Questions           |
#' |:-------------------------------------:|
#' | REG01 - REG02 - REG03 / REG05 - REG06 |
#' 
#' **Numerator**: Total number of returnees with with legally recognized identity documents or credentials
#' 
#' **Denominator**: Total number of returnees
#' 
#' **Formula**: *REG01*=1 \| *REG02*=1 \| *REG03*=1 \| *REG05*=1 \| *REG06*=1
#' 
#'This indicator comes from the individual dataset
#' Calculate valid identity documents for under 5 with REG05 and REG06 variables
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#'
#' ## Apply indicator function on datalist
#' datalist <- outcome14_1(datalist )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome14_1,
#'                      iconunicode = "f140")   
outcome14_1 <- function(datalist ){
  ## Mapper , 

mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("Passport?", "Birth certificate?", "Civil/government-issued ID card ?", 
"Residency permit (both temporary and permanent)?", "Statelessness documentation?", 
"Household card of address / family book/ marriage certificate?", 
"Social security card?", "2. Does ${name_individual} have any other document that establishes his/her legal identity?", 
"3. Does ${name_individual} have a birth certificate?", "4. Has ${name_individual}\'s birth been registered with civil authorities?", 
"Passport?", "Civil/government-issued ID card ?", "Residency permit (both temporary and permanent)?", 
"Statelessness documentation?", "Household card of address / family book/ marriage certificate?", 
"Social security card?", "6. Does ${name_individual} have any other document that establishes your legal identity?"
)
              ,
            variable =  
c("REG01a", "REG01b", "REG01c", "REG01d", "REG01e", "REG01f", 
"REG01g", "REG02", "REG03", "REG04", "REG05a", "REG05b", "REG05c", 
"REG05d", "REG05e", "REG05f", "REG06")
              ),
          modalitymap = data.frame(
            variable =  
c("REG01a", "REG01a", "REG01a", "REG01b", "REG01b", "REG01b", 
"REG01c", "REG01c", "REG01c", "REG01d", "REG01d", "REG01d", "REG01e", 
"REG01e", "REG01e", "REG01f", "REG01f", "REG01f", "REG01g", "REG01g", 
"REG01g", "REG02", "REG02", "REG02", "REG03", "REG03", "REG03", 
"REG04", "REG04", "REG04", "REG04", "REG05a", "REG05a", "REG05a", 
"REG05b", "REG05b", "REG05b", "REG05c", "REG05c", "REG05c", "REG05d", 
"REG05d", "REG05d", "REG05e", "REG05e", "REG05e", "REG05f", "REG05f", 
"REG05f", "REG06", "REG06", "REG06")
               ,
            label =  
c("Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Don\'t know", "Yes", "No", "Don\'t know", "Prefer not to say", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond")
               ,
            standard =  
c("1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "98", "1", "0", "98", "99", "1", "0", "99", "1", "0", 
"99", "1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", 
"99", "1", "0", "99")
              ))
       
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 14.1")
  } else {

datalist[["ind"]]$document_under5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG05a) == 1 |  #ind$REG05a - passport
      as.integer(datalist[["ind"]]$REG05b) == 1 |  #ind$REG05b - civil/government issued ID
      as.integer(datalist[["ind"]]$REG05c) == 1 |  #ind$REG05c - residency permit
      as.integer(datalist[["ind"]]$REG05d) == 1 |  #ind$REG05d - statelessness documentation
      as.integer(datalist[["ind"]]$REG05e) == 1 |  #ind$REG05e - household card of address/family book
      as.integer(datalist[["ind"]]$REG05f) == 1 |  #ind$REG05f - social security card
      as.integer(datalist[["ind"]]$REG06)  == 1 | #ind$REG06 - any other document establishes identity
      as.integer(datalist[["ind"]]$REG03)  == 1   #add birth certificate as additional document from REG03
           ~ 1,
      as.integer(datalist[["ind"]]$REG05a) == 0 & 
      as.integer(datalist[["ind"]]$REG05b) == 0 & 
      as.integer(datalist[["ind"]]$REG05c) == 0 & 
      as.integer(datalist[["ind"]]$REG05d) == 0 & 
      as.integer(datalist[["ind"]]$REG05e) == 0 & 
      as.integer(datalist[["ind"]]$REG05f) == 0 & 
      as.integer(datalist[["ind"]]$REG06) == 0 & 
      as.integer(datalist[["ind"]]$REG03) == 0 ~ 0, 
      TRUE ~ NA_real_ )
  
  ###Calculate  valid identity documents for above 5 with REG01 and REG02 variables
  
  
  #ind$REG01a # passport
  #ind$REG01b # birth certificate
  #ind$REG01c # civil/ government issued ID
  #ind$REG01d # residency permit
  #ind$REG01e # statelessness documentation
  #ind$REG01f # household card of address/family book
  #ind$REG01g # social security card
  #ind$REG02 # any other document establishes identity
  
datalist[["ind"]]$document_above5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG01a) == 1 | 
      as.integer(datalist[["ind"]]$REG01b) == 1 | 
      as.integer(datalist[["ind"]]$REG01c) == 1 | 
      as.integer(datalist[["ind"]]$REG01d) == 1 | 
      as.integer(datalist[["ind"]]$REG01e) == 1 | 
      as.integer(datalist[["ind"]]$REG01f) == 1 | 
      as.integer(datalist[["ind"]]$REG01g) == 1 |
      as.integer(datalist[["ind"]]$REG02) == 1 ~ 1,
      
      as.integer(datalist[["ind"]]$REG01a) == 0 & 
      as.integer(datalist[["ind"]]$REG01b) == 0 & 
      as.integer(datalist[["ind"]]$REG01c) == 0 & 
      as.integer(datalist[["ind"]]$REG01d) == 0 & 
      as.integer(datalist[["ind"]]$REG01e) == 0 & 
      as.integer(datalist[["ind"]]$REG01f) == 0 & 
      as.integer(datalist[["ind"]]$REG01g) == 0 & 
      as.integer(datalist[["ind"]]$REG02) == 0 ~ 0, 
      
      TRUE ~ NA_real_)
      
  ##Combine both age groups
datalist[["ind"]]$outcome14_1<- dplyr::case_when(
     (datalist[["ind"]]$document_above5 == 1 | 
      datalist[["ind"]]$document_under5 == 1) ~ 1,
     
     (datalist[["ind"]]$document_above5 == 0 | 
      datalist[["ind"]]$document_under5 == 0) ~ 0)

datalist[["ind"]]$outcome14_1  <- labelled::labelled(datalist[["ind"]]$outcome14_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
                label = "Proportion of returnees with legally recognized identity 
                documents or credentials")
  }
   return(datalist)
}
