# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome16_1
#' 
#'  **Proportion of Persons of Concern with secure tenure rights and/or property rights to housing and/or land**
#'  
#'  This indicator measures the proportion of persons of concern that have secure tenure rights to housing and/or land.
#' Security of tenure means that persons of concern can live in their homes without fear of forced eviction, whether in communal settlement situations, informal settlements, host communities or after return.
#' 
#' This indicator is linked to SGD Indicator [1.4.2](https://unstats.un.org/sdgs/metadata/files/Metadata-01-04-02.pdf). The further guidance can be found [here](https://gltn.net/download/measuring-individuals-rights-to-land-an-integrated-approach-to-data-collection-for-sdg-indicators-1-4-2-and-5-a-1-english/?wpdmdl=16316&refresh=5efb342458df61593521188)
#' 
#'  *Concept*
#' 
#' -   Secure tenure rights: comprised of two sub-components: (i) legally recognized documentation and (ii) perception of the security of tenure, which are both necessary to provide a full measurement of tenure security.
#' 
#' -   Legally recognized documentation: Legal documentation of rights refers to the recording and publication of information on the nature and location of land, rights and right holders in a form that is recognized by government, and is therefore official.
#' 
#' -   Perceived security of tenure: Perception of tenure security refers to an individual's perception of the likelihood of involuntary loss of land, such as disagreement of the ownership rights over land or ability to use it, regardless of the formal status and can be more optimistic or pessimistic.
#' 
#' |    Standard Questions     |
#' |:-------------------------:|
#' | DWE06-DWE07 & DWE10-DWE11 |
#' 
#' **Numerator**: Total population with secure tenure rights to housing and/or land
#' 
#' **Denominator**: Total population
#' **Formula**: *DWE011* = 1,2 & *DWE10* = 1,2,3,4,5,6 & *DWE06* != 9, 96,98,99 & *DWE07* = 9, 96,98,99 
#' This indicator is calculated from the main dataset
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#'
#' ## Apply indicator function on datalist
#' datalist <- outcome16_1(datalist )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome16_1,
#'                      iconunicode = "f140")    
outcome16_1 <- function(datalist ){
  # Mapper , 

mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("6. Who owns the dwelling that you currently live in?", "7. Who owns the land that your current dwelling is built on?", 
"10. What type of documents does your household have for the housing you live in?", 
"11. In the next 12 months, how likely or unlikely is it that you could lose your right to this housing and/or land, against your will?"
)
              ,
            variable =  
c("DWE06", "DWE07", "DWE10", "DWE11")
              ),
          modalitymap = data.frame(
            variable =  
c("DWE06", "DWE06", "DWE06", "DWE06", "DWE06", "DWE06", "DWE06", 
"DWE06", "DWE06", "DWE06", "DWE06", "DWE06", "DWE07", "DWE07", 
"DWE07", "DWE07", "DWE07", "DWE07", "DWE07", "DWE07", "DWE07", 
"DWE07", "DWE07", "DWE07", "DWE07", "DWE07", "DWE10", "DWE10", 
"DWE10", "DWE10", "DWE10", "DWE10", "DWE10", "DWE11", "DWE11", 
"DWE11", "DWE11", "DWE11")
               ,
            label =  
c("Respondent or another HH member", "Unrelated Person", "Friend Or Relative", 
"Ngo/Non-Religious Charity", "Government Agency Or Municipality", 
"UNHCR", "Religious Organization/ Charity", "Foreign Government", 
"Unowned/Squatting", "Other (Specify)", "Don\'t know", "Prefer not to respond", 
"Respondent or another HH member", "Unrelated Person", "Friend Or Relative", 
"Ngo/Non-Religious Charity", "Government Agency Or Municipality", 
"UNHCR", "Religious Organization/ Charity", "Foreign Government", 
"Unowned/Squatting", "Apartment Building", "Community", "Other(Specify)", 
"Don\'t know", "Prefer not to respond", "Title deed", "Certificate of customary ownership", 
"Certificate of occupancy", "Certificate of hereditary acquisition listed in registry", 
"Rental contract", "Lease registered", "Other (Specify)", "Very unlikely", 
"Somewhat unlikely", "Somewhat likely", "Very likely", "Don\'t Know"
)
               ,
            standard =  
c("1", "2", "3", "4", "5", "6", "7", "8", "9", "96", "98", "99", 
"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "96", 
"98", "99", "1", "2", "3", "4", "5", "6", "96", "1", "2", "3", 
"4", "99")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 16.1")
  } else {
  
  # likelihood of losing right for housing is unlikely
  datalist[["main"]]$housing_cond1<- dplyr::case_when(
         (as.integer(datalist[["main"]]$DWE11) == 1 | 
          as.integer(datalist[["main"]]$DWE11) == 2 ) ~ 1, 
         TRUE ~ 0)
# have official documents to proof residency
  datalist[["main"]]$housing_cond2 <- dplyr::case_when(
    as.integer(datalist[["main"]]$DWE10) == 96 ~ 0, 
    as.integer(datalist[["main"]]$DWE10) == 1 | 
    as.integer(datalist[["main"]]$DWE10) == 2 |  
    as.integer(datalist[["main"]]$DWE10) == 3 | 
    as.integer(datalist[["main"]]$DWE10) == 4 | 
    as.integer(datalist[["main"]]$DWE10) == 5 | 
    as.integer(datalist[["main"]]$DWE10) == 6 ~ 1)
  
# not un-owned or not squatting
  datalist[["main"]]$housing_cond3 <- dplyr::case_when(
    as.integer(datalist[["main"]]$DWE06) == 9 | 
    as.integer(datalist[["main"]]$DWE06) == 96 | 
    as.integer(datalist[["main"]]$DWE06) == 98 | 
    as.integer(datalist[["main"]]$DWE06) == 99 | 
    as.integer(datalist[["main"]]$DWE07) == 9 | 
    as.integer(datalist[["main"]]$DWE07) == 96 | 
    as.integer(datalist[["main"]]$DWE07) == 98 | 
    as.integer(datalist[["main"]]$DWE07) == 99 ~ 0, 
    TRUE ~ 1)
  
datalist[["main"]]$outcome16_1<- dplyr::case_when(
    as.integer(datalist[["main"]]$housing_cond1) == 1 & 
    as.integer(datalist[["main"]]$housing_cond2) == 1 & 
    as.integer(datalist[["main"]]$housing_cond3) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$housing_cond1) == 0 | 
    as.integer(datalist[["main"]]$housing_cond2) == 0 | 
    as.integer(datalist[["main"]]$housing_cond3) == 0 ~ 0)

datalist[["main"]]$outcome16_1  <- labelled::labelled(datalist[["main"]]$outcome16_1,
      labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion of PoC with secure tenure rights and/or property rights to housing and/or land")
  }
   return(datalist)
}
