# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome13_2
#' 
#' **Proportion of Persons of Concern who self-report positive changes in their income compared to previous year**
#' 
#' This indicator measures the proportion of PoC who self-report positive changes in their income compared to previous year.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       INC01        |
#' 
#' **Numerator**: Population 18 and above who self-report increased income compared to last year
#' 
#' **Denominator**: Total population 18 and above
#' 
#' **Formula**: *INC01*=1
#'
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#'  Only calculate as positive if they responded 'more' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome13_2(datalist)
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome13_2,
#'                      iconunicode = "f140")   
outcome13_2 <- function(datalist){
  ## Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
"11. Compared to this time last year, do you think you can now afford more goods and services, the same, or fewer goods and services?"
              ,
            variable =  
"INC01"
              ),
          modalitymap = data.frame(
            variable =  
c("INC01", "INC01", "INC01", "INC01")
               ,
            label =  
c("More", "The same", "Fewer", "Don't know")
               ,
            standard =  
c("1", "2", "3", "98")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 13.2")
  } else {
  
datalist[["main"]]$outcome13_2<- dplyr::case_when(
  
    as.integer(datalist[["main"]]$INC01) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$INC01) == 2 |
    as.integer(datalist[["main"]]$INC01) == 3 |
    as.integer(datalist[["main"]]$INC01) == 98 ~ 0 )

datalist[["main"]]$outcome13_2  <- labelled::labelled(datalist[["main"]]$outcome13_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
    label = "Proportion of PoC who self-report positive changes in their income compared to previous year")

}
 return(datalist)
}
