# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome4_1
#' 
#' 
#' **Proportion of Persons of Concern who do not accept violence against women**
#' 
#' This indicator measures the proportion of persons of concern who disagree that a husband is justified in hitting or beating his wife for a list of specific reasons.
#' This serves as a proxy indicator for those who do not accept violence against women.
#' 
#' This module is taken from [Domestic Violence Module](https://dhsprogram.com/pubs/pdf/DHSQMP/DHS6_Module_Domestic_Violence_6Aug2014_DHSQMP.pdf) from DHS and similar module used by MICS.
#' Due to its sensitivity, this module is only recommended for face-to-face surveys.
#' 
#' *Data Collection Safeguards*
#' 
#' Enumerators (and data collection teams) must be trained on GBV safe disclosures and referrals prior to undertaking household surveys (or at least get a briefing on the GBV referral pathway in their area).
#' To ensure quality feedback and limit risks of harm, it is advisable to administer the survey to members of the household separately in confidential spaces (consider using interview rooms at community centres in settings where layout of communities' homes do not allow for confidential discussions).
#' 
#' It is also recommended to ensure same-sex enumerators to minimize risks of SEA particularly for female respondents.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |       VAW01        |
#' 
#' **Numerator**: Population 18 and above who disagree that a husband is justified in hitting or beating his wife for all the following reasons:
#' 
#' 1.  Going out without telling him.
#' 
#' 2.  Neglecting the children.
#' 
#' 3.  Arguing with him.
#' 
#' 4.  Refusing to have sexual intercourse with him.
#' 
#' 5.  Burning food.
#' 
#' **Denominator**: Total population 18 and above
#' 
#' **Formula**: ( *GBV01a=1 \| GBV01b=1 \| GBV01c=1 \| GBV01d=1) / Total population*
#' 
#' 
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' 
#' If randomly selected adult who believes that a  husband is justified in beating his wife in various circumstances
#' 
#' If yes selected for any of the circumstances
#' Prefer not to respond will be put into missing
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome4_2(datalist)
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome4_2,
#'                      iconunicode = "f140")   
outcome4_2 <- function(datalist ){
  # Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("If she goes out without telling him?", "If she neglects the children?", 
"If she argues with him?", "If she refuses to have sex with him?", 
"If she burns the food?")
              ,
            variable =  
c("VAW01a", "VAW01b", "VAW01c", "VAW01d", "VAW01e")
              ),
          modalitymap = data.frame(
            variable =  
c("VAW01a", "VAW01a", "VAW01a", "VAW01b", "VAW01b", "VAW01b", 
"VAW01c", "VAW01c", "VAW01c", "VAW01d", "VAW01d", "VAW01d", "VAW01e", 
"VAW01e", "VAW01e")
               ,
            label =  
c("Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond")
               ,
            standard =  
c("1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 4.2")
  } else {

datalist[["main"]]$outcome4_2<- dplyr::case_when(
     as.integer(datalist[["main"]]$VAW01a) == 1 | 
     as.integer(datalist[["main"]]$VAW01b) == 1 |  
     as.integer(datalist[["main"]]$VAW01c) == 1 |  
     as.integer(datalist[["main"]]$VAW01d) == 1 | 
     as.integer(datalist[["main"]]$VAW01e) == 1 ~ 0,
     
     as.integer(datalist[["main"]]$VAW01a) == 0 & 
     as.integer(datalist[["main"]]$VAW01b) == 0 &  
     as.integer(datalist[["main"]]$VAW01c) == 0 &  
     as.integer(datalist[["main"]]$VAW01d) == 0 & 
     as.integer(datalist[["main"]]$VAW01e) == 0 ~ 1,
     
     TRUE ~ NA_real_)

datalist[["main"]]$outcome4_2  <- labelled::labelled(datalist[["main"]]$outcome4_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                          label = "Proportion of PoC who do not accept 
                          violence against women" )  
  }
   return(datalist) 
}
