# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome1_3
#' 
#' **Proportion of Persons of Concern with legally recognized identity documents or credentials**
#' 
#' This indicator measures the proportion of persons of concern who possess legally 
#' recognized and valid identity documents or credentials.
#' 
#' Establishing one's identity and possessing legally recognized and valid identity
#'  documents or credentials ensures the legal protection of persons of concern,
#'   protection from refoulement, registration of life events to prevent statelessness,
#'    as well as access to services.
#'    
#'    **Definitions**
#'    
#'     Identity document or credential is any document or credential which may be 
#'     used as proof of identity, which may also include reference to the
#'      individuals' legal status and associated rights vis-à-vis the host 
#'      State and/or UNHCR.
#'      
#'  |          Standard Questions           |
#'  |:-------------------------------------:|
#'  | REG01 - REG02 - REG03 / REG05 - REG06 |
#'  
#'  **Numerator**: Total population with valid identity documents or credentials
#'  
#'  **Denominator**: Total population
#'  
#'  **Formula**: ( *REG01=1 \| REG02=1 \| REG03=1 \| REG05=1 \| REG06=1) / Total population*
#'  
#'  This indicator comes from the individual dataset - 
#'  Calculate valid identity documents for under 5 with REG05 and REG06 variables
#'  ind$REG05a - passport
#'  ind$REG05b - civil/government issued ID
#'  ind$REG05c - residency permit
#'  ind$REG05d - statelessness documentation
#'  ind$REG05e - household card of address/family book
#'  ind$REG05f - social security card
#'  ind$REG06 - any other document establishes identity
#'  add birth certificate as additional document from REG03
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome1_3(datalist)
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome1_3,
#'                      iconunicode = "f140")    
#'
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$document_above5,
#'                      iconunicode = "f140")    
#'
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$document_under5,
#'                      iconunicode = "f140")    
outcome1_3 <- function(datalist){
  ## Mapper
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("Passport?", "Birth certificate?", "Civil/government-issued ID card ?", 
"Residency permit (both temporary and permanent)?", "Statelessness documentation?", 
"Household card of address / family book/ marriage certificate?", 
"Social security card?", "2. Does ${name_individual} have any other document that establishes his/her legal identity?", 
"3. Does ${name_individual} have a birth certificate?", "Passport?", 
"Civil/government-issued ID card ?", "Residency permit (both temporary and permanent)?", 
"Statelessness documentation?", "Household card of address / family book/ marriage certificate?", 
"Social security card?", "6. Does ${name_individual} have any other document that establishes your legal identity?"
)
              ,
            variable =  
c("REG01a", "REG01b", "REG01c", "REG01d", "REG01e", "REG01f", 
"REG01g", "REG02", "REG03", "REG05a", "REG05b", "REG05c", "REG05d", 
"REG05e", "REG05f", "REG06")
              ),
          modalitymap = data.frame(
            variable =  
c("REG01a", "REG01a", "REG01a", "REG01b", "REG01b", "REG01b", 
"REG01c", "REG01c", "REG01c", "REG01d", "REG01d", "REG01d", "REG01e", 
"REG01e", "REG01e", "REG01f", "REG01f", "REG01f", "REG01g", "REG01g", 
"REG01g", "REG02", "REG02", "REG02", "REG03", "REG03", "REG03", 
"REG05a", "REG05a", "REG05a", "REG05b", "REG05b", "REG05b", "REG05c", 
"REG05c", "REG05c", "REG05d", "REG05d", "REG05d", "REG05e", "REG05e", 
"REG05e", "REG05f", "REG05f", "REG05f", "REG06", "REG06", "REG06"
)
               ,
            label =  
c("Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Don\'t know", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond", 
"Yes", "No", "Prefer not to respond", "Yes", "No", "Prefer not to respond"
)
               ,
            standard =  
c("1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "98", "1", "0", "99", "1", "0", "99", "1", "0", "99", 
"1", "0", "99", "1", "0", "99", "1", "0", "99", "1", "0", "99"
)
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 1.3")
  } else {
  
  
datalist[["ind"]]$document_under5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG05a) == 1 | 
      as.integer(datalist[["ind"]]$REG05b) == 1 | 
      as.integer(datalist[["ind"]]$REG05c) == 1 | 
      as.integer(datalist[["ind"]]$REG05d) == 1 | 
      as.integer(datalist[["ind"]]$REG05e) == 1 | 
      as.integer(datalist[["ind"]]$REG05f) == 1 |
      as.integer(datalist[["ind"]]$REG06) == 1 | 
      as.integer(datalist[["ind"]]$REG03) == 1 ~ 1, 
      
      as.integer(datalist[["ind"]]$REG05a) != 1 &
      as.integer(datalist[["ind"]]$REG05b) != 1 & 
      as.integer(datalist[["ind"]]$REG05c) != 1 & 
      as.integer(datalist[["ind"]]$REG05d) != 1 & 
      as.integer(datalist[["ind"]]$REG05e) != 1 & 
      as.integer(datalist[["ind"]]$REG05f) != 1 & 
      as.integer(datalist[["ind"]]$REG06) != 1 & 
      as.integer(datalist[["ind"]]$REG03) != 1 ~ 0, 
      
      TRUE ~ NA_real_   )

datalist[["ind"]]$document_under5  <- labelled::labelled(datalist[["ind"]]$document_under5,
                            labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Proportion of Persons above 5 with legally
                      recognized identity documents or credentials")
  
  ###Calculate  valid identity documents for above 5 with REG01 and REG02 variables
  #ind$REG01a # passport
  #ind$REG01b # birth certificate
  #ind$REG01c # civil/ government issued ID
  #ind$REG01d # residency permit
  #ind$REG01e # statelessness documentation
  #ind$REG01f # household card of address/family book
  #ind$REG01g # social security card
  #ind$REG02 # any other document establishes identity

#Make sure to delete REG01e below from the script if you don't have any stateless   

datalist[["ind"]]$document_above5 <- dplyr::case_when(
      as.integer(datalist[["ind"]]$REG01a) == 1 | 
      as.integer(datalist[["ind"]]$REG01b) == 1 | 
      as.integer(datalist[["ind"]]$REG01c) == 1 | 
      as.integer(datalist[["ind"]]$REG01d) == 1 | 
      as.integer(datalist[["ind"]]$REG01e) == 1 | 
      as.integer(datalist[["ind"]]$REG01f) == 1 | 
      as.integer(datalist[["ind"]]$REG01g) == 1 |
      as.integer(datalist[["ind"]]$REG02) == 1 ~ 1,
      
      as.integer(datalist[["ind"]]$REG01a) != 1 & 
      as.integer(datalist[["ind"]]$REG01b) != 1 & 
      as.integer(datalist[["ind"]]$REG01c) != 1 & 
      as.integer(datalist[["ind"]]$REG01d) != 1 & 
      as.integer(datalist[["ind"]]$REG01e) != 1 & 
      as.integer(datalist[["ind"]]$REG01f) != 1 & 
      as.integer(datalist[["ind"]]$REG01g) != 1 & 
      as.integer(datalist[["ind"]]$REG02) != 1 ~ 0, 
      
      TRUE ~ NA_real_)

datalist[["ind"]]$document_above5  <- labelled::labelled(datalist[["ind"]]$document_above5,
                            labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Proportion of Persons above 5 with legally
                      recognized identity documents or credentials")
      
  ##Combine both age groups
datalist[["ind"]]$outcome1_3<- dplyr::case_when(
     (datalist[["ind"]]$document_above5 == 1 | 
      datalist[["ind"]]$document_under5 == 1 ) ~ 1,
     
     (datalist[["ind"]]$document_above5 == 0 | 
      datalist[["ind"]]$document_under5 == 0 ) ~ 0)

datalist[["ind"]]$outcome1_3  <- labelled::labelled(datalist[["ind"]]$outcome1_3,
                            labels = c('Yes' = 1, 'No' = 0 ),
                      label = "Proportion of Persons with legally
                      recognized identity documents or credentials")
  
  }
   return(datalist)
}
