# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome16_2
#' 
#'  **Proportion of Persons of Concern covered by social protection floors/systems**
#'  This indicator measures the proportion of persons of concern who receive government social protection benefits.
#'  Social protection is a set of policies and programmes aimed at preventing or 
#'  protecting all people against poverty, vulnerability and social exclusion 
#'  throughout their life-course, with particular emphasis on vulnerable groups.
#'   For persons of concern, being part of a social protection system is a measure
#'    of integration and stability. This indicator is linked to SGD indicator
#'     [1.3.1](https://unstats.un.org/sdgs/metadata/files/Metadata-01-03-01a.pdf).
#'  
#'  This indicator focuses on the social benefits received from the government in which UNHCR might be supporting UNHCR.
#'  
#'  |    Standard Questions     | 
#'  |:-------------------------:|
#'  | SPF01                     |
#'  
#'  **Numerator**: Total population covered by social protection floors/systems
#'  **Denominator**: Total population
#'  **Formula**: *SPF01*=1 
#'  
#' This indicator is calculated from the main dataset
#' If PoC has covered by at least one of the social protection floors/systems
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome16_2(datalist)
#'
#' table( datalist[["main"]]$outcome16_2, useNA = "ifany")
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome16_2,
#'                      iconunicode = "f140")   
outcome16_2 <- function(datalist ){
   # Mapper , 

mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("Social protection cash benefit", "Parental benefit", "Disability benefit", 
"Unemployment benefit", "Employment injury benefit", "Old-age pension", 
"Other vulnerability benefit", "Social assistance cash benefit"
)
              ,
            variable =  
c("SPF01a", "SPF01b", "SPF01c", "SPF01d", "SPF01e", "SPF01f", 
"SPF01g", "SPF01h")
              ),
          modalitymap = data.frame(
            variable =  
c("SPF01a", "SPF01a", "SPF01a", "SPF01b", "SPF01b", "SPF01b", 
"SPF01c", "SPF01c", "SPF01c", "SPF01d", "SPF01d", "SPF01d", "SPF01e", 
"SPF01e", "SPF01e", "SPF01f", "SPF01f", "SPF01f", "SPF01g", "SPF01g", 
"SPF01g", "SPF01h", "SPF01h", "SPF01h")
               ,
            label =  
c("Yes", "No", "Don\'t know", "Yes", "No", "Don\'t know", "Yes", 
"No", "Don\'t know", "Yes", "No", "Don\'t know", "Yes", "No", "Don\'t know", 
"Yes", "No", "Don\'t know", "Yes", "No", "Don\'t know", "Yes", 
"No", "Don\'t know")
               ,
            standard =  
c("1", "0", "98", "1", "0", "98", "1", "0", "98", "1", "0", "98", 
"1", "0", "98", "1", "0", "98", "1", "0", "98", "1", "0", "98"
)
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 16.2")
  } else {
  
datalist[["main"]]$outcome16_2 <- dplyr::case_when(
    datalist[["main"]]$SPF01a == 1 |
    datalist[["main"]]$SPF01b == 1 |
    datalist[["main"]]$SPF01c == 1 |
    datalist[["main"]]$SPF01d == 1 | 
    datalist[["main"]]$SPF01e == 1 | 
    datalist[["main"]]$SPF01f == 1 | 
    datalist[["main"]]$SPF01g == 1 | 
    datalist[["main"]]$SPF01h == 1 ~ 1, 
    TRUE ~ 0)

  datalist[["main"]]$outcome16_2  <- labelled::labelled(datalist[["main"]]$outcome16_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
   label = "Proportion of Persons of Concern covered by social protection 
   floors/systems")
  
  }
   return(datalist)
}
