# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome13_3#' 
#' 
#' **Proportion of Persons of Concern (working age) who are unemployed**
#' The unemployment rate is a standard indicator to measure the efficiency and effectiveness of an economy.
#' For Persons of Concern, access to employment is central for self-reliance, socio-economic inclusion and dignity and often restricted through laws, policies or practical barriers.
#' This indicator is also linked to SGD [8.5.2](https://unstats.un.org/sdgs/metadata/files/Metadata-08-05-02.pdf).
#' The standard questionnaire module is from [Standardized Employment Module](https://www.unhcr.org/5ea81b954) of UNHCR.
#' The calculations are also done based on the same guidance.
#' | Standard Questions |
#' |:------------------:|
#' |   UNEM01-UNEM10    |
#' 
#' **Numerator**: Unemployed working age population within a country
#' 
#' **Denominator**: Total working age population who are employed and unemployed within a country (often referred to as labour force)
#' 
#' **Formula**: *UNEM01*=1 \| (*UNEM02*=1 & *UNEM07*=3) \| *UNEM04*=1 \| (*UNEM02*=1 & *UNEM07*=1 &( *UNEM08*=1,2)) \|(*UNEM05*=1 & *UNEM06*=3) \| ( *UNEM05*=1 & ( *UNEM06*=1,2 \| *UNEM08*=1,2)
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' 
#' 
#' #Numerator: Those of working age who were not in employment, looked for employment in the past 30 days and were available to take up employment
####Denominator: Those of working age in labour force
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome13_3(datalist )
#'
#' table( datalist[["main"]]$outcome13_3, useNA = "ifany")
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome13_3,
#'                      iconunicode = "f140")   
outcome13_3 <- function(datalist ){
  # mapper , 

mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. During the past 7 days, did ${name_selectedadult18} work for someone else for pay, for one or more hours?", 
"2. During the past 7 days, did ${name_selectedadult18} run or do any kind of business, farming, or other activity to generate income?", 
"3. During the past 7 days, did ${name_selectedadult18} help in a family business or farm?", 
"4. Even though ${name_selectedadult18} did not work, during the past 7 days, did he/she have a paid job from which he/she was temporarily absent?", 
"5. Even though ${name_selectedadult18} did not work, during the past 7 days, did he/she have a business or a helper job in a family business/farm from which he/she was temporarily absent?", 
"6. Last week, did ${name_selectedadult18} do any work in\u2026?", 
"7. Was this work that  ${name_selectedadult18} mentioned in...?", 
"8. Thinking about this work, are the products intended...?", 
"9. During the last 30 days, did ${name_selectedadult18} do anything to find a paid job or try to start a business?", 
"10. Could ${name_selectedadult18} start working within the next two weeks?"
)
              ,
            variable =  
c("UNEM01", "UNEM02", "UNEM03", "UNEM04", "UNEM05", "UNEM06", 
"UNEM07", "UNEM08", "UNEM09", "UNEM10")
              ),
          modalitymap = data.frame(
            variable =  
c("UNEM01", "UNEM01", "UNEM02", "UNEM02", "UNEM03", "UNEM03", 
"UNEM04", "UNEM04", "UNEM05", "UNEM05", "UNEM06", "UNEM06", "UNEM06", 
"UNEM07", "UNEM07", "UNEM07", "UNEM08", "UNEM08", "UNEM08", "UNEM08", 
"UNEM09", "UNEM09", "UNEM10", "UNEM10")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", 
"No", "Farming or rearing farm animals", "Fishing or fish farming", 
"None of the above", "Farming or rearing farm animals", "Fishing or fish farming", 
"None of the above", "Only for sale", "Mainly for sale", "Only for family use", 
"Mainly for family use", "Yes", "No", "Yes", "No")
               ,
            standard =  
c("1", "0", "1", "0", "1", "0", "1", "0", "1", "0", "1", "2", 
"3", "1", "2", "3", "1", "2", "3", "4", "1", "0", "1", "0")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 13.23")
  } else {
  

datalist[["main"]]$employed <- dplyr::case_when(
  
    as.integer(datalist[["main"]]$UNEM01) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$UNEM02) == 1 & 
    as.integer(datalist[["main"]]$UNEM07) == 3 ~ 1,
    
    as.integer(datalist[["main"]]$UNEM04) == 1 ~ 1,
    
    as.integer(datalist[["main"]]$UNEM02) == 1 & 
    as.integer(datalist[["main"]]$UNEM07) == 1 & 
      (as.integer(datalist[["main"]]$UNEM08) == 1 | 
       as.integer(datalist[["main"]]$UNEM08) == 2) ~ 1,
    
    as.integer(datalist[["main"]]$UNEM05) == 1 & 
    as.integer(datalist[["main"]]$UNEM06) == 3 ~ 1,
    as.integer(datalist[["main"]]$UNEM05) == 1 & 
     ( as.integer(datalist[["main"]]$UNEM06) == 1 | 
       as.integer(datalist[["main"]]$UNEM06) == 2) & 
     ( as.integer(datalist[["main"]]$UNEM08) == 1 | 
       as.integer(datalist[["main"]]$UNEM08) == 2) ~ 1,
    TRUE ~ 0)


datalist[["main"]]$employed  <- labelled::labelled(datalist[["main"]]$employed,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion employed")


datalist[["main"]]$unemployed<- dplyr::case_when(
    as.integer(datalist[["main"]]$employed) == 0 & 
    as.integer(datalist[["main"]]$UNEM09) == 1 & 
    as.integer(datalist[["main"]]$UNEM10) == 1 ~ 1,
    TRUE ~ 0)


datalist[["main"]]$unemployed  <- labelled::labelled(datalist[["main"]]$unemployed,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion unemployed")

datalist[["main"]]$labour_force <- dplyr::case_when(
    datalist[["main"]]$employed == 1 | 
    datalist[["main"]]$unemployed == 1 ~ 1)


datalist[["main"]]$labour_force  <- labelled::labelled(datalist[["main"]]$labour_force,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion forming labour force")

datalist[["main"]]$outcome13_3 <- dplyr::case_when(
  (datalist[["main"]]$unemployed == 1 &  
  datalist[["main"]]$labour_force == 1)  ~ 1,
  (datalist[["main"]]$employed == 1 &  
  datalist[["main"]]$labour_force == 1)  ~ 0,
      TRUE ~ NA_real_   )
  

datalist[["main"]]$outcome13_3  <- labelled::labelled(datalist[["main"]]$outcome13_3,
                            labels = c('Yes' = 1, 'No' = 0 ),
      label = "Proportion of unemployed while being part of labour force")

  }
 return(datalist)
    
}
