# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome5_2
#' 
#' **Proportion of children who participate in community-based child protection programmes**
#' 
#' The indicator is defined as the the proportion of children who participate in community-based child protection programmes.
#' The module for this question comes from UNHCR Core indicator metadata.
#' 
#' Children' participation in community-based recreational and child protection activities is a key mechanism for the protection of children by providing children with a protected environment in which they can participate in organized activities to play, socialize, learn, and express themselves, promoting their psycho-social well-being and reducing the risk of abuse, violence or exploitation.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |   COMM01-COMM04    |
#' 
#' **Numerator**: Total number of children between 4-17 years who participate in community-based recreational and child protection programmes
#' 
#' **Denominator**: Total [number of children between 4-17 years
#' 
#' **Formula**: ( *COMM01=1 & COMM02 \>=2 \| & COMM03=1 & COMM04=1) / Total number of children 4-17 years*
#' This indicator comes from the individual level dataset
#' 
#'  
#' Children who participate in community-based programmes at least 2 times, under adult supervision in a physically safe area
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome5_2(datalist  )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome5_2,
#'                      iconunicode = "f140")   
outcome5_2 <- function(datalist){
  ## Mapper , 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
c("1. Has ${child_edu_name} participated in sports, arts, cultural activities or other after-school programmes for children outside the home in the last month?", 
"2. In the past month, how many times did ${child_edu_name} participate in these activities?", 
"3. Were they in a physically safe area while participating in the activity?", 
"4. Were there adults supervising the activities?")
              ,
            variable =  
c("COMM01", "COMM02", "COMM03", "COMM04")
              ),
          modalitymap = data.frame(
            variable =  
c("COMM01", "COMM01", "COMM02", "COMM03", "COMM03", "COMM03", 
"COMM04", "COMM04", "COMM04")
               ,
            label =  
c("Yes", "No", NA, "Yes", "No", "Don't know", "Yes", "No", "Don't know"
)
               ,
            standard =  
c("1", "0", NA, "1", "0", "98", "1", "0", "98")
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 5.2")
  } else {
  
datalist[["ind"]]$outcome5_2<- dplyr::case_when(
     ( as.integer(datalist[["ind"]]$COMM01) == 1 & 
       as.integer(datalist[["ind"]]$COMM02) >= 2 & 
       as.integer(datalist[["ind"]]$COMM03) == 1 & 
       as.integer(datalist[["ind"]]$COMM04) == 1) ~ 1,
     
     ( as.integer(datalist[["ind"]]$COMM01) == 0 | 
     ( as.integer(datalist[["ind"]]$COMM02) < 2 | 
       as.integer(datalist[["ind"]]$COMM02) == 98 ) | 
      ( as.integer(datalist[["ind"]]$COMM03) == 0 | 
        as.integer(datalist[["ind"]]$COMM03) == 98) |
       ( as.integer(datalist[["ind"]]$COMM04) == 0 | 
         as.integer(datalist[["ind"]]$COMM04) == 98)) ~ 0, 
     
     TRUE ~ NA_real_)

datalist[["ind"]]$outcome5_2  <- labelled::labelled(datalist[["ind"]]$outcome5_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                              label = "Proportion of children who participate 
                            in community-based child protection programmes")
  }
   return(datalist)
}
