# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome13_1
#' 
#' **Proportion of Persons of Concern with an account at a bank or other financial institution or with a mobile-money-service provider**
#' 
#' This indicator measures the percentage of persons of concern (ages 15+) who report having an account (by themselves or together with someone else) at a bank or another type of financial institution or personally using a mobile money service in the past 12 months in the country of asylum or habitual residence (for returnees, countries of origin are included).
#' 
#' The methodology is taken from [The Global Findex Database](https://www.worldbank.org/en/publication/globalfindex) which is developed by the World Bank.
#' This indicator is also linked to SGD Indicator [8.10.2](https://unstats.un.org/sdgs/metadata/files/Metadata-08-10-02.pdf).
#' 
#' | Standard Questions |
#' |:------------------:|
#' |   BANK01-BANK05    |
#' 
#' **Numerator**: Total population having a personal mobile or bank account
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: *BANK01*=1 \| *BANK02*=1 \| *BANK03*=1 \|*BANK05*=1
#' This indicator comes from main dataset based on the respondent randomly selected for individual level
#' include if the respondent has an account on their own/with someone else, ATM card, personal bank card
#' or personally used phone to send money (proxy)
#' 
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome13_1(datalist )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome13_1,
#'                      iconunicode = "f140")   
outcome13_1 <- function(datalist){
  
  ## Mapper , 
mapper = list(
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. Do you, either by yourself or together with someone else, currently have an account at a bank or another type of formal financial institution in ${countryname} ?", 
"2. Do you, personally, have a/an [local terminology for ATM/debit card] in ${countryname} ?", 
"3. Is this [local terminology for ATM/debit card] connected to an account with your name on it in ${countryname} ?", 
"4. In the past 12 months, have you used a mobile phone to make payments, to buy things, or to send or receive money?", 
"5. In the past 12 months, have you, personally, used a mobile phone to make payments, to buy things, or to send or receive money using a service such as [local example of mobile money from GSMA database, like M-PESA]?"
)
              ,
            variable =  
c("BANK01", "BANK02", "BANK03", "BANK04", "BANK05")
              ),
          modalitymap = data.frame(
            variable =  
c("BANK01", "BANK01", "BANK02", "BANK02", "BANK03", "BANK03", 
"BANK04", "BANK04", "BANK05", "BANK05")
               ,
            label =  
c("Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", 
"No")
               ,
            standard =  
c("1", "0", "1", "0", "1", "0", "1", "0", "1", "0")
              ))
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 13.1")
  } else {
  
datalist[["main"]]$outcome13_1 <- dplyr::case_when(
      as.integer(datalist[["main"]]$BANK01) == 1 | 
      as.integer(datalist[["main"]]$BANK02) == 1 | 
      as.integer(datalist[["main"]]$BANK03) == 1 |
      as.integer(datalist[["main"]]$BANK05) == 1 ~ 1,
      
      as.integer(datalist[["main"]]$BANK01) == 0 & 
      as.integer(datalist[["main"]]$BANK02) == 0 & 
      as.integer(datalist[["main"]]$BANK03) == 0 & 
      as.integer(datalist[["main"]]$BANK05) == 0 ~ 0,
      TRUE ~ 0)

datalist[["main"]]$outcome13_1  <- labelled::labelled(datalist[["main"]]$outcome13_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
                label = "PoC with an account at a bank or other financial 
                institution or with a mobile-money service provider")
  
}
   return(datalist)
}
