# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome10_1
#' 
#' 
#' **Proportion of children aged 9 months to five years who have received measles vaccination**
#' 
#' Coverage of measles vaccination in children in the target age group of 9 months to 5 years of age.
#' Measles vaccination is an essential preventive primary care intervention to protect children from measles infection.
#' 
#' Standard module is from [UNICEF MICS6](https://mics.unicef.org/tools#survey-design) Children under 5 module.
#' The calculation of this module is also aligned with UNICEF MICS6.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |    MMR01-MMR04     |
#' 
#' **Numerator**: Total number of children 9 months to 5 years who have received a measles containing vaccine (measles or MMR- Measles Mumps and Rubella)
#' 
#' **Denominator**: Total number of children 9 months to 5 years
#' 
#' **Formula**: *MMR03=*1 / Total number of children 9 months to 5 years
#' 
#' This comes from the main dataset
#' 
#' MICS TC.1.1 UNICEF calculates on the first dose received##
#' Children who had et least one dose of measles vaccination
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#'
#' ## Apply indicator function on datalist
#' datalist <- outcome10_1(datalist)
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["ind"]]$outcome10_1,
#'                      iconunicode = "f140")   
outcome10_1 <- function(datalist){
  # Mapper , 
mapper = list(
           hierarchy = "ind",
          variablemap = data.frame(
            label = 
"3. Has ${indiv_05Less_name} ever received a measles containing vaccine(i.e. measles, MR or MMR)? That is a shot at the age of 9 months or older - to prevent (him/her) from getting measles"
              ,
            variable =  
"MMR03"
              ),
          modalitymap = data.frame(
            variable =  
c("MMR03", "MMR03", "MMR03")
               ,
            label =  
c("Yes", "No", "Don\'t know")
               ,
            standard =  
c("1", "0", "98")
              ))
  
  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper) 
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 10.1")
  } else {
  
  
datalist[["ind"]]$outcome10_1 <- dplyr::case_when(
    as.integer(datalist[["ind"]]$MMR03) == 1 ~ 1, 
    
    as.integer(datalist[["ind"]]$MMR03) == 0  |
    as.integer(datalist[["ind"]]$MMR03) == 98 ~ 0)

datalist[["ind"]]$outcome10_1  <- labelled::labelled(datalist[["ind"]]$outcome10_1,
                            labels = c('Yes' = 1, 'No' = 0 ),
     label = "Proportion of children aged 9 months to five years who have received measles vaccination")
}
   return(datalist)
}
