# WARNING - Generated by {fusen} from dev/indicators.Rmd: do not edit by hand

#' outcome8_2
#' 
#' 
#' **Proportion of Persons of Concern with primary reliance on clean (cooking) fuels and technology**
#' 
#' This indicator measures the proportion of population who use clean fuel and technology as primary source of cooking.
#' Any type of cooking fuel and technology meeting the WHO set standards on indoor air emissions, as their main cooking solution.
#' This is also linked to SGD indicator [7.1.2](https://sdg-tracker.org/energy) .
#' 
#' The standard questions are similar to MICS and the calculation of indicators are based on [UNICEF MICS](https://mics.unicef.org/files?job=W1siZiIsIjIwMTcvMDIvMDMvMTYvMjcvMjUvNTk5L1BpY3RvcmlhbHNfV0hPX0hvdXNlaG9sZF9FbmVyZ3lfVXNlX0NhdGFsb2d1ZV9TZXB0ZW1iZXJfMjAxNl8ucGRmIl1d&sha=57b4a452fcc0ac88) and [WHO](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/5662) guidance on the calculation of the same SGD indicator.
#' 
#' | Standard Questions |
#' |:------------------:|
#' |   COOK01- COOK03   |
#' 
#' **Numerator**: Percentage of population with primary reliance on clean fuels and technologies for cooking
#' 
#' **Denominator**: Total population
#' 
#' **Formula**: COOK01=1 (there is a cooking device) & (COOK02=1,2,3,4,5) \| (COOK02=6 & COOK03=1,2) / Total Population
#' 
#' This indicator comes from household level dataset
#' Based on MICS calculation : TC4.1
#' 
#' @param datalist A list with all hierarchical data frame for a survey data set.
#'    format is expected to match the Excel export synchronized from kobo to RILD
#'    and loaded with  kobocruncher::kobo_data() 
#' 
#' @importFrom dplyr mutate case_when
#' @importFrom labelled labelled
#' 
#' @return new calculated variable - appended or not...
#' 
#' @export
#' @examples
#' ## data, cf example  fct_re_map()
#' datalist <- kobocruncher::kobo_data( system.file("dummy_RMS_CAPI_v2_mapped.xlsx", 
#'                                                  package = "IndicatorCalc"))
#' ## Apply indicator function on datalist
#' datalist <- outcome8_2(datalist )
#'
#' ## Visualise value
#' fct_plot_indic_donut(indicator = datalist[["main"]]$outcome8_2,
#'                      iconunicode = "f140")   
outcome8_2 <- function(datalist){
mapper = list(
           hierarchy = "ind",
           hierarchy = "main",
          variablemap = data.frame(
            label = 
c("1. Is any food or drink consumed by household members cooked or prepared at the household dwelling using a cookstove, fire or other cooking device?", 
"2. What does this household use for cooking most of the time, including cooking food, making tea/coffee, boiling drinking water?", 
"3. What type of fuel or energy source does this household use most of the time in this cookstove or device for cooking food, making tea/coffee and boiling drinking water?"
)
              ,
            variable =  
c("COOK01", "COOK02", "COOK03")
              ),
          modalitymap = data.frame(
            variable =  
c("COOK01", "COOK01", "COOK02", "COOK02", "COOK02", "COOK02", 
"COOK02", "COOK02", "COOK02", "COOK02", "COOK02", "COOK02", "COOK02", 
"COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", 
"COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", 
"COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", "COOK03", 
"COOK03")
               ,
            label =  
c("Yes", "No", "Solar cooker (thermal energy from the sun, not solar panels)", 
"Electric stove", "Piped natural gas stove", "Biogas stove", 
"Liquefied petroleum gas (LPG)/ cooking gas stove", "Liquid fuel stove", 
"Manufactured solid fuel stove", "Traditional solid fuel stove (non-manufactured)", 
"Moveable firepan", "Three stone stove/open fire", "Other, specify", 
"Alcohol/ethanol", "Liquefied petroleum gas", "Biogas", "Electricity from the national grid", 
"Electricity from solar mini-grid", "Electricity from diesel generator", 
"Electricity from hybrid mini-grid (i.e., solar+ diesel, solar+ national grid, etc..)", 
"Gasoline/diesel (not in generator)", "Kerosene/paraffin", "Coal/lignite unprocessed", 
"Coal/lignite briquettes/pellets", "Charcoal unprocessed", "Charcoal briquettes/pellets", 
"Wood (collected)", "Wood (distributed/purchased)", "Agricultural or crop residue/grass/ straw/ shrubs/ corn cobs", 
"Animal waste/dung", "Processed biomass pellets/briquettes", 
"Woodchips", "Garbage/plastic", "Sawdust", "Other, specify")
               ,
            standard =  
c("1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
"96", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", 
"12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "96"
)
              ))

  ## So first we check that we have what we need in the data set based on the mapper
  check_map <- fct_check_map(datalist = datalist,
                             mapper = mapper)
  if ( check_map == FALSE) {
   cat( "There are missing data requirement to calculate Indicator Outcome 8.2")
  } else {
     
datalist[["main"]]$outcome8_2 <- dplyr::case_when(
       ( as.integer(datalist[["main"]]$COOK01) == 1 & 
           (datalist[["main"]]$COOK02 %in% c("1", "2", "3", "4", "5")) |
           (datalist[["main"]]$COOK02 %in% c("6") & 
            datalist[["main"]]$COOK03 %in% c("1", "3")) ) ~  1,
       
       ( as.integer(datalist[["main"]]$COOK01) == 1 & 
          (datalist[["main"]]$COOK02 %in% c("7", "8", "9", "10", "96")) |
          ((datalist[["main"]]$COOK02 %in% c("6") &
              !(datalist[["main"]]$COOK03 %in% c("1", "3") )))) ~  0 ,
       TRUE ~ NA_real_ )

datalist[["main"]]$outcome8_2  <- labelled::labelled(datalist[["main"]]$outcome8_2,
                            labels = c('Yes' = 1, 'No' = 0 ),
                    label = "Proportion of Persons of Concern with
                    primary reliance on clean (cooking) fuels and technology")
  }

   return(datalist)
}
